### ISSUE TITLE
Shared tests should be not be mututally exclusive with dedicated tests

### ISSUE THREAD

**Issue by yves-vogl** [ansible-community/molecule#1515]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.7.0
  config file = None
  configured module search path = ['/Users/vogl/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/vogl/Development/ansible-roles/ansible-role-docker/.direnv/python-3.7.0/lib/python3.7/site-packages/ansible
  executable location = /Users/vogl/Development/ansible-roles/ansible-role-docker/.direnv/python-3.7.0/bin/ansible
  python version = 3.7.0 (default, Jun 29 2018, 20:13:13) [Clang 9.1.0 (clang-902.0.39.2)]
```

```
molecule, version 2.18.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

It's pretty easy to include tests from another scenario by using the directory option. It'd be great if this could be treated like a base directory so that you can not only include those shared tests but also execute your local ones also.

```yaml

verifier:
  name: testinfra
  directory: ../default/tests/

```

**Comment by ssbarnea** [comment]
I think that current behavior is good enough and based on lack of activity I think is the time to close it.

**Comment by yves-vogl** [comment]
Maybe I find some time to implement this. Would you accept a PR in that case?

**Comment by ssbarnea** [comment]
Sure! More than welcomed.
