### ISSUE TITLE
random failures of Build an Ansible compatible image task

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#1529]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.1 (from pip)
molecule, version 2.19.0 (from pip)
```
# Desired Behavior

Predictable execution output, avoidind random failures to build docker images.

# Actual Behaviour (Bug report only)

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.
```
TASK [Build an Ansible compatible image] ***************************************
    failed: [localhost] (item=None) => {
        "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
        "changed": false
    }
    changed: [localhost] => (item=None)
    fatal: [localhost]: FAILED! => {
        "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
        "changed": true
    }
```

**Comment by ssbarnea** [comment]
I didn't had the time to investigate more this issue but. if no_log is an issue, why not making no_log conditional based on results? 

I succesfully used in the past `no_log: result.rc == 0` so silence successes.

**Comment by dj-wasabi** [comment]
@wilmardo Thanks! Was indeed also an option.

@ssbarnea If you can't provide the information then we can't help you?

**Comment by ssbarnea** [comment]
@wilmardo I am not sure if this is duplicate of that bug because is unrelated to linting but the good news is that it seems not to be too hard to replicate. I just came to it on Travis  see https://travis-ci.com/ssbarnea/mooolecule/builds/90120293?utm_medium=notification&utm_source=email

I mention that I do run locally without problems now, so time to add `MOLECULE_DEBUG=true` to travis now.

**Comment by ssbarnea** [comment]
I tried to define `MOLECULE_DEBUG=true` on travis and it seems to have no effect at all.
See https://travis-ci.com/ssbarnea/mooolecule/jobs/156065099#L487

**Comment by wilmardo** [comment]
@ssbarnea You need to add `--debug` to the execution of molecule. Molecule overrides the env var MOLECULE_DEBUG on runtime based on that flag.

Curious to see what is happening :)

**Comment by ssbarnea** [comment]
MOLECULE_DEBUG=true  was defined in travis config and which is used by makefile which passed the variable explicitly to molecule. Not sure why it didn't work but I will add an exclicit --debug just so we can findout what happens. Sadly testing travis requires lots of pushes.

**Comment by webknjaz** [comment]
> if no_log is an issue, why not making no_log conditional based on results?

Because the main purpose of `no_log` is to hide potentially sensitive output. You really don't want to leak any of such data to logs in prod(-like) envs :)
`--debug`, however, lets you figure out problems in your trusted env, without forgetting to set it back for prod.

**Comment by webknjaz** [comment]
> Not sure why it didn't work but

Maybe `ANSIBLE_DEBUG=1`?

**Comment by webknjaz** [comment]
Oh.. I see. `MOLECULE_DEBUG` is used explicitly for `no_log`s

**Comment by ssbarnea** [comment]
Well, now we have a clean failure: https://travis-ci.com/ssbarnea/mooolecule/jobs/156138203#L806

Two things to learn about it:
* assure docker module is installed by default with molecule
* assure that we use conditional no_log based on result code to avoid hiding useful output (the error)

In the past, I succesfully use a line like below to achieve this:
```
register: result
no_log: result.rc != 0
```

**Comment by webknjaz** [comment]
As I said earlier, I'm against conditional `no_log`, error results are even more likely to expose creds. What you suggest is a security breach: https://github.com/ansible/molecule/issues/1529#issuecomment-435624464

**Comment by wilmardo** [comment]
> assure docker module is installed by default with molecule

See #1539

**Comment by ssbarnea** [comment]
@webknjaz I can understand the concerns related to security but at the same time we should not cripple testing and provide a very bad user experience just be cause in-some cases some sensitive information could be leaked.

For example, when testing on Travis with local docker, you don't need any creadentials, so there is nothing to leak.

I think that molecule should at least allow user to control the no_log behavior, having it hardcoded to diabled or only enabled with --debug mode, is making it close to useless. Debug mode is extreamly verbose and is supposed to be run only on exceptional cases, some kind of last resort measure. 

If I could define a variable like `MOLECULE_LOGGING=default,on-error,always,never` we should be fine, as it would still allow user to control bahaviour and make a decision.

I wonder if would not even make sense to use no_log only when called with a non interactive TTY, assuming that an interactive TTY is unlikely to expose credentials. We should think about this.

Summary: as a user (story): I do not expect to see meaningless error message on execution. When something fails in molecule, I should not be required to rerun the entire task again in debug mode in order to figure out what was the cause of the error.

**Comment by webknjaz** [comment]
@ssbarnea the use case makes total sense to me, but I think we shouldn't rush with decisions, which might be costly to revert. I think, we need a separate issue (maybe in ansible/proposals?), where this would be discussed.

**Comment by wilmardo** [comment]
> P.S. First, I want to understand why no_log was used in the first place by the original authors of those playbooks.

@retr0h Could you shed some light on this?
