### ISSUE TITLE
devel: consolidate linting into a single job (tox target)

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#1596]
# Issue Type

- Feature request

# Molecule and Ansible details

At this moment in order to preform only linting a developer would have to run this command:
```
tox -e py27-lint,py36-lint,py37-lint,format-check
```

This is insanely long command and I really doubt anyone is actively using it. 

Also is takes a huge amount of disk space as it creates 4 different environments without any practical reasons, especially as it makes no sense to run linting with 3 different intepretes, using the latest supported version is more than enough. 

PS.  Please note that the alternative of using the oldest interpreter (py27) is not as good as the newest one because it is known that the parsing ability of the newer ones is greatlly improved. 

Also CI job should be updated to assure the same execution, matching local development usage.

Proposed command
```
tox -e lint
```

This approach is also future proof as we could add new linters or swap exiting ones without changing the user interface, the job would still have the same name regardless what internal tools are used at a moment.

**Comment by webknjaz** [comment]
I'd like to see separate envs for different checks. I'd default to the current `python` executable, not bound to version. In CI we use Python 3.7, specified on the config level.

**Comment by webknjaz** [comment]
Oh, and another thought: I tend to use pre-commit.com tool to consolidate linters in one place and then, additionally to CI, users may optionally set that up as a pre-commit or pre-push hook in their local repo with just a single one-time command.

**Comment by decentral1se** [comment]
PR out for review on this: https://github.com/ansible/molecule/pull/1800.

**Comment by webknjaz** [comment]
> py27-lint,py36-lint,py37-lint,format-check

you can do:
```ini
[toxenv:lint]
commands =
    {[py37-lint]commands}
    {[format-check]commands}
```

To achieve this.

**Comment by ssbarnea** [comment]
Done, long time ago.
