### ISSUE TITLE
Docker driver: create.yml jinja expression always evaulates to True

### ISSUE THREAD

**Issue by Rickkwa** [ansible-community/molecule#1688]
Hi,

So I've been looking at [molecule/provisioner/ansible/playbooks/docker/create.yml](https://github.com/ansible/molecule/blob/f09b039e69a599df5a56fe5359647e6ed1821fd3/molecule/provisioner/ansible/playbooks/docker/create.yml).

Specifically, [line 48](https://github.com/ansible/molecule/blob/f09b039e69a599df5a56fe5359647e6ed1821fd3/molecule/provisioner/ansible/playbooks/docker/create.yml#L48):

```
- platforms.changed or docker_images.results | map(attribute='images') | select('equalto', []) | list | count >= 0
```

The reason I am looking at this line specifically was because it used `equalto` which isn't on Jinja 2.7.2 (which is the latest version in yum on RHEL/CentOS 7). I wanted to see if I can make a PR which doesn't require the use of `equalto`, and while looking at this line I noticed something. Wouldn't `docker_images.results | map(attribute='images') | select('equalto', []) | list | count >= 0` always be true since it is doing a `count` on a list? Or am I missing something here.

If this is supposed to be `>` instead of `>=`, then may I also suggest the following change to avoid `equalto`:

```
- platforms.changed or [] in docker_images.results | map(attribute='images') | list
```

**Comment by lwm** [comment]
Well, seems like yes, we have a bug:

```python
>>> import yaml
>>> from jinja2 import Template
>>> print(Template("""{{ [] | select('equalto', []) | list | count >= 0 }}""").render())
True
>>> print(Template("""{{ ['my-cool-image'] | select('equalto', []) | list | count >= 0 }}""").render())
True
```

And if we're using unsupported selects for current mainstream distros, then we should probably use something more widely available. Ideally, you could also come up with for this to be tested. I'm not quite familiar with the functional tests but that would probably be where they would go. 

This is core functionality of this driver. So, I wonder why no one complained. Or was nobody noticing when the image was being built over and over again? I'm not sure.

**Comment by lwm** [comment]
Any news on a fix for this @Rickkwa?

**Comment by Rickkwa** [comment]
@lwm I haven't looked into this any deeper yet. One of these days I'll have to learn how to contribute to Molecule - ie. workflow, test cases, etc.

**Comment by Rickkwa** [comment]
@lwm 

> This is core functionality of this driver. So, I wonder why no one complained. Or was nobody noticing when the image was being built over and over again? I'm not sure.

Looks like molecule has a state file in `/tmp/molecule/<role>/<scenario>/state.yml` that has `created: true` so it won't create the instance again:

```
--> Action: 'create'
Skipping, instances already created.
```

**Comment by lwm** [comment]
@Rickkwa, right, that makes sense! Thanks :wave:
