### ISSUE TITLE
Test containers with systemd support

### ISSUE THREAD

**Issue by vutkin** [ansible-community/molecule#1768]
# Issue Type

- Feature request

Hi @themr0c , @Lowess , @decentral1se.
We support next docker images with systemd on-board for testing our roles: https://hub.docker.com/r/leandelivery/docker-systemd

Here some scenario examples how we use them:
https://github.com/lean-delivery/ansible-development-kit
https://github.com/lean-delivery/ansible-role-gitlab-runner/blob/master/molecule/default/molecule.yml

Could we use them as default molecule base images for testing? They already has all needed packages and improvements.

Will it work for us?

**Comment by ssbarnea** [comment]
systemd support with container is a YOLO kind of adventure and has nothing to do with molecule itself.
