### ISSUE TITLE
Variables used in playbook are being resolved before 'converge'

### ISSUE THREAD

**Issue by munjoy** [ansible-community/molecule#1827]
# Issue Type

- Bug report

# Molecule and Ansible details

- Ansible version: 2.7.8
- Molecule version: 2.19.0 

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

The desired behaviour would be exactly as when the playbook is run with `ansible-playbook`. Example,

```
TASK [example : Generate data file from template] ***************************************************************************************
changed: [localhost]
```

# Actual Behaviour

When `molecule test` is executed, this is the actual error:
```
TASK [example : Generate data file from template] ******************************
fatal: [instance]: FAILED! => {"changed": false, "checksum": "15eb25600a9417548c9388111c2df4911e59ffd8", "msg": "Destination directory /home/ubuntu/Projects/test/example/files does not exist"}
    
PLAY RECAP *********************************************************************
instance                   : ok=1    changed=0    unreachable=0    failed=1   
```

Sample playbook and corresponding role have been attached to this issue. There is no hard-coded path in the provided. It would appear that the variable `some_file_path` is being resolved outside of the container and when the playbook is run in the container, it cannot find it.

So, I am still wondering if I am missing some configuration setting, a setup (prepare.yml ?) or, is this a bug?

[example.zip](https://github.com/ansible/molecule/files/2960629/example.zip)

**Comment by decentral1se** [comment]
Thanks for report @munjoy! We have lots to review and it would be very appreciated if you could turn your `example.zip` into a repository here on Github that we can more easily review in passing and if needed, `git clone` and run etc.

**Comment by munjoy** [comment]
@decentral1se: I have added a repo with the sample code in it https://github.com/munjoy/molecule_issue_101

**Comment by decentral1se** [comment]
Hey @munjoy, I am getting `"msg": "Error pulling image molecule_local/ubuntu:18.04 - 404 Client Error: Not Found (\"repository molecule_local/ubuntu not found: does not exist or no pull access\")"` when trying to test this with Molecule v2.19. I am not sure what you are aiming to achieve with https://github.com/munjoy/molecule_issue_101/blob/master/example/molecule/default/molecule.yml#L10?

**Comment by munjoy** [comment]
Hi @decentral1se. I am sorry the image that I have put there was already built on my machine. I have now updated the repo so that It will pull from some registry and then build. Sorry about that. Regarding the question about "what I am trying to achieve", the idea is simply to test my playbook in a Dokcer container. The playbook is just create a local file (i.e. on the Ansible controller) from a template which is provided in the role
