### ISSUE TITLE
[Discussion] Allow molecule to also specify/delegate the Ansible controller

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible-community/molecule#1837]
# Issue Type

- Feature request

# Desired Behavior

It might be useful to also be able to specify an external resource (a Docker container, a VM...) which is used as the Ansible controller (the machine that connects to the hosts that are managed, aka. "the place where `ansible-playbook` is launched from"). This would e.g. allow for testing a role that has some local_actions or help with module development.

**Comment by ljbaar** [comment]
Are you aware of the official docker container?

https://molecule.readthedocs.io/en/latest/examples.html#docker

**Comment by MarkusTeufelberger** [comment]
Yes. What if I don't want my tests to run in an Alpine Linux userland, but a CentOS one?

**Comment by ssbarnea** [comment]
If you want to run molecule from a specific container, other than the one we build, please build your own. We will continue to publish one based on its size and stability, without a special love for one OS or another.

**Comment by MarkusTeufelberger** [comment]
This is not the point of the issue - I want to be able to actually specify the Ansible controller (meaning: The machine that runs `ansible-playbook`) instead of implying "localhost".

If I build my own container with `molecule` in it (or even just want to use the official one) - how would I tell molecule to run Ansible in that container instead of localhost in the `molecule.yml` file?
