### ISSUE TITLE
Use provisioner name as Docker container name

### ISSUE THREAD

**Issue by andyshinn** [ansible-community/molecule#1847]
# Issue Type

- Feature request

# Molecule and Ansible details

```console
$ ansible --version && molecule --version
ansible 2.7.8
  config file = /Users/andy/Projects/myproj/infrastructure/ansible.cfg
  configured module search path = ['/Users/andy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Feb 12 2019, 08:15:36) [Clang 10.0.0 (clang-1000.11.45.5)]
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

The current Docker driver builds an image name of `"molecule_local/{{ item.item.image }}"` per https://github.com/ansible/molecule/blob/master/test/resources/playbooks/docker/create.yml#L40. When running multiple Molecule tests in parallel where the `Dockerfile.j2` differs but the base images do not, this can cause race conditions in the actual image used for the tests.

I am wondering if this should be based on the platform name instead of the platform image? I make sure the platform names are unique for all roles. But the base images I use are `ubuntu:16:04` and `ubuntu:18.04` which means that all the tests try to build the same image names.

My workaround right now is to just make sure the `Dockerfile` templates are exactly the same between all roles. If there is a better way to currently handle parallel testing of roles with the same images bases that renders this request moot then I'm all ears!

**Comment by decentral1se** [comment]
Thanks for the report @andyshinn!

This is definitely an issue and we've been tracking related ideas on https://github.com/ansible/molecule/issues/1573!
