### ISSUE TITLE
'overlay2' is not supported over overlayfs

### ISSUE THREAD

**Issue by jdrowne** [ansible-community/molecule#1877]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.7.9
molecule, version 2.20.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package manager

# molecule.yml
```
platforms:
  - name: instance
    image: centos/systemd
    privileged: true
    command: /sbin/init
```

# Ansible role in question

```
- name: Installing Docker
  yum:
    name: docker
    state: present
  become: yes

- name: Ensuring Docker is started on system boot
  service:
    enabled: true
    name: docker
    state: started
  become: yes
```

# Desired Behavior

Docker daemon is started and enabled.

# Actual Behaviour

Molecule error:
```
Unable to start service docker: Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n
```
Output from journalctl -xe inside the Docker container created by Molecule:
```
Mar 25 21:25:42 instance dockerd-current[729]: time="2019-03-25T21:25:42.763988551Z" level=error msg="'overlay2' is not supported over overlayfs"
Mar 25 21:25:42 instance dockerd-current[729]: Error starting daemon: error initializing graphdriver: backing file system is unsupported for this graph driver
Mar 25 21:25:42 instance systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Mar 25 21:25:42 instance systemd[1]: Failed to start Docker Application Container Engine.
```

**Comment by jdrowne** [comment]
Workaround to get the service to start. Execute the following inside the container created by Molecule:
```
sed -i -e 's/overlay2/vfs/g' /etc/sysconfig/docker-storage
sudo yum install -y iptables
systemctl start docker
systemctl enable docker
systemctl status docker
```

**Comment by decentral1se** [comment]
Have you seen https://github.com/ansible/molecule/pull/1876 @jdrowne?

Is it also solved with some further tweaking of the capabilities/privileges!?

This looks like a plain 'ol Docker issue and not a Molecule one ... we could document something for it.

**Comment by jdrowne** [comment]
I think this might be related to DIND because Molecule is creating a CentOS container during 'create' and then, because of the tasks specified in the playbook, attempting to run a Docker daemon inside that container during 'converge.'

**Comment by decentral1se** [comment]
Yes, makes sense. Not sure what to do about this ... is there a more "stable" solution than your work around for this that you discovered? We could add a https://molecule.readthedocs.io/en/latest/faq.html entry to avoid further issues being raised about DinD usage ... otherwise, should we close this?

**Comment by jdrowne** [comment]
I'd say to leave it open for a while to allow others to chime in.

As for the solution, I tried changing the storage driver in ``/etc/sysconfig/docker-storage-setup`` _before_ starting the daemon and got a different set of errors. So maybe someone more knowledgeable of DIND can provide a better answer.

**Comment by ssbarnea** [comment]
This seems to have nothing to do with molecule itself.
