### ISSUE TITLE
[wip] packages/molecule/provisioner/ansible/plugins/filters/molecule_core.py) as it seems to be invalid: No module named 'molecule'

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#1888]
It seems that I managed to find a bug relarted to usage of molecule from inside a tox virtualenv created with use-sitepackages. Likely to be unrelated to tox.

On Linux there is a real need to create virtualenvs using site-packages because this assures that `selinux` python bindings are available (needed by ansible modules used by molecule).

How to reproduce:
* install molecule on your default python interpreter (does not matter if at user or system level), but it matters not to be in a virtualenv.
* create a virtualenv using system-packages
* activate system packages
* run `molecule test --all`, it will likely fail with something like:

```
...
    ansible-playbook 2.7.8
      config file = /var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/molecule/tripleo-ci/tripleo-repos/ansible.cfg
      configured module search path = ['/Users/ssbarnea/rdo/tripleo-ci/.tox/molecule/lib/python3.6/site-packages/molecule/provisioner/ansible/plugins/libraries', '/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/molecule/tripleo-ci/tripleo-repos/library', '/Users/ssbarnea/rdo/tripleo-ci/library']
      ansible python module location = /Users/ssbarnea/.pyenv/versions/3.6.7/lib/python3.6/site-packages/ansible
      executable location = /Users/ssbarnea/.pyenv/versions/3.6.7/bin/ansible-playbook
      python version = 3.6.7 (default, Nov 12 2018, 16:11:56) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
    Using /var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/molecule/tripleo-ci/tripleo-repos/ansible.cfg as config file
    setting up inventory plugins
    /var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/molecule/tripleo-ci/tripleo-repos/inventory/ansible_inventory.yml did not meet host_list requirements, check plugin documentation if this is unexpected
    /var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/molecule/tripleo-ci/tripleo-repos/inventory/ansible_inventory.yml did not meet script requirements, check plugin documentation if this is unexpected
    Parsed /var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/molecule/tripleo-ci/tripleo-repos/inventory/ansible_inventory.yml inventory source with yaml plugin
    Loading callback plugin yaml of type stdout, v2.0 from /Users/ssbarnea/.pyenv/versions/3.6.7/lib/python3.6/site-packages/ansible/plugins/callback/yaml.py

    PLAYBOOK: destroy.yml **********************************************************
    1 plays in /Users/ssbarnea/rdo/tripleo-ci/.tox/molecule/lib/python3.6/site-packages/molecule/provisioner/ansible/playbooks/docker/destroy.yml
 [WARNING]: Skipping plugin (/Users/ssbarnea/rdo/tripleo-
ci/.tox/molecule/lib/python3.6/site-
packages/molecule/provisioner/ansible/plugins/filters/molecule_core.py) as it
seems to be invalid: No module named 'molecule'
```

I am planning to dig bit more to narrow down what happens but I think that we need to sort this out because it is high likely that users would want to call molecule from inside tox. And on development systems I do also expect users to install molecule outside virtualenv, mostly for convenience of calling it directly.

As a temporary workaround I added this line inside tox.ini file: `pip install --force molecule` which seems to have repaired the issue at the cost of doing a lot of uninstalling and reinstalling.

**Comment by ssbarnea** [comment]
I was able to findout when this happens but not how to avoid it yet. Mainly it happens when the virtualenv is created with   --system-site-packages and ansible and molecule are alread installed on the system level.

It seems to be related to how ansible is modifying the python PATH, somehow the python code run by ansible is loosing the system path from the include list and python fails to find either molecule or ansible modules.

**Comment by webknjaz** [comment]
yeah, that's why system-site-packages is discouraged.

**Comment by ssbarnea** [comment]
@webknjaz system-site-packages is a reality we cannot escape because selinux, which is present on most linux systems and without which most of ansible modules cannot be used. Selinux python bindings are provided by the system packages and if you create a virtualenv, it will miss them. You cannot install selinux python bindings using pip (forget about https://pypi.org/project/selinux/ which is an empty stub that I created to see how many users are fooled...).

It seems thart we cannot build a wheel with real selinux because it is highly dependend on the os-selinux libraries. It is a really s**** situation for which I do not know to resolve. At some point I was wondering if I would make the pure-python selinux module just lookup for the real selinux module and use it instead (escaping the virtualenv, which is perfectly possible today). I am not even sure it could work as I didn't had time to work on it.

PS. You may be surprised how many people do install it https://pypistats.org/packages/selinux :p

**Comment by webknjaz** [comment]
Not sure whether it's relevant, but I've just faced this:
```python-traceback
ansible27-unit run-test: commands[0] | pytest test/unit/ --cov=~/src/github/ansible/molecule/molecule/ --no-cov-on-fail
WARNING: test command found but not installed in testenv
  cmd: ~/.pyenv/versions/3.7.1/bin/pytest
  env: ~/src/github/ansible/molecule/.tox/ansible27-unit
Maybe you forgot to specify a dependency? See also the whitelist_externals envconfig setting.

DEPRECATION WARNING: this will be an error in tox 4 and above!
Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/_pytest/config.py", line 339, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('~/src/github/ansible/molecule/test/unit')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/_pytest/config.py", line 370, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('~/src/github/ansible/molecule/test/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/_pytest/config.py", line 376, in _importconftest
    mod = conftestpath.pyimport()
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 215, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "~/src/github/ansible/molecule/test/conftest.py", line 29, in <module>
    from molecule import config
  File "~/src/github/ansible/molecule/molecule/config.py", line 23, in <module>
    import anyconfig
ModuleNotFoundError: No module named 'anyconfig'
ERROR: could not load ~/src/github/ansible/molecule/test/conftest.py

ERROR: InvocationError for command ~/.pyenv/versions/3.7.1/bin/pytest test/unit/ --cov=~/src/github/ansible/molecule/molecule/ --no-cov-on-fail (exited with code 4)
___________________________________________________________________________________________ summary ___________________________________________________________________________________________
ERROR:   ansible27-unit: commands failed
```

It looks like `pytest` is loaded from the global site-packages while `anyconfig` is installed under tox's virtualenv and thus lookup fails... I think it's because of system-site-packages.

**Comment by webknjaz** [comment]
Another instance of this with system site-packages disabled: https://github.com/ansible/molecule/issues/1851.

It looks like molecule somehow messes with env vars when spawning subprocesses.

I blame `sh` library: https://github.com/ansible/molecule/issues/2012#issuecomment-487068300

**Comment by NitradoJustus** [comment]
What's the progress on this? Just hit this bug when trying out molecule, it blocks me from further introductory tests.
