### ISSUE TITLE
[FR] List available scenarios with a short description

### ISSUE THREAD

**Issue by rockandska** [ansible-community/molecule#1900]
# Issue Type

- Feature request

# Desired Behavior

If i didn't missed it, there is no possibilities to list scenarios available, and/or a short description of them.
This addition will be handy for people who want to provide an easy way to users to target a specific scenario without digging in files since even the directory name inside `molecule/` is not the final scenario name.

Regards,

**Comment by decentral1se** [comment]
This will be a good improvement!

**Comment by zeitounator** [comment]
This can probably be implement as an option to `molecule list`

**Comment by ssbarnea** [comment]
I am closing this before it gets one year old with the note that a PR that adds this would be welcomed.
