### ISSUE TITLE
Documentation: Fedora seccomp Link is broken

### ISSUE THREAD

**Issue by madonius** [ansible-community/molecule#2032]
# Issue Type

- Bug report

# Molecule and Ansible details

```bash
> $ ansible --version && molecule --version
ansible 2.7.10
  config file = /home/madonius/.ansible.cfg
  configured module search path = ['/home/madonius/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3rc1 (default, Mar 13 2019, 11:01:15) [GCC 8.3.0]
molecule, version 2.20.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

In the examples given in the documentation the link to the Fedora seccomp file is not working
https://github.com/ansible/molecule/blame/master/docs/examples.rst#L165

# Actual Behaviour

Provide a sample seccomp that is known to work

**Comment by ssbarnea** [comment]
Unable to reproduce.
