### ISSUE TITLE
molecule lint doesn't respect all ignore entries in .yamllint config

### ISSUE THREAD

**Issue by philipsd6** [ansible-community/molecule#2038]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.6.post0 (stable-2.7 1d3f29d4be) last updated 2019/01/31 09:40:14 (GMT -400)
  config file = None
  configured module search path = [u'/home/philipd/ansible/library']
  ansible python module location = /home/philipd/ansible/lib/ansible
  executable location = /home/philipd/ansible/bin/ansible
  python version = 2.7.15+ (default, Oct  2 2018, 22:12:08) [GCC 8.2.0]
molecule, version 2.20.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- source

Detail any linters or test runners used:

yamllint 1.15.0

# Desired Behavior

Running `yamllint .` and `molecule lint` should be identical, based on the same `.yamllint` config.

# Actual Behaviour

Using this `.yamllint` config file, 
```yaml
extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length: disable
  truthy: disable
  document-start:
    ignore: |
      inventory/
      examples/*inventory*
```

Running `yamllint .` produces no errors or warnings -- it correctly ignores `inventory/` and `examples/*inventory*`.

However, running `molecule lint` produces document-start warnings for the example inventory files:
```
--> Validating schema /home/philipsd6/devel/project1/molecule/default/molecule.yml.
Validation completed successfully.
--> Validating schema /home/philipsd6/devel/project1/molecule/centos/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    └── lint
    
--> Scenario: 'default'
--> Action: 'lint'
--> Executing Yamllint on files found in /home/philipsd6/devel/project1/...
    /home/philipsd6/devel/project1/examples/tech1_inventory.dummy.yml
      2:1       warning  missing document start "---"  (document-start)
    
    /home/philipsd6/devel/project1/examples/tech2_inventory.dummy.yml
      2:1       warning  missing document start "---"  (document-start)
    
    /home/philipsd6/devel/project1/examples/inventory.dummy.yml
      2:1       warning  missing document start "---"  (document-start)
```
This shows that it correctly ignores `inventory/` but does not correctly ignore `examples/*inventory*`. If I update that rule to ignore `examples/` it ignores the whole directory, and therefore doesn't lint the non-inventory files in that directory.

`molecule --debug lint` shows that the lint stage is passing a list of fully qualified yaml files to the `yamllint` command:

```
/home/philipsd6/.local/bin/yamllint -s /home/philipsd6/devel/project1/examples/tech1_inventory.dummy.yml ...
```

Nothing I put in the `.yamllint` ignore can avoid warnings for files under `example/` whether a fully qualified or relative path, or wildcard, except by ignoring just the `example/` directory itself.

**Comment by decentral1se** [comment]
Hey @philipsd6, thanks for the report. Looking at https://molecule.readthedocs.io/en/stable/configuration.html#molecule.lint.yamllint.Yamllint, I see that we can configure this using `options:` section in the `molecule.yml` of the `lint` stanza. I am not quite clear on the relationship between this configuration and the `.yamllint` file. Perhaps Molecule is not honouring it ... there should be some investigation for this.

**Comment by ssbarnea** [comment]
#2293 makes this bug irrelevant.

**Comment by till** [comment]
Thanks for the hint with the configuration @decentral1se. 👍🏼 

The complete fix is as follows:

Create a file `.yamllint`, e.g. to ignore certain files that have "terraform" in the path:

```yaml
ignore: |
  *terraform*
```

Then in `molecule.yml`:

```yaml
lint:
  name: yamllint
  options:
    config-file: /absolute/path/to/.yamllint
```
