### ISSUE TITLE
Adopt versioning based on minimal version of ansible needed

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2075]
I propose to start versioning molecule based on the minimal version of ansible it supports.

This means that versions that require `ansible>=2.5` should look like `2.5.x[.y]`.

The reasoning behind this is to send a clear message to the users and avoid suprising them when we will drop compatibility with older versions.

**Comment by MarkusTeufelberger** [comment]
What should molecule's version number for compatibility with `ansible>=2.8.0; <2.9` be for example?

**Comment by ssbarnea** [comment]
Mainly I was considering mentioning only the minimal version of ansible supported, not the maximal one as we would aim to make molecule compatible with all released versions of ansible. 

I also suppose that we will keep a constant number of backwards compatible versions, which means as soon we addsupport for one new ansible version, we drop the support for the oldest one.

Still one issue that we have is that molecule version is already greater than ansible, so we cannot really go back.

I am curious what other think about this.

**Comment by seandst** [comment]
I don't think that the version number is a good way to send a clear message to users. It's a reasonable way to send vague messages by way of semver (It's 3.0! We broke...*something* that you might care about but we've hopefully warned you about!).

If the motivation is to send clear messages to users, I think there may be better ways to do it, including literally sending clear messages to users. One option is sending messages to users when molecule is run, like emitting a deprecation warning (or similar) if the current used version of ansible is the next one to go unsupported.

The simplest thing to do might be to put a link to the [ansible support table](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#release-status) at the top of the README, along with a note about how it affects molecule and users of molecule as a result.

**Comment by ssbarnea** [comment]
Closing as wontfix as we do not directly depend on ansible.
