### ISSUE TITLE
Verifiy with alternativ files not work if 'test_default.py' not work

### ISSUE THREAD

**Issue by Smuu** [ansible-community/molecule#2081]
# Issue Type

- Bug report

# Molecule and Ansible details

ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/s.enderwitz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/s.enderwitz/.local/lib/python2.7/site-packages/ansible
  executable location = /home/s.enderwitz/.local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
molecule, version 2.20.1

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

I added some other testinfra files in 'default/tests/'. I added them to the additional_files_or_dirs argument in the 'molecule.yml' to use them.
The 'test_default.py' is not needed anymore and I can delete it.

# Actual Behaviour

With no 'test_default.py' file in 'default/tests/' the output is: 'Skipping, no tests found.'.
If there is a empty 'test_default.py' file in folder the tests work properly.

**Comment by EugenFo** [comment]
I can confirm this behaviour. I'm working not with testinfra, but InSpec instead. Same bevaviour. If there are no test_*.rb files, then molecule assumes that there are no tests.
I also looked that up in the molecule code and molecule just checks at the verify step if a file named test_*.* exists.

**Comment by alexppg** [comment]
Can confirm this still happens in 2.22 version.
