### ISSUE TITLE
Under Win10, docker ... molecule destroy fail

### ISSUE THREAD

**Issue by jehon** [ansible-community/molecule#2084]
# Issue Type

- Bug report

# Molecule and Ansible details

image from docker on 2019-06-04

Molecule installation method (one of):
- Docker

Ansible installation method (one of):
- Docker

Detail any linters or test runners used:

# Desired Behavior

Under Windows 10, I use the command:
`docker run --privileged -v %cd%:/tmp -w /tmp -it --rm quay.io/ansible/molecule molecule destroy`
(I am inside a ansible role folder)

It fails with the message: 

>     TASK [Wait for instance(s) deletion to complete] *******************************
>     failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
>     fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
> 

# Actual Behaviour

I would expect "destroy" to work.

log: [log.log](https://github.com/ansible/molecule/files/3252316/log.log)

Thanks for your support !

**Comment by decentral1se** [comment]
Can you do `export MOLECULE_NO_LOG=False` and `MOLECULE_DEBUG=True` and give us the output? This will show *all* the logging.
