### ISSUE TITLE
Allow prepared platforms that can be selectively excluded from destroy cycle.

### ISSUE THREAD

**Issue by skyscooby** [ansible-community/molecule#2087]
# Issue Type

- Feature request

# Desired Behavior

It's quite possible there is an existing way to do this well but it would be nice to have the ability to control the create/destroy stage to have an isolated instance that can be reused while testing the converge stage. Today it looks like create and destroy do not support specifying individual hostnames to act on.

Here is the scenario.. I am developing/testing an agent role that manages an agent for a server based platform. As part of the agent role testing I have included one platform container that represents the server and the server role is deployed to this platform as part of the prepare.yml file via galaxy dependancy.. also in the platforms list is a set of 5-10 more containers representing the different operating systems the agent supports and they leverage the server endpoints to validate functional tests. It takes 10-15 minutes to bring up this server based platform but only a minute or less to run the agent role... I'd like the ability to exclude the server from the destroy / create operations in iterative development so I can focus on the testing of the agent role without suffering the delays of having the server torn down and re-installed each cycle.

How this fits with the project vision is for the team to decide.

**Comment by themr0c** [comment]
Hi, lately, the `extra_hosts` key was added to add hosts in the inventory that are not affected by create/destroy. Your usecase seems to be a good example for the usage of this feature. Would it suit you?

https://molecule.readthedocs.io/en/master/configuration.html#id19

**Comment by skyscooby** [comment]
I suppose so.. I could create an integration scenario in each individual project (using the same network name in both) and add extra_host referencing the other project as the integration point... Then as separate "pre-steps" clone out and run the converge on the server side project in advance of the full test on the client project and finally destroy the server project as a post-step.

**Comment by ssbarnea** [comment]
This sounds like the use case for a custom `destroy.yaml` playbook, something you can already do.
