### ISSUE TITLE
Consider dropping cookiecutter due lack of maintenance

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2102]
It seems that dependency on cookiecutter became a liability for molecule and unless its [maintenance issue](https://github.com/audreyr/cookiecutter/issues/1174) is sorted I think we are better off migrating off it.

I mention that that is the second time when cookiecutter remain unmaintained, first time being in 2014.

I am not sure which options are pratical but having unmaintained depdendencies is a high risk that we may want to avoid.

**Comment by themr0c** [comment]
What could be an alternative?

**Comment by ssbarnea** [comment]
I have no idea but hopefully we can revive its maintenance, I offered to help on that. See https://github.com/audreyr/cookiecutter/issues/1174 -- we only need 2-3 people to look over PRs and review them to keep it alive.

**Comment by decentral1se** [comment]
Given the proceedings on https://github.com/audreyr/cookiecutter/issues/1174, I think we can say that cookiecutter will not be going unmaintained for now. I'm glad that the project won't go dead because it is so useful and widely used.

**Comment by ssbarnea** [comment]
I am reopening this ticked and keep it open until cookiecutter maintenance issue is sorted, and by sorted I mean the project starts to make new releases. I already tried to help them along others but the outcome was marginal: core reviews are still very slow and worse no release was made.

**Comment by decentral1se** [comment]
Dare I suggest https://palletsprojects.com/p/jinja/ :scream:

**Comment by ssbarnea** [comment]
Closing this as cookiecutter is no longer such a big issue and because I do not expect anyone to work on this. Still, if someone wants to replace it with a pure ansible implementation, I will be happy to review the PR.
