### ISSUE TITLE
Document environment variables

### ISSUE THREAD

**Issue by nkakouros** [ansible-community/molecule#2123]
# Issue Type

- Feature request

There seem to be environment variables that could be used inside playbooks, etc:

https://github.com/ansible/molecule/blob/f31502746f33abd7720264430e4f665be72d3df1/molecule/config.py#L198-L214

But these are not documented anywhere. At least the search on https://molecule.readthedocs.io/ does not return anything. Is there a place to learn about them?

**Comment by decentral1se** [comment]
Happily accepting documention PRs if people have time!

**Comment by ssbarnea** [comment]
Closing with note that PRs are still welcomed.
