### ISSUE TITLE
Customize verifier output

### ISSUE THREAD

**Issue by mNantern** [ansible-community/molecule#2129]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version && molecule --version
```

```
ansible 2.6.3
  config file = None
  configured module search path = [u'/Users/matt/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Mar  4 2019, 09:02:22) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
molecule, version 2.19.0
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):

- OS package

# Desired Behavior

We are using inspec as our verifier and the output is bad, almost unusable: the tests results are displayed through the debug module and so everything is green even when an error arises.

![Capture d’écran 2019-06-25 à 09 41 15](https://user-images.githubusercontent.com/1544226/60079022-6b3d1b00-972d-11e9-87d0-5ce828d395af.png)

Is it possible to have a better output ?

**Comment by ssbarnea** [comment]
Yes, you can configure same options as you have with ansible in molecule.ym file. Read the docs about it.a
