### ISSUE TITLE
[FR] Merge ansible.cfg with molecule_yml.provisioner.config_options

### ISSUE THREAD

**Issue by rockandska** [ansible-community/molecule#2130]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.7.9
molecule, version 2.20.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

I use molecule to test APB and it works well.
For a specific APB, i change some options in the ansible.cfg at the root of my APB.
At that time, i need to add the same settings present in my ansible.cfg in each molecule.yml because molecule don't take the ansible.cfg at the root of the project and merge it with its own settings.
Despite it works well it could lead to unexpected results if someone change something in ansible.cfg without porting it to each scenario molecule.yml

Having molecule merge ansible.cfg and its own settings with a higher priority for the settings present in molecule.yml will fix this.

Regards,

**Comment by ssbarnea** [comment]
Not doing because it would make execution non predictable. The idea is to run tests with same set of settings on any machine.

**Comment by rockandska** [comment]
@ssbarnea where does it not make reproducible on any machine ?
Since the ansible.cfg is part of the APB it will be always the same.
Having not the ansible.cfg (next to the playbook) merged in molecule is what cause here a non desirable behaviour since you can forgot some settings in some scenario and the result will be not the same if you run the APB directly or with molecule.

I'm agreed to do not take the user ansible.cfg into account but that was not the subject for this issue.

**Comment by ssbarnea** [comment]
Excuse my ignorance but is the first time I hear about ABP and apparently the https://galaxy.ansible.com/docs/finding/content_types.html#ansible-playbook-bundles page sends to a github project hosted under another org with Another Bigger Problem: its homepage points to an expired godaddy domain. I have being member of #ansible-galaxy irc channel for more than an year and I did not see anything about ABP.

Maybe someone from galaxy team can clarify its status. @geerlingguy ?

**Comment by rockandska** [comment]
I should not have talk about APB at first to not add complexity in the conversation.

To be more clear, my situation could be solved if  :

- an ansible.cfg at the root of the scenario is take into account ( so i will symlink the ansible.cfg at the root of my project in each scenario )
- an ansible.cfg path could be provided in the scenario

@ssbarnea : ping me on IRC if needed
