### ISSUE TITLE
Connect molecule to dynamic inventory (openshift inventory plugin)

### ISSUE THREAD

**Issue by catalinad90** [ansible-community/molecule#2166]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.0
python 2.7.5
molecule 2.19.0

```
Molecule installation method (one of):

- source

Ansible installation method (one of):
- source
source /data/.virtualenvs/ansible-2-7-0/bin/activate

Detail any linters or test runners used:
testinfra

# Desired Behavior

Is it possible to integrate an inventory plugin (ex: k8s, openshift) into molecule? At the moment the inventory plugin runs fine in the ansible role: it connects to openshift to a certain project and runs a command into a container.

# Actual Behaviour

I would like to integrate the dynamic inventory into molecule so we can run our functional tests with molecule verify (testinfra).
Already tried using in the molecule.yml file: 
-> env variables:
MOLECULE_INVENTORY_FILE: /home/user/inventorytest/delegate/inventory/openshift.yml
-> via hosts:
inventory:
    links:
      hosts: ../.../inventory
This one fails with this error: OSError: [Errno 17] File exists (From what I read it's because of the molecule version)

Can you provide some hints? I am bit new with testinfra and molecule.

Thanks! :)

**Comment by ssbarnea** [comment]
Closing as no PRs were received. Still feel free to make a PR and reference this ticket, even if it is closed.
