### ISSUE TITLE
quay.io master tag points to latest stable instead of pre-release

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2225]
At this moment there is no mobile tag that can used to point latest development version of molecule because both `master` and `latest` point to last release.

Pre-releases were published but the user using them are forced to manually update versions for each of them.

https://quay.io/repository/ansible/molecule?tab=tags

**Comment by daurrutia** [comment]
Master points to an older tag?

bash-4.4# ansible --version
ansible 2.7.9
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Mar  7 2019, 22:40:59) [GCC 8.2.0]
bash-4.4# molecule --version
molecule, version 2.20.0.0a3.dev12
