### ISSUE TITLE
Unable to disable colored output

### ISSUE THREAD

**Issue by adam-dej** [ansible-community/molecule#2256]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.8.3
molecule, version 2.22
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- source

Detail any linters or test runners used:

- none

# Desired Behavior

Colors should be stripped from output if `PY_COLORS=0` is defined or if the output is redirected to a file.

```shell
$ PY_COLORS=0 molecule list > some_file
$ xxd some_file                        
00000000: 2d2d 3e20 5661 6c69 6461 7469 6e67 2073  --> Validating s
```

# Actual Behaviour

Control characters defining colors are not stripped.

```shell
$ PY_COLORS=0 molecule list > some_file
$ xxd some_file 
00000000: 2d2d 3e20 1b5b 3336 6d56 616c 6964 6174  --> .[36mValidat
```
If I rollback changes introduced in fecf50b7e4f2bc19d3981b645b3c9c267efc95a9, color stripping works as expected.

**Comment by ssbarnea** [comment]
Have you tried using `TERM=dumb`?

**Comment by adam-dej** [comment]
Unfortunately, the result is the same:

```shell
$ TERM=dumb molecule list | xxd
00000000: 2d2d 3e20 1b5b 3336 6d56 616c 6964 6174  --> .[36mValidat
```

**Comment by ssbarnea** [comment]
I am unable to reproduce it with code from master.

**Comment by kevingentile** [comment]
```
molecule 3.0.2
   ansible==2.9.6 python==3.8
```

This is still a present issue. PY_COLOR=0 appears to remove color from the help text but fails to remove control characters from general execution.

* Help text
```
bash-5.0# PY_COLORS=1 molecule | xxd
00000000: 1b5b 306d 5573 6167 653a 206d 6f6c 6563  .[0mUsage: molec
```

```
bash-5.0# PY_COLORS=0 molecule | xxd
00000000: 5573 6167 653a 206d 6f6c 6563 756c 6520  Usage: molecule
```

* molecule test

```
bash-5.0# PY_COLORS=0 molecule test | xxd
00000000: 2d2d 3e20 1b5b 3336 6d54 6573 7420 6d61  --> .[36mTest ma
```



`logger.should_do_markup` parses the PY_COLORS environment variable which is then [passed to strip in `colorama.init`](https://github.com/ansible-community/molecule/blob/master/molecule/shell.py#L39). However, click is [passed a `HelpColorGroup` for all command groups](https://github.com/ansible-community/molecule/blob/master/molecule/command/base.py#L221) which may be the source of the remaining control characters.
