### ISSUE TITLE
proposal: a newly created role should always pass linting

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2290]
Currently if you create a role with molecule it will fail to pass linting because some default fields do still have their original settings.
```
molecule init role -d vagrant -r test-vagrant
```
In order to improve the UX we need to find a way to avoid these errors. Also this would allow us to perform a full integration testing on molecule CI, where we validate that user can successfully run all commands on newly created roles.

```
--> Executing Ansible Lint on /root/rdo/molecule/test-vagrant/molecule/default/playbook.yml...
    [701] Role info should contain platforms
    /root/rdo/molecule/test-vagrant/meta/main.yml:1
    {'meta/main.yml': {'skipped_rules': [], '__file__': u'/root/rdo/molecule/test-vagrant/meta/main.yml', u'dependencies': [], u'galaxy_info': {u'description': u'your description', u'license': u'license (GPLv2, CC-BY, etc)', u'author': u'your name', u'company': u'your company (optional)', u'galaxy_tags': [], '__line__': 2, '__file__': u'/root/rdo/molecule/test-vagrant/meta/main.yml', u'min_ansible_version': 1.2}, '__line__': 1}}

    [703] Should change default metadata: author
    /root/rdo/molecule/test-vagrant/meta/main.yml:1
    {'meta/main.yml': {'skipped_rules': [], '__file__': u'/root/rdo/molecule/test-vagrant/meta/main.yml', u'dependencies': [], u'galaxy_info': {u'description': u'your description', u'license': u'license (GPLv2, CC-BY, etc)', u'author': u'your name', u'company': u'your company (optional)', u'galaxy_tags': [], '__line__': 2, '__file__': u'/root/rdo/molecule/test-vagrant/meta/main.yml', u'min_ansible_version': 1.2}, '__line__': 1}}

    [703] Should change default metadata: description
    /root/rdo/molecule/test-vagrant/meta/main.yml:1
    {'meta/main.yml': {'skipped_rules': [], '__file__': u'/root/rdo/molecule/test-vagrant/meta/main.yml', u'dependencies': [], u'galaxy_info': {u'description': u'your description', u'license': u'license (GPLv2, CC-BY, etc)', u'author': u'your name', u'company': u'your company (optional)', u'galaxy_tags': [], '__line__': 2, '__file__': u'/root/rdo/molecule/test-vagrant/meta/main.yml', u'min_ansible_version': 1.2}, '__line__': 1}}

    [703] Should change default metadata: company
    /root/rdo/molecule/test-vagrant/meta/main.yml:1
    {'meta/main.yml': {'skipped_rules': [], '__file__': u'/root/rdo/molecule/test-vagrant/meta/main.yml', u'dependencies': [], u'galaxy_info': {u'description': u'your description', u'license': u'license (GPLv2, CC-BY, etc)', u'author': u'your name', u'company': u'your company (optional)', u'galaxy_tags': [], '__line__': 2, '__file__': u'/root/rdo/molecule/test-vagrant/meta/main.yml', u'min_ansible_version': 1.2}, '__line__': 1}}

    [703] Should change default metadata: license
    /root/rdo/molecule/test-vagrant/meta/main.yml:1
    {'meta/main.yml': {'skipped_rules': [], '__file__': u'/root/rdo/molecule/test-vagrant/meta/main.yml', u'dependencies': [], u'galaxy_info': {u'description': u'your description', u'license': u'license (GPLv2, CC-BY, etc)', u'author': u'your name', u'company': u'your company (optional)', u'galaxy_tags': [], '__line__': 2, '__file__': u'/root/rdo/molecule/test-vagrant/meta/main.yml', u'min_ansible_version': 1.2}, '__line__': 1}}
```

Ideas:
* Get default user from `git config user.name`
* Get default email from `git config user.email`
* Default to an MIT license.
* Default to no company
* Find a simple and popular platform to include by default

Open questions:
* Can we avoid adding a configuration file for molecule?
* How could user define new defaults for `license` and `company` (we want to avoid adding new cli arguments)
* What to do if git is not configured yet with user.name and user.email?
* Would it be acceptable to piggy-back git configuration for fields that have not meaning for git?:
```
git config user.company "Red Hat"
git config user.license "MIT"
```
This could be handy for us as we could avoid having to create a new config file.

**Comment by decentral1se** [comment]
> a newly created role should always pass linting

I disagree because that's the way ansible galaxy creates roles and the way ansible-lints them by default. With errors on the default values. I am for the defaults so I say we don't try to do anything better here.

> Also this would allow us to perform a full integration testing on molecule CI, where we validate that user can successfully run all commands on newly created roles.

We already can because we arranged that a dummy configuration be put in place to ignore those initial warnings when making the linting run on newly created roles.

**Comment by MarkusTeufelberger** [comment]
Just writing "MIT" in a metadata file is not enough to license something under the MIT license. Also I definitely do not want to have stuff automatically put under a permissive license.

**Comment by ssbarnea** [comment]
Another idea would be to make molecule fail to run if it does not find required information in its config (default license, company, author, email), obviously with a clear error message that tells user how to configure these.

I guess that not having defaults on pure-clean installs should address last concerns, like accidental licensing misuse. True that even for author/email we may be able to see a LOT of code on github using default value that do not make any sense. Still, I prefer to avoid making molecule cli interactive. I kinda dislike prompts,... or popups ;)

The idea is that a successful run (error code 0) of templating should produce a result that is fully functional. This could easily be tested in CI to keep it functional.

@MarkusTeufelberger I am more curious what you think about using git configuration for storing molecule config. I am inclined to  prefer it than creating a molecule specific config file because git one is very flexible and well known (also user can configure it at various levels).

**Comment by MarkusTeufelberger** [comment]
I somewhat doubt that people are used to or comfortable with storing configuration for a test runner in git config vs. a dedicated file named after the tool.

Since you already proposed to remove linting, I'd rather see full role/collection templating being removed from molecule (and outsourced to `ansible-galaxy` or `mazer`) than assuming or asking for some global defaults.

**Comment by ssbarnea** [comment]
@MarkusTeufelberger I see no practical way to remove templating from molecule at this point as this is still quite important for many users and lots of templates content is specific to each molecule driver. 

I am bit disapointed that people do not like the idea of re-using git config but I respect that. Now I need a simple config file loader as the use of environment variables does not scale well, I already identified 4 properties for which we need defaults. I am open to suggestions.

**Comment by MarkusTeufelberger** [comment]
Drivers should ship templates for their molecule specific files, `molecule init role` could use galaxy to create the ansible specific things and molecule would only be concerned with the contents of the molecule folder.

**Comment by decentral1se** [comment]
> Drivers should ship templates for their molecule specific files, molecule init role could use galaxy to create the ansible specific things and molecule would only be concerned with the contents of the molecule folder.

+1

**Comment by ssbarnea** [comment]
There is now a PR for removal of cookiecutter role template from molecule and use galaxy init. See https://github.com/ansible/molecule/pull/2342

**Comment by ssbarnea** [comment]
Fixed long time ago.
