### ISSUE TITLE
proposal: consolidate test fixtures in a single place

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2305]
At this moment we have a big number of test fixtures spread across at least 5 files listed below:
```
molecule/test/unit/conftest.py
molecule/test/unit/model/v2/conftest.py
molecule/test/unit/command/conftest.py
molecule/test/conftest.py
molecule/test/functional/conftest.py
```

Some of them even have duplicate names, and importing them from plugins is far from easy and causes a lot of boilerplate code (not to mention mistakes when porting code from core to plugins).

If we can change the unittests to load fixtures only from one location, like `molecule/test/conftest.py` it should be much easier to consume them in plugins.

**Comment by decentral1se** [comment]
+1 

:bomb:

**Comment by ssbarnea** [comment]
Closing as most of these already happened. Also if anyone spots more, just raise a PR.
