### ISSUE TITLE
plugins: externalize podman driver

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2317]

**Comment by sshnaidm** [comment]
@ssbarnea what does it mean "externalize"?

**Comment by decentral1se** [comment]
Hi @sshnaidm, it means all the driver code will be maintained in another repository and molecule will load drivers as plugins. Molecule is moving towards a plugin architecture.

**Comment by ssbarnea** [comment]
Done in master and hosted at https://github.com/ansible-community/molecule-podman
