### ISSUE TITLE
Molecule shows misleading messages when linting is disabled

### ISSUE THREAD

**Issue by ansiblejunky** [ansible-community/molecule#2344]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.8.0
molecule, version 2.20.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

- ansible-lint
- yamllint
- flake8

# Desired Behavior

Molecule config file `molecule.yml` has lint section disabled using `enabled: false` and so running `molecule lint` should simply show the following output:
```
> molecule lint
--> Validating schema foo/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix

└── default
    └── lint

--> Scenario: 'default'
--> Action: 'lint'
Skipping, lint is disabled.
```

# Actual Behaviour

Molecule outputs misleading messages that show `Executing xxx on files found` which makes the user believe that linting was performed. These messages should not be printed when linting is disabled. The messages are coming from the fact that the `molecule.yml` defines linters for the `verifier` section and `provisioner` section. However, we only ran `molecule lint` so I assume these other sections should never be executed or considered. 

```
> molecule lint
--> Validating schema foo/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix

└── default
    └── lint

--> Scenario: 'default'
--> Action: 'lint'
Skipping, lint is disabled.
--> Executing Flake8 on files found in foo/molecule/default/tests/...
Lint completed successfully.
--> Executing Ansible Lint on foo/molecule/default/playbook.yml...
Lint completed successfully.
```

The following is the `molecule.yml`:
```
---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint
  enabled: False

platforms:
  - name: centos
    box: bento/centos-7.4
    groups:
      - linux

provisioner:
  name: ansible
  lint:
    name: ansible-lint

verifier:
  name: testinfra
  enabled: False
  lint:
    name: flake8
```

**Comment by ansiblejunky** [comment]
It appears the code that performs the lint against each area is:

https://github.com/ansible/molecule/blob/bd7f4767d6a57bf9c1153bcb5c31c5a005fefc40/molecule/command/lint.py#L73-L76

Not sure the `molecule lint` command should span across different phases (lint, verify, provision).

**Comment by hoanganh25991** [comment]
haksjdhfjdsf

**Comment by rollerd** [comment]
Is the expected behavior that setting the outermost lint (in molecule.yml) to `enabled: false` should prevent the provisioner and verifier linters from running?

I believe the output you're seeing isn't misleading - it's actually running those linters (try adding something to either the tests file or role files that would trigger a linter response - trailing whitespace works - and then set the outermost lint to `enabled: false`).

Setting the linters in each subsection to false:
```

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False

verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: False
```
will produce the desired output you mentioned.

I'm interested to hear what the expected behavior should be. I could see it being useful to have a general yamllint with modified rules run before something like ansible-lint or flake8.

**Comment by ansiblejunky** [comment]
I understand that the `molecule lint` command will perform all linting across any phase (linting, verification, provisioning), but when we also have molecule commands like `molecule verify` and `molecule prepare`, etc, i was only assuming the `molecule lint` command would only run the lint as described in the section of the molecule.yml that defines the main lint tool and that molecule would do linting in the verify mode only when I run `molecule verify`.

**Comment by rollerd** [comment]
I created a very simple WIP PR that adds the functionality you're describing (if I'm understanding correctly) @ansiblejunky - #2387

In the PR, running `molecule lint` now only runs the  root lint against the role.
`molecule verify` and `molecule converge` now run their respective linting independently.

If users have come to expect that all linting should be done up front in the main lint step, this could cause issues. Wouldn't it be preferable to check all linting up front anyway, rather than have a step fail at the end when, say, verifying?

**Comment by ssbarnea** [comment]
I am not sure I do want to have linters spread across multiple places. I am for having one `lint` command that does run all linters.

I am for simplification of linting config but not for spreading them to various places or running them at different times. @decentral1se what's your take on this?

@rollerd do you have an example that makes impossible to run all linters in the current lint stage?

**Comment by decentral1se** [comment]
I think this is a docs issue. Linting being all done up front is how it runs today and changing that would be a significant breaking change for users and their expectations (that doesn't mean we can't do it, it's all up for debate). It's been confusing for people to see multiple linting keys in the config but when you finally find out why (different linters for different files with different responsibilities) it makes sense. I'm all for making this more clear on existing behaviour (docs, more output messages, better examples, etc.) but I'd rather not change the existing behaviour. I like things to break fast when there are linting issues anywhere. That said, big up to @rollerd to churning out the change, we need more of that :)

**Comment by ansiblejunky** [comment]
@rollerd Thanks for putting that together. Sorry for the late response as well. 

So we define scenarios in the `molecule.yml` config file. We have scenarios defined like `verify`, `lint`, etc.  We also define these scenarios separately in the config file.  However, the molecule commands seem inconsistent.  With `molecule verify` we run the verify scenario, which includes the lint for only the verify scenario.  However with `molecule lint` we run all linters defined anywhere in the config file, which I find inconsistent. If I don't want to run the verify scenario (not listed in the `scenario:` section or not executed from the `molecule` command then I also don't want to run the linting for the verify scenario!  If "lint" is a scenario then it should only run the linting defined in the `lint:` section of the config file.

However, I do agree with the "fail-early-fail-fast" approach of being able to run all the linters in the beginning - a.k.a define a lint scenario as one of the first scenarios to run.  But how to do this intuitively without breaking some of the concepts mentioned above?  

One way perhaps is to require all the linters to be defined at the root level `lint:` in the config file.  Then in the various defined scenarios, we can reference those linters by `name`... however, they need to be defined in the `lint:` section before they can be used in other sections.

In this example, flake8 was pre-defined in the `lint` root level section and then later referenced (by name) in the `verifier` section.

```
lint:
   - 
   name: ansible-lint
   enabled: True
   - 
   name: flake8
   enabled: True

verifier:
  name: testinfra
  enabled: False
  lint:
    name: flake8
```

If we do it this way, then I would be cool with `molecule lint` running all of my defined linters. 

Hope this helps.

**Comment by ssbarnea** [comment]
Yes, I will support any change that is detaching the linter execution from verifier or provisioner as I want to have only one lint action (which could run more than one linter in the end).

Still having linters scattered around many places would only confuse and or alienate our users.

**Comment by ansiblejunky** [comment]
The linters are currently scattered across the entire molecule config. 
With the design I proposed, you at least define them in one place in the config and in other areas you can "use" the ones predefined in the `lint` section.

**Comment by decentral1se** [comment]
OK, there is a discussion rolling on centralising linting configs and command line interface over in #2293. Please leave your thoughts there to push the issue forward.

**Comment by ssbarnea** [comment]
v2 is EOL
