### ISSUE TITLE
Dockerfile.j2 support for centos/redhat 8

### ISSUE THREAD

**Issue by christiangda** [ansible-community/molecule#2348]
# Issue Type

- Feature request

# Molecule and Ansible details

- all version

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Recently I trying to support **centos/redhat 8** into my ansible roles and the base Dockerfile template doesn't support it.  

The problem is that **centos/fedora 8** has `yum` and `dnf` packages manager installed by default so your Dockerfile.j2 template fails to prepare the images.

I move forward fixing it with the following `if conditionals` 

**Dockerfile.j2**

```Dockerfile
# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates && apt-get clean; \
    elif [ $(command -v dnf) ] && [ $(rpm --query 'centos-release-8*' 'redhat-release-8*' | grep -v 'is not installed') ]; then dnf install -y python3 python3-devel python3-dnf python3-pip && dnf clean all && ln -s /usr/bin/python3 /usr/bin/python; \
    elif [ $(command -v dnf) ] && ![ $(rpm --query 'centos-release-8*' 'redhat-release-8*' | grep -v 'is not installed') ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python2-dnf bash && dnf clean all; \
    elif [ $(command -v yum) ] && ![ $(rpm --query 'centos-release-8*' 'redhat-release-8*' | grep -v 'is not installed') ]; then yum makecache fast && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python sudo bash python-xml && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python sudo bash ca-certificates && xbps-remove -O; fi
```

Will there be a better solution?

**Comment by hudecof** [comment]
+1

what about creating pull request for this issue. I have got the same problem.

My slution is based on `rpm -E %{rhel}`

```
RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates iproute2 && apt-get clean; \
    elif [ $(command -v dnf) ] && [ $(rpm -E %{rhel}) -eq 8 ]; then dnf makecache && dnf --assumeyes install python3 python3-devel python3-dnf python3-pip bash iproute && dnf clean all; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python*-dnf bash iproute && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y python sudo yum-plugin-ovl bash iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python sudo bash python-xml iproute2 && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python sudo bash ca-certificates iproute2 && xbps-remove -O; fi
```

**Comment by ssbarnea** [comment]
Clearly this needs to be fixes ASAP but I am not yet sure which is the optimal way to address it. This is why I also asked on https://stackoverflow.com/questions/58337303/how-to-install-default-python-in-a-portable-way-betwee-all-recent-redhat-distros

In addition to this I also discovered that we have multiple Dockerfiles and I am attempting to consolidate them in a single template, so we don't have to maintain all.

**Comment by ekultails** [comment]
The only thing I can think of is to grab the distro name and version from /etc/os-release. Then have some nested `if` statements to handle the Python package name for EL 7 vs EL 8 vs Fedora.

For example, my this is what Fedora 30 would report:

```
$ grep NAME= /etc/os-release | cut -d= -f2 | head -n 1
Fedora
$ grep VERSION_ID= /etc/os-release | cut -d= -f2
30
```

+1 to the consolidation of Dockerfiles, too.

**Comment by KAMI911** [comment]
> +1
> 
> what about creating pull request for this issue. I have got the same problem.
> 
> My slution is based on `rpm -E %{rhel}`

It seems it does not install sudo.

**Comment by KAMI911** [comment]
> > +1
> > what about creating pull request for this issue. I have got the same problem.
> > My slution is based on `rpm -E %{rhel}`
> 
> It seems it does not install sudo.

Using this fix the test is green for my project here: https://travis-ci.org/KAMI911/ansible-role-java-adopt-open-jdk11
(DEBUG Molecule output is enabled.)

**Comment by ssbarnea** [comment]
This was done a long time ago.
