### ISSUE TITLE
remove obsolete branches

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2383]
The list of below branches are ~3 years old and out of support but I cannot delete them as they are protected. 
```
v1
v2
stable/1.25
stable/1.24
stable/1.23
stable/1.22
stable/1.21
stable/1.20
```

@gundalow Please delete those branches, to avoid confusions or spamming the branch tree, nobody is going push stuff to them. Tags are enough.

**Comment by ssbarnea** [comment]
@retr0h @gundalow Any reason for not doing this cleanup? Are they of any practical use? AFAIK, the code from there is still in master history, so we should have no worries to remove them.

**Comment by gundalow** [comment]
OK with me
