### ISSUE TITLE
Proposal: ansible-lint as a project linter

### ISSUE THREAD

**Issue by nervo** [ansible-community/molecule#2393]
# Proposal: ansible-lint as a project linter

*Date*: 2019-10-23

- Status: New
- Proposal type: project linter

## Motivation

Just like molecule has become the defacto standard testing framework for ansible roles, ansible-lint has become the defacto standard ansible role linter.
Imho, it makes sense for the first one to be able to use the second one to lint role itself :)

### Problems

Yamllint is too yaml syntax centric, and misses all the domain rules ansible-lint offers (https://docs.ansible.com/ansible-lint/rules/default_rules.html)

## Solution proposal

The following commit (https://github.com/ansible/molecule/commit/dd951b8b2551c7830e1f376e7cdc5cc7dafdee12#diff-ed08bd49fed1ae05e3aa10d9931db457) split linters into 3 types (project, provisionner and verifier), but leave only yamllint as project linter. Maybe one could re-use old base code to re-introduce ansible-lint as project linter.

**Comment by ssbarnea** [comment]
If I am not wrong there is an already existing issue for implementing this. This will be implemented as a side-effect of switching the default verifier from testinfra to ansible, the former one using ansible-lint as default linter.

BTW, the bug title is misleading because ansible-lint can already be used, is just that is not the default one picked.

**Comment by nervo** [comment]
Ah ! I guess you are speaking about https://github.com/ansible/molecule/pull/2321
As far as i can see, this only concerns *verifier* linter, and not *project* one, no ?

And btw, reading code (https://github.com/ansible/molecule/tree/master/molecule/lint) ansible-lint does not seem to be a *project* linter option...

**Comment by ssbarnea** [comment]
Closing it because now molecule is linter independent. You can call a linter but is up to you which one to use.

I am considering adding a `molecule init lint` command which initializes linter config inside your repository, but this would be a new feature.
