### ISSUE TITLE
Not all extended shell-style features are supported

### ISSUE THREAD

**Issue by robertdebock** [ansible-community/molecule#2404]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.8.5
  config file = None
  configured module search path = ['/home/robertdb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
molecule, version 2.22
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

Detail any linters or test runners used:
- not applicable

# Desired Behavior

The variable should behave [as described](https://molecule.readthedocs.io/en/stable/configuration.html#variable-substitution)

# Actual Behaviour
I would like more shell-style variable features to be usable. For example:

Add a dash to `variable` if `variable` is set:

```
$ variable="i.love.molecule"
$ echo "${variable:+$variable-}"
i.love.molecule-
$ unset variable
$ echo "${variable:+$variable-}"
$
```

Currently I'm getting this error:
```
ERROR: parsing config file 'molecule/default/molecule.yml'.

Invalid placeholder in string: line 11, col 12
```

(Where line 11, col 12 is the beginning of this variable.)

An example application would be:

```yaml
platforms:
  - name: "instance"
    image: "${namespace:+$namespace/}fedora"
```

Where the variables could be:

- no variables set, `image` should expand to `fedora`
- namespace set to `robertdebock`, `image` should expand to `robertdebock/fedora`. (Mind that `/`.)

**Comment by ssbarnea** [comment]
I will close this because it seems a corner case but if anyone wants it so much to create PR with tests, I will not oppose it.
