### ISSUE TITLE
molecule needs to generate an implicit execution GUID like

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2420]
While https://github.com/ansible/molecule/pull/2377/files documents a workaround for creating some unique resource name we shoudl make this a core feature of molecule, which should expose a documented variable that is an unique-enough ID for a an execution.

This should allow running
* same scenario on multiple machines (CI testing with multiple jobs running the same code)
* be persistent for local user running various tasks
* be generated before create runs (is needed by create)

**Comment by decentral1se** [comment]
Agree. We need this.

While I'm a bit wary of my own experiments, the `--parallel` functionality does generate an internal UUID which is used for creating a unique location on the file system for caching connection details. It is only available for certain sequences but it would probably be enough to cover the use cases listed here.

Perhaps ensuring that the UUID is injected into the run environment as some named variable like `$RUN_UUID` would be enough? Then document that it is available. This could be a small change and potentially work ...
