### ISSUE TITLE
molecule init role detects .git directory as populated role

### ISSUE THREAD

**Issue by dnorthup-ums** [ansible-community/molecule#2430]
<!- - - Verify first that your issue is not already reported on GitHub - ->
✔
<!- - - Do not report bugs before reproducing them with the code of the master branch! - ->
I'd love to, but I don't have the additional time to actually get it running on Fedora just to report a very simple and basic oops. It doesn't appear that this has been merged into master yet anyhow.

# Issue Type

- Bug report
(Rather minor bug, but kinda annoying.)

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dnorthup/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
molecule, version 2.20.1
```
I cannot get a newer version of molecule running on this platform. Yes, I did try, and no it isn't the fault of the molecule team.

Molecule installation method (one of):

- rpm built from source to match OS package format (if the original had worked properly)

Ansible installation method (one of):

- OS package

Detail any linters or test runners used:
Didn't get that far here, they seem to work as much as I can expect given bugs others have reported elsewhere.

# Desired Behavior

Allow a new role skeleton to be instantiated into an existing but otherwise effectively empty GIT repository (EG: only contains the ".git" directory and contents).

(I think that it is obvious why we wouldn't want to "init" into a directory containing a built-out role, so I'm not suggesting that.)

# Actual Behaviour

``` bash
[dnorthup@hostname Roles]$ git clone git@gitlab.domain:Roles/molecule_template.git
Cloning into 'molecule_template'...
warning: You appear to have cloned an empty repository.
[dnorthup@hostname Roles]$ molecule init role -r molecule_template
--> Initializing new role molecule_template...
ERROR: The directory molecule_template exists. Cannot create new role.
```

**Comment by kevingentile** [comment]
It doesn't feel right to me to initialize a molecule role outside of the git repository it lives in. I would expect `molecule init role` to, by default, inherit the parent directory as the role name. Thus,

```
cd molecule_template
molecule init role
```

This would require a conditional modification to the [call-through to ansible-galaxy](https://github.com/ansible-community/molecule/blob/master/molecule/command/init/role.py#L77). Something like:

```
cmd = ["ansible-galaxy", "init", "-v", "--offline", "--force", "--init-path ../", os.getcwd()]
```

However, I'm a bit weary of the `ansible-galaxy --force` flag.

Additionally, the [exit call](https://github.com/ansible-community/molecule/blob/master/molecule/command/init/role.py#L77) @dnorthup-ums is hitting should prompt to use an existing directory if the role name matches the name of a directory within the current working directory (and ignore prompt with an additional flag).

**Comment by ssbarnea** [comment]
Invalid, unable to reproduce.

**Comment by dnorthup-ums** [comment]
@ssbarnea Excuse me, but it doesn't seem like you tried very hard.

```bash
[dnorthup@drew-northup tmp]$ mktemp -d
/tmp/tmp.6mHDzHLFNb
[dnorthup@drew-northup tmp]$ cd /tmp/tmp.6mHDzHLFNb
[dnorthup@drew-northup tmp.6mHDzHLFNb]$ mkdir roletest
[dnorthup@drew-northup tmp.6mHDzHLFNb]$ cd roletest/
[dnorthup@drew-northup roletest]$ git init
Initialized empty Git repository in /tmp/tmp.6mHDzHLFNb/roletest/.git/
✔ /tmp/tmp.6mHDzHLFNb/roletest [master L|✔] 
09:36 $ cd ..
[dnorthup@drew-northup tmp.6mHDzHLFNb]$ molecule init role -r roletest
--> Initializing new role roletest...
ERROR: The directory roletest exists. Cannot create new role.
```

**Comment by kevingentile** [comment]
@ssbarnea 
![molecule_git_init](https://user-images.githubusercontent.com/10604101/74767833-909b0e00-5255-11ea-8e9e-184cd230605b.gif)

**Comment by dnorthup-ums** [comment]
@kevingentile That actually should fail. My example doesn't result in a subdirectory containing a role which then gets initialized over.

**Comment by ssbarnea** [comment]
What you do in the video makes no sense, correct steps:
```
mkdir myproject
cd myproject
git init
molecule init role myrole
cd myrole
molecule list
Instance Name    Driver Name    Provisioner Name    Scenario Name    Created    Converged
---------------  -------------  ------------------  ---------------  ---------  -----------
instance         docker         ansible             default          false      false
```

Also be sure you use latest prerelease, 3.0a9 (which is likely to becomade official 3.0 in the next couple of days).

**Comment by dnorthup-ums** [comment]
@ssbarnea What you list also doesn't make sense when using ANY collaborative git hosting platform (github, GitLab, etc), as you're expecting users to set their remotes by hand instead of the standard workflow of cloning a repo then working in it. I only used it as a minimal test case to show how minimal I could make my test case.
I have no idea why both you and @kevingentile insist on throwing in an extra level of directory structure. If I'm building a role that I'm going to write to standards so that I can possibly share it with the community then I'm going to write it in the base directory of the repository, not a subdirectory, as that's the best practice promoted by the Ansible Galaxy community.

**Comment by dnorthup-ums** [comment]
@ssbarnea Additionally, while I know it makes things easier for Devs for everyone to run the latest, I am a working systems engineer type person. I don't run alpha software on my work desktop unless I have no other option. I have work to get done. I only ever ran the git.git `pu` branch when hacking on git itself (at home) for a reason.

**Comment by kevingentile** [comment]
@dnorthup-ums 
The use case provided by @ssbarnea is how you would initialize a role in your typical Ansible directory structure:
```
.git/
roles/
-- mymoleculerole/
---- README.md
---- defaults/
---- handlers/
---- meta/
---- molecule/
---- tasks/
---- vars/
```

Reading the ticket your use case sounded similar to my own, but to clarify:

I want to manage roles as individual git repositories to make them portable. The code change in my previous comment accomplishes this (poorly). 

--
My expected use case:

```
mkdir mymoleculerole
cd mymoleculerole
git init
molecule init role -r .
```

Yields:

```
mymoleculerole/
-- .git/
-- README.md
-- defaults/
-- handlers/
-- meta/
-- molecule/
-- tasks/
-- vars/
```

I want this flexibility to separate the git history of unrelated roles. This allows me to version individual roles instead of versioning groups of roles.

The workaround is to initialize the git repository and set your upstream after creating the molecule role.

**Comment by dnorthup-ums** [comment]
@kevingentile Yes, I know the work-around. Our use case here where I work, at the University of Maine System, is similar to your own. However, the majority of people involved in Configuration Management are not people whom have been using Revision Control Systems for many years and are therefore not familiar with all of the available workarounds. The main thing that bothers me is the lack of a cohesive observance between these related projects (Ansible, the Ansible Galaxy community, and Molecule) of each other's stated best practices. At this point I'm not expecting anybody to care, even if I did have the time to author a patch.
