### ISSUE TITLE
Make prepare silent

### ISSUE THREAD

**Issue by robertdebock** [ansible-community/molecule#2431]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.8.5
  config file = None
  configured module search path = ['/home/robertdb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
molecule, version 2.22
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

When CI fails (in my case, quite often ;-) ) I need to scroll down and find the error in a long list of output.

I'd like molecule to be more silent and only show the `converge` output. I'm less interested in the `prepare` output. (Maybe if `prepare` failed, show the output, otherwise be (more) silent.

Other molecule users may be interested in the prepare output, so I guess a parameter needs to be introduced to change the behavior of Molecule. A suggestion:

```yaml
provisioner:
  name: ansible
  options:
    prepare_output: none|all|on_failure
```

**Comment by decentral1se** [comment]
We've definitely had an issue with verbosity being either too little or too much. This could be a good way to start to reduce the noise.

I am worried that it is too many fiddling in the configuration. For each sequence step, we'll have a output none/all/on_failure? We should also provide these on the CLI too which also feels like overkill.

Glad you raised this ticket but I'm not satisfied on how to proceed. 

Looking forward to hear more thoughts.

**Comment by robertdebock** [comment]
I would be happy of prepare showed output only on failure by default. So maybe register the output and show when prepare is failed.

I could even go as far as to say that I don't need output if any step (even converge) has no errors, but I guess that's a little extreme.

**Comment by ssbarnea** [comment]
I am closing this because is unlikely any core would implement it but others are welcomed to raise PR that implements this feature.
