### ISSUE TITLE
Use non-default shell, like /bin/sh instead of /bin/bash

### ISSUE THREAD

**Issue by robertdebock** [ansible-community/molecule#2432]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.8.5
  config file = None
  configured module search path = ['/home/robertdb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
molecule, version 2.22
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Some containers do not have `/bin/bash`, so login result in an error:
```
molecule login
--> Validating schema /my_role/molecule/default/molecule.yml.
Validation completed successfully.
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"bash\": executable file not found in $PATH"
```

I'd like to be able to tell molecule to use a different shell. Maybe something like this:
```yaml
platforms:
  - name: "my_instance"
    image: "alpine"
    pre_build_image: yes
    login_shell: /bin/sh
```

**Comment by ssbarnea** [comment]
Title is misleading, i suppose you want to use default shell of the machine instead of current bash. My impression is that this can be controlled via inventory vars but have a look.

I can understand the need and I will support a PR in this area, even if it proves to be only on the docs.
