### ISSUE TITLE
Idempotence test fails with no output

### ISSUE THREAD

**Issue by till** [ansible-community/molecule#2439]
# Issue Type

- Bug report

# Molecule and Ansible details

Using `quay.io/ansible/molecule:2.22`

Molecule installation method (one of):

- docker

Ansible installation method (one of):

- docker

Detail any linters or test runners used:

- ansible-lint
- testinfra/pytest
- flake8 

(Standard setup.)

# Desired Behavior

I'm running a complex molecule scenario where I boot multiple instances and use multiple roles to assemble a cluster of servers. I made a change to one of the roles yesterday (to fix a bug) and now molecule is reporting the idempotence check fails, but I would like to know which task it fails on. 

# Actual Behaviour

I ran with `no_log: false` and `--debug` — the output is the same:

```
--> Scenario: 'multi-node'
--> Action: 'idempotence'
ERROR: Idempotence test failed because of the following tasks:
An error occurred during the test sequence action: 'idempotence'. Cleaning up.
--> Scenario: 'multi-node'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'multi-node'
--> Action: 'destroy'
```

I've been struggling with this for a few hours now, unable to find out what it fails on. Are there any "special" options or methods to enable more _verbose_ output for the idempotence tests?

**Comment by decentral1se** [comment]
Hmmm, that is strange. I'd install molecule HEAD locally (see https://molecule.readthedocs.io/en/stable/installation.html#source) and then patch or drop into a debugger when the idempotence test is happening. See https://github.com/ansible/molecule/blob/master/molecule/command/idempotence.py#L83. Also, see https://molecule.readthedocs.io/en/stable/faq.html#why-is-my-idempotence-action-failing. If you can track it down further, we can follow it up.

**Comment by till** [comment]
@decentral1se Thanks, I'll have a look. Not really a Python developer, but I can `print()` like a boss. 🎉 

General question though. Would it be too much to have a more output in `--debug` or a `--verbose-idempotence` flag in the future? E.g. so people wouldn't have to patch source locally.

**Comment by till** [comment]
@decentral1se thanks, so going down a rabbit hole, I encountered this:
https://github.com/ansible/molecule/pull/2391#issuecomment-554334523

Someone on `#ansible-molecule` was kind to provide some help how to install the drivers with `HEAD`, but it looks like the removal of the driver broke something else. I am not sure how to continue at this point?

**Comment by till** [comment]
I have a working `Dockerfile`:

```
FROM quay.io/ansible/molecule:latest
RUN apk add --update build-base git
RUN pip install --upgrade pip
RUN pip install dnspython requests==2.20.1 docker docker-compose hcloud
RUN pip install git+https://github.com/xlab-si/molecule-hetznercloud.git@register-entrypoint#egg=molecule-hetznercloud
RUN pip install ansible==2.8.4
```

h/t @tadeboro

**Comment by decentral1se** [comment]
Sorry, forgot that the master branch is like a bomb hit it! Thanks for your perseverance.

> General question though. Would it be too much to have more output in --debug or a --verbose-idempotence flag in the future? E.g. so people wouldn't have to patch source locally.

We probably should allow for something like this to avoid rabbit holes!

**Comment by till** [comment]
I got it running — I think @tadeboro helped me.

So, the issue is, that we have a command in the ansible run, which can fail — it turns out to be `fatal` and `changed` at the same time. This is completely hidden in the run though.

**Comment by till** [comment]
I'll provide more logs in a bit.

**Comment by till** [comment]
```
TASK [p-node : Add the 'DOCKER-USER' chain via firewalld (runtime)] ***
fatal: [cluster-node-02-111]: FAILED! => {"changed": true, "cmd": ["firewall-cmd", "--direct", "--add-chain", "ipv4", "filter", "DOCKER-USER"], "delta": "0:00:00.341732", "end": "2019-11-15 14:42:45.711832", "msg": "non-zero return code", "rc": 13, "start": "2019-11-15 14:42:45.370100", "stderr": "Error: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore: line 2 failed", "stderr_lines": ["Error: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore: line 2 failed"], "stdout": "", "stdout_lines": []}
...ignoring
fatal: [cluster-node-01-111]: FAILED! => {"changed": true, "cmd": ["firewall-cmd", "--direct", "--add-chain", "ipv4", "filter", "DOCKER-USER"], "delta": "0:00:00.617123", "end": "2019-11-15 14:42:46.194097", "msg": "non-zero return code", "rc": 13, "start": "2019-11-15 14:42:45.576974", "stderr": "Error: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore: line 2 failed", "stderr_lines": ["Error: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore: line 2 failed"], "stdout": "", "stdout_lines": []}
...ignoring
```

I think these are the tasks that trigger the `changed=1`, but they are not shown in the output, unless you dump it yourself inside Molecule's code base.

I am pretty sure I am doing it wrong :trollface:, never the less, it would be great if Molecule would show this output to the user.

**Comment by till** [comment]
@ssbarnea Any comment?

**Comment by ssbarnea** [comment]
Based on what I read I understand that this happens in a particular case only, so that is why I closed it. Still, if you find an easy way to replicate it even better. Try to make a PR that adds a test that replicates the issue and we can even merge it as xfail.

**Comment by till** [comment]
@ssbarnea fair enough, I can try to provide a molecule scenario, where would you like a test to be added otherwise?
