### ISSUE TITLE
plugins: how to pass cerberus validation schema to core?

### ISSUE THREAD

**Issue by decentral1se** [ansible-community/molecule#2442]
In Molecule < 3.0, we have all the driver schemas defined in the schema_v2 file. We then run the cerberus validator on this schema against the configuration specified by the user.

However, in the move to 3.0, we removed the shema code. See https://github.com/ansible/molecule/pull/2391/files#diff-1e67bc3147c69bed463615849b56f3b1L490 for that removal for the hetzner cloud driver.

So, now I find that my molecule-hetznercloud plugin unit tests are failing schema validation and only the "name" option is being validated against (that is because molecule core has that still in the code).

So, my idea is:

1) Should we define schemas in the plugins (move them over)
2) How to pass this schema into core for validation?

For 2) if we've successfully loaded the plugin, then we can be pretty sure we can run an import if the schemas are placed in a standard location or accessor off the module. 

One tricky point is that some drivers, like docker, are not externalised yet, so we'd have to conditionally check that we should be importing from a plugin and not from a schema_v2 definition.

I don't really like Cerberus as a dependency but we need user configuration validation with decent error messages and this is what it gives us. It is also seemingly well maintained.

**Comment by decentral1se** [comment]
Also see https://github.com/ansible/molecule/pull/2391#issuecomment-554334523 as an example of what is happening. Molecule doesn't have a validation schema for the plugin so it thinks the values being used from the molecule.yml configuration are invalid.

**Comment by tadeboro** [comment]
I am not sure how well-defined is the API that drivers should implement, but maybe we can simply add another function (for example `platform_schema` for drivers) that returns a schema in a format that we can call in Molecule and merge that stuff with the rest of the schema?

**Comment by decentral1se** [comment]
Yep, that's the general idea indeed @tadeboro! After some discussion I'm leaning towards using the ArgumentSpec of Ansible core. They're doing it all already. For example, the docker module: https://github.com/ansible/ansible/blob/7f643690c7535c2623c52809cd27b3231b9f0fa7/lib/ansible/modules/cloud/docker/docker_container.py#L3153. We'd just reach into Ansible (which we're already doing in some ways) and pull out that spec and run validation against what the user is passing in. Then we just point users to the standard Ansible module documentation when forming their configuration schema. This would be a pretty big breaking change though.

Please also bear in mind, there are other solutions being proposed for this in https://github.com/ansible/molecule/issues/1923. It's all the same sides of the coin, specifying what the user can pass in from their configuration and what Molecule expects. They may be more compatible, I'm not sure.

Remember, the simplest is adding a "platform_schema" attribute to plugins and Molecule  continues to run validation as it does now.

**Comment by tadeboro** [comment]
I am not sure if grabbing the argument specification directly from the module is the best idea. Ansible core is actively trying to remove all modules and move them into collections. What will happen once the docker module is gone from the core? I know this will break the Molecule in more that one way even without this change, but it still feels wrong adding new functionality that is destined to fail at some point in time.

**Comment by decentral1se** [comment]
But all functionality is destined to fail at some point :) Well, this code will still be importable from collection side and not core side and we'll probably have ample time to migrate with the release process of Ansible. It still avoids duplication in the most effective way, as far as I see it.

**Comment by decentral1se** [comment]
Also, bear in mind, this argspec code comes with the module which we'll have to import anyway to actually run the driver. So, we're already in the position of having to deal with breaking imports already.

**Comment by ssbarnea** [comment]
Add new method to base driver, default to return a False value so we can ignore validation.

**Comment by decentral1se** [comment]
So if users enter bad values, they won't receive feedback and any indication of what they should change? If users enter values that shouldn't be there, they will be silently ignored? We're just going to hand back stack traces or command invocation errors?

**Comment by ssbarnea** [comment]
Let me give you one example: when you orverride the driver! One may want/need to put values that do not make sense for docker but that make semse to podman but still allow user to overide the confugures driver. How can we validate this?

**Comment by decentral1se** [comment]
I am not sure what you mean by overriding. 

I'm open to ideas but we need a solution for this for 3.0 that has feature parity with the existing validation solution.

**Comment by decentral1se** [comment]
Not relevant anymore.
