### ISSUE TITLE
Unable to load the cache plugin (memory)

### ISSUE THREAD

**Issue by axil76** [ansible-community/molecule#2444]
Hello,
when I run molecule I have the following error message

 ansible-playbook 2.9.0
      config file = /root/.cache/molecule/itaas/default/ansible.cfg
      configured module search path = [u'/tmp/.gitlab-ci/venv/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries', u'/root/.cache/molecule/itaas/default/library', u'/tmp/src/itaas/library']
      ansible python module location = /tmp/.gitlab-ci/venv/lib/python2.7/site-packages/ansible
      executable location = /tmp/.gitlab-ci/venv/bin/ansible-playbook
      python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
    Using /root/.cache/molecule/itaas/default/ansible.cfg as config file
### ERROR! Unable to load the cache plugin (memory).
ERROR:
(venv) /tmp/src/itaas $ cat /root/.cache/molecule/itaas/default/ansible.cfg
# Molecule managed

[ssh_connection]
control_path = %(directory)s/%%h-%%p-%%r
scp_if_ssh = True
[defaults]
host_key_checking = False
ansible_managed = Ansible managed: Do NOT edit this file manually!
retry_files_enabled = False
fact_caching = jsonfile
nocows = 1

Is it necessary to put a special config of ansible?

Thanks

**Comment by decentral1se** [comment]
That looks like an Ansible thing not a Molecule thing? Unsure.

**Comment by seandst** [comment]
https://docs.ansible.com/ansible/latest/plugins/cache/jsonfile.html
`fact_caching_connection` is a required config key, this is indeed not a molecule thing.

**Comment by decentral1se** [comment]
:+1:

**Comment by ssbarnea** [comment]
I am reopening this because our documentation example does not include `fact_caching_connection`, so is misleading the users that this may be enough to enable caching.
