### ISSUE TITLE
How to specify tag with molecule test 

### ISSUE THREAD

**Issue by krimitalel** [ansible-community/molecule#2449]
Hello,

is there a way to specify tag when executing molecule test ( ex molecule test -- --tags foo,bar ) ?

apparently, it works only with molecule converge ( molecule converge -- tags foo,bar )

**Comment by rafaelpirolla** [comment]
Example:
molecule converge -- -vvv --tags foo,bar

**Comment by lanceofwhichwedream** [comment]
I'd like to see this added as well

**Comment by liuyangc3** [comment]
I guess only molecule `converge` and `idempotence` needs the tags. but idempotence not support tags ansible args yet.
