### ISSUE TITLE
molecule.yml user template

### ISSUE THREAD

**Issue by apatard** [ansible-community/molecule#2490]
# Issue Type

- Feature request

It's possible to provide a template for scenario with `--driver-template` but it's quite limited.
Is there a way to change the `molecule.yml` template ?

# Molecule and Ansible details

```
ansible --version && molecule --version
```
ansible 2.7.7, molecule 2.22

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

# Desired Behavior

Please give some details of the feature being requested

I'm using the same `molecule.yml` file for role testing, with the only difference being the instance name and the docker image to use (for my docker based tests). In reality, it's the same `molecule.yml` everywhere and I'm using variables.

Of course, it's not the same as the default one provided by molecule. It would be nice if it was possible to provide a template for it, instead of using `molecule init scenario ...` and then overwrite the `molecule.yml` file. That would make one thing less to do.

**Comment by ssbarnea** [comment]
You can use cookiecutter alone to create any kind of template you wish. We are not going to extend the templating support in molecule because it overlaps too much with cookiecuttter.
