### ISSUE TITLE
conftest.py logically dead code

### ISSUE THREAD

**Issue by huornlmj** [ansible-community/molecule#2491]
https://github.com/ansible/molecule/blob/65101392b49bc18581ee78ae17669db97f7df77f/molecule/test/conftest.py#L146

The line `if not is_sharded:` cannot be evaluated as true so the condition it controls is dead, not reachable.  `is_sharded` is assigned True on line 143 (boolean).

**Comment by ssbarnea** [comment]
I will remove all sharding related code once we finish #2488 as we will no longer need it.

**Comment by ssbarnea** [comment]
Fixed in master. Next time just make a PR for such minor issues.
