### ISSUE TITLE
Moving molecule docs under https://docs.ansible.com/molecule/

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2494]
@gundalow I would like to switch the default location of published documentation of molecule from  https://molecule.readthedocs.io  to  https://docs.ansible.com/molecule/ so it would also match how ansible-lint is published.

Do you think this is possible?

**Comment by gundalow** [comment]
That's doable, though would require some infrastructure work on the Ansible side. At the moment the docs and infrastructure teams priorities are around Collections.

This is something we can revisit later in the year.

**Comment by ssbarnea** [comment]
Yeah, that was the idea. After migration to zuul, release of version 3.0, conversion of docs to the same format used there. Is more of longer term goal as you said.

**Comment by decentral1se** [comment]
Any news on this?

**Comment by ssbarnea** [comment]
Considering that the linter was also moved outside the docs, I am not sure if this will ever happen. Presence under docs.ansible.com is nice but bureaucracy proved to prevent an easy way to update it.

I will close this bug because I do not see any actionable here with the note that we should still pursuit it in the future.
