### ISSUE TITLE
molecule.yml schema validator is too restrictive for 'env'

### ISSUE THREAD

**Issue by greenmaid** [ansible-community/molecule#2495]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible 2.9.3
  ...
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
molecule, version 2.22
```

Molecule installation method:

- pip

Ansible installation method:

- pip

Detail any linters or test runners used:

molecule.yml:
```
platforms:
  - name: instance
    image: centos:7
    env: 
      test.env: something
```

# Desired Behavior

Schema validator should comple successfully and container be running with 'test.env' variable

# Actual Behaviour

```
$ molecule create
--> Validating schema /xxxxx/molecule/default/molecule.yml.
ERROR: Failed to validate.

{'platforms': [{0: [{'env': [{'test.env': ["value does not match regex '^[a-zA-Z0-9_-]+$'"]}]}]}]}
```

According to used regexp, variable names should not contain point ('.') character. I think it is too restrictive, some products (eg elasticsearch) are configured using such variables.

**Comment by ssbarnea** [comment]
Lets to a test:
```
$ export FOO.BAR=xx                                                                                                                                                       
export: not valid in this context: FOO.BAR
```

Case closed. ;)

**Comment by greenmaid** [comment]
Well, but :

```
$ env FOO.BAR=xx printenv | grep FOO
FOO.BAR=xx
```
or 
```
$ docker run --rm -e FOO.BAR=xx alpine printenv | grep FOO
FOO.BAR=xx
```

1. It is only a shell restriction. There is no problem at system level. 
2. Main shells also refuse env variable with dash (-) but it is allowed by molecule. Why not for dot (.) ?
3. As said before, some docker images rely on variables with dot for configuration. Example : [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode)

**Comment by ssbarnea** [comment]
I would accept a fix for dash but I see no reasons to accept the dot. Not sure what elasticsearch team was smoking when they started to use variables that cannot be defined on shells.

Have you tried to patch molecule and see if it manages to resolve your problem? ...as in suceeding in setting that variable?

If it works, please create a PR that is addressing both issues, accepting dash and dot. I will merge it.
