### ISSUE TITLE
add molecule reset command

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2496]
If you switch driver on existing scenario you are high-likely to endup with molecule being broken because the temporary files are not updated and it still believes instances are managed by different driver.

This is usually fixed by doing a  `rm -rf ~/.cache/molecule/*`, but it should be a `molecule reset` command that does this.

**Comment by andreamaruccia** [comment]
nice

**Comment by ssbarnea** [comment]
@andreamaruccia If you can make a PR to implement it it would be great because these weeks/months I am deep into fixing other issues.

**Comment by andreamaruccia** [comment]
I'll have a look no promises :)

**Comment by mwhahaha** [comment]
I think you mean ~/.cache/molecule/
