### ISSUE TITLE
reimplement release of molecule using zuul

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2502]
Since we moved from Travis to Zuul CI we have reimplement its release logic job.

On **tag pushes** the following must run:

```bash
tox -e build-dists
twine upload --disable-progress-bar --skip-existing --verbose dist/*
```

Obviously that twine needs to be configured with credentials in order to be able to do this.

@pabelanger I will need few hints from you about how to do this, maybe you have a similar example? I suppose that job will not be defined in repo.

**Comment by pabelanger** [comment]
My plan here, is re-use the job in opendev.org, I will start on it for Monday.  This is built on the build-python-release role:

  https://opendev.org/zuul/zuul-jobs/src/branch/master/roles/build-python-release

The job is built atop of the following playbooks:

  https://github.com/openstack/project-config/tree/master/playbooks/pti-python-tarball

I'd like to first try to upload to https://test.pypi.org/ then we can flip the job to use pyp.org. I expect it to take maybe 3 days to implement and test.

**Comment by ssbarnea** [comment]
Sounds like a very good plan. My only remark is about giving it a more generic name: like "release", or "deploy-release". This job is likely to perform several functions in the future: building and publishing wheels, rpms, containers.

Let me know if you need any help on it.

**Comment by ssbarnea** [comment]
Got confirmation that this works last week.
