### ISSUE TITLE
Dockerfile.j2 does not support Ubuntu 20.04/focal or CentOS/RHEL 8 = no "python" package

### ISSUE THREAD

**Issue by dgvigil** [ansible-community/molecule#2517]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.9.4
  config file = None
  configured module search path = ['/Users/dgvigi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:28) [Clang 11.0.0 (clang-1100.0.33.16)]
molecule, version 2.22
```

# Desired Behavior
I am unable to build updated containers with which to test my code.

# Actual Behaviour

The `TASK [Build an Ansible compatible image (new)]` fails since CentOS/RHEL 8 and Ubuntu 20.04 no longer have a package named `python`. 

from CentOS 8:
`failed: [localhost] (item=molecule_local/centos:8)` ... `, 'No match for argument: python\\n', 'There are following alternatives for \"python\": python2, python36\\n', 'No match for argument: python-devel\\n', 'Package python3-dnf-4.2.7-7.el8_1.noarch is already installed.\\n', 'Package bash-4.4.19-10.el8.x86_64 is already installed.\\n', 'Package iproute-4.18.0-15.el8.x86_64 is already installed.\\n', '\\x1b[91mError: Unable to find a match: python python-devel\\n\\x1b[0m', 'Removing intermediate container 63b86fe3c05c\\n']"}`

and from Ubuntu 20:04
`failed: [localhost] (item=molecule_local/ubuntu:focal)` ... `'Package python is not available, but is referred to by another package.\\nThis may mean that the package is missing, has been obsoleted, or\\nis only available from another source\\nHowever the following packages replace it:\\n  python2-minimal python2 2to3\\n\\n', \"\\x1b[91mE: Package 'python' has no installation candidate\\n\\x1b[0m\", 'Removing intermediate container 9a38944294fe\\n']"}`

There is a little bit of crossover here with: #2348

**Comment by ssbarnea** [comment]
Quote from the second line in the bug template: `Do not report bugs before reproducing them with the code of the master branch!`

**Comment by mconigliaro** [comment]
This is a legitimate bug. I tried the embedded `Dockerfile.j2` from #2360 (which is on master) and got the same error on Ubuntu 20.04:

    Package python is not available, but is referred to by another package.

That's because the `python` package was renamed to `python2` in 20.04. It works fine after updating my local `Dockerfile.j2` with the correct package name, with the caveat that the `Dockerfile.j2` won't be backwards compatible with Ubuntu versions prior to 20.04 anymore. If you need both platforms, you'll have to maintain two separate `Dockerfile` templates and do something like this in your `molecule.yml`:

    - name: xenial
      image: ubuntu:16.04
    - name: focal
      image: ubuntu:20.04
      dockerfile: Dockerfile-focal.j2
