### ISSUE TITLE
proposal: rename playbook.yml to converge.yml

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2531]
## Motivation

In order to make molecule less confusing for users, I would like to propose renaming `playbook.yml` to `converge.yml`.

### Problems

Each sequence command should match a file name with the same name. This is true to most cases but not for the most important one, `converge` command which loads playbook file.

It is easy to understand how this creates confusions

## Solution proposal

First step would be to change code to look first for new name and fallback to old name with a deprecation warning, mainly not a breaking change.

## Anything else?

If you have others ideas regarding matching sequence steps to playbooks names, please comment.

Also use thumbs up and down to support of express disapproval about the proposal.

**Comment by KeyboardInterrupt** [comment]
I like that Idea. 👍
Also +1 for keeping the `playbook.yml` alias around 😉!
