### ISSUE TITLE
ability to define implicit preparing command at repository level

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2565]
I recently realized that there is a read need to run a host preparatory command, like a shell script that configures mirrors on hosts.

If you have 100 scenarios, changing all of them is a real maintenance nightmare, example https://review.opendev.org/#/c/708808/

If we can add an option to molecule to run a script before prepare, for any scenario, we could avoid having to touch all these scenarios.

Implementing this could be tricky because at prepare step, the only command that we are guaranteed to be able to run is `raw`, as the tested containers may not have python yet.

Regarding implementation, I would say that molecule could look for presence of `REPO/.config/molecule/prepare.yml` and run it automatically if found.

**Comment by ekultails** [comment]
I like where this is going!

This would basically add some kind of global "pre-prepare" step for all Molecule instances, right? That sounds useful. We could have a built-in immutable "pre-pre-prepare" playbook that will bootstrap/install Python with `raw`. Then the operator can define their own "pre-prepare" tasks (ex. setting up local repository mirrors, network/time config, etc.). I'm not sure if we want to handle repository mirrors in the scope of Molecule. If we do, perhaps make it optional? Operators may expect that the repos be the default ones.
