### ISSUE TITLE
Docker Image: using `apk` always fails due to Dockerfile syntax error

### ISSUE THREAD

**Issue by dduportal** [ansible-community/molecule#2581]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ docker run --rm -ti quay.io/ansible/molecule:3.0.1 sh -c "ansible --version && molecule --version"
ansible 2.9.4
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.1 (default, Jan 19 2020, 11:48:03) [GCC 9.2.0]
molecule 3.0.1
   ansible==2.9.4 python==3.8
```

Molecule installation method (one of):  Docker Image (pip)

Ansible installation method (one of): Docker Image (pip)

# Desired Behavior

As a molecule user using the Docker image `quay.io/ansible/molecule:3.0.1`
When I run a container based on this image 
And that I install any package within using the command `apk add --no-cache <package-name>` (exemple with `rsync`)
Then I expect the package to be installed (with a working network of course).

# Actual Behaviour

Any `apk` commands fails with the following error:

```
ERROR: unsatisfiable constraints:
  /root/.cache (missing):
    required by: world[/root/.cache]
  apk (missing):
    required by: world[apk]
  del (missing):
    required by: world[del]
  etc (missing):
    required by: world[etc]
  gem (missing):
    required by: world[gem]
  install (missing):
    required by: world[install]
  json (missing):
    required by: world[json]
  rm (missing):
    required by: world[rm]
  rubocop (missing):
    required by: world[rubocop]
```

# Reproduction Case:

```
$ docker run --rm -ti quay.io/ansible/molecule:3.0.1 apk add --no-cache rsync
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  /root/.cache (missing):
    required by: world[/root/.cache]
  apk (missing):
    required by: world[apk]
  del (missing):
    required by: world[del]
  etc (missing):
    required by: world[etc]
  gem (missing):
    required by: world[gem]
  install (missing):
    required by: world[install]
  json (missing):
    required by: world[json]
  rm (missing):
    required by: world[rm]
  rubocop (missing):
    required by: world[rubocop]
```

# Proposed Fix

Incoming PR: the flattened `RUN` instruction at https://github.com/ansible-community/molecule/blob/3.0.1/Dockerfile#L137 (link points to `3.0.1` tag but it's the same on `master`) is made of 4 different shell instructions, without any separator, which result in passing the 3 last instructions as arguments to `apk`.

Adding `&&` instructions separator would fix the issue and provide fail fast pipeline.

PR incoming

**Comment by abeluck** [comment]
@ssbarnea Would it be possible to get the docker images at https://quay.io/repository/ansible/molecule?tab=tags rebuilt?

**Comment by dduportal** [comment]
Good point, what is the release process for this @ssbarnea . Is there anything we could do to help on this part ?
