### ISSUE TITLE
Proposal: `docker commit` During `verify.yml` with Base Image `ENTRYPOINT` and `CMD`

### ISSUE THREAD

**Issue by hswong3i** [ansible-community/molecule#2594]
# Proposal: `docker commit` During `verify.yml` with Base Image `ENTRYPOINT` and `CMD`

*Author*: Wong Hoi Sing Edison <@hswong3i>

*Date*: 2020-02-29

- Status: New
- Proposal type: core design, schema changes
- Estimated time to implement: **DONE** (see #2595)

## Motivation

Create reusable Docker image after successful Molecule test cases, with original base image's `ENTRYPOINT` and `CMD`.

### Problems

When creating Docker image with Ansible, we may:
- `Dockerfile` based: Install Ansible and copy Playbooks into container by Dockerfile, then self-provision itself with Molecule + delegated driver to localhost
- `ansible-bender` based: Install podman, buildah and ansible-bender, then provision container from host to running container with buildah
- `molecule` based: run tests with docker or podman driver, then `docker commit` the result running container as a new image

With `moledule` based solution, when `docker commit` both `ENTRYPOINT` and `CMD` will be replaced by molecule's `entrypoint` and `command` options (see #2593), e.g. `''` and `bash -c "sleep infinity"`.

We need a way to discover the original base image's `ENTRYPOINT` and `CMD`, rollback them during `docker commit` with `--change`. 

## Solution proposal

Add a new `verify.yml` template for both docker and podman driver, which:
- Discover original base image info with `docker image inspect`
- Commit the result running container with `docker commit`, plus rollback original base image's `ENTRYPOINT` and `CMD` with `--change`

With this solution we could also simplify the definition of image meta data with `Dockerfile.j2` during local image creation, e.g. CMD | ENTRYPOINT | ENV | EXPOSE | LABEL | ONBUILD | STOPSIGNAL | USER | VOLUME | WORKDIR.

When compare with other else 2 container provision solution this is much better because:
- `Dockerfile` based: no more Ansible **INSIDE** the result container image (i.e. smaller image size), simplify all provision action into a single layer, support debug intermediate container with `molecule converge`
- `ansible-bender` based: support both docker and podman, with standard ansible coding style supporting (e.g. `import_playbook`, `import_role`, `group_vars`, etc)

## Dependencies (optional)

With #2593 we could ensure both `entrypoint` and `command` are overwritten from `Dockerfile.j2` by molecule correctly during provision phase, where also allow us to resume it as original with this proposal.

## Testing (optional)

Corresponding test cases updated (see #2595)

## Documentation (optional)

Corresponding documentation updated (see #2595)

## Anything else?

As a side effect we may also remove docker driver support for both `docker_host`, `cacert_path`, `cacert_path`, `key_path` and `tls_verify`, which we also didn't support with podman driver; This simply assuming we are running molecule with docker driver on localhost, only.

**Comment by ssbarnea** [comment]
I am going to close this because apparently it tries to go beyond the scope of molecule. I may be wrong, so I am happy to reopen it if someone can explain the use-case it tried to fix.

**Comment by klaus385** [comment]
This would be useful for the purpose of leveraging Molecule to build an image with `converge` that could be re-used from a docker registry. Especially without having to re-create what molecule does already out of the box. Which would have to be done with the Ansible docker modules.

Then from the same CI we could push to container registry to re-use the container converged by molecule.
