### ISSUE TITLE
Doc bug - Getting Started Guide - Scenario Layout does not match described example

### ISSUE THREAD

**Issue by mh182** [ansible-community/molecule#2596]
# Issue Type

- Bug report for documentation

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible 2.9.5
  config file = None
  configured module search path = ['/home/max/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/max/.local/lib/python3.6/site-packages/ansible
  executable location = /home/max/.local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
molecule 3.0.2
   ansible==2.9.5 python==3.6
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

The described layout in section _The Scenario Layout_ matches the one created by the example.

# Actual Behaviour

The directory `molecule/default` does not contain the file `Dockerfile.j2`, nor the directory `tests` (which exists in the root director).

```
$ molecule init role my-new-role
--> Initializing new role my-new-role...
$ tree
.
└── my-new-role
    ├── defaults
    │   └── main.yml
    ├── files
    ├── handlers
    │   └── main.yml
    ├── meta
    │   └── main.yml
    ├── molecule
    │   └── default
    │       ├── converge.yml
    │       ├── INSTALL.rst
    │       ├── molecule.yml
    │       └── verify.yml
    ├── README.md
    ├── tasks
    │   └── main.yml
    ├── templates
    ├── tests
    │   ├── inventory
    │   └── test.yml
    └── vars
        └── main.yml

11 directories, 12 files
```

**Comment by ssbarnea** [comment]
I think that the section is explained good enough, probably you did not use the latest branch when reading the documentation. Still, feel free to propose a PR that improves it.

**Comment by mh182** [comment]
I'm a bit disappointed how the bug report was handled. But maybe I misunderstand your comment - is the documentation fixed on the current branch or does it still diverge from the programs functioanlity?

> probably you did not use the latest branch when reading the documentation.
I think my bug report clearly states which version I use - the current stable (the version which you get from PyPi). And the documentation to which I refer is the current stable on https://molecule.readthedocs.io/en/latest/getting-started.html. 

It was a drive-by bug report because I was testing Molecule the first time in my live. I was irritated about the divergence in the documentation and assumed maybe other molecule-newbies will hit the same problem. 

If you feel that your documentation is good enough (even if the outcome of the step-by-step guide diverges from reality), fine. I even would not care if you say "I have higher priorities ATM and will fix it later". But insinuating that I use the wrong branch (I used the current package on PyPi) is not a good way to get potential contributors on board.

**Comment by ssbarnea** [comment]
Please make PR to improve the docs and I will be more than happy to review it. I close the bug because the issue was bit vague, bot because we would not welcome improvement of docs, especially docs.

**Comment by kevingentile** [comment]
I was also confused by lack of `Dockerfile.j2` in the role initialization, although it is optional. @mh182 you can find the [default template here](https://github.com/ansible-community/molecule/blob/master/molecule/data/Dockerfile.j2). I assume you can copy and paste this where molecule expects it to be and modify it as you will. 

@ssbarnea I would be happy to include this file with a flag on role init as a feature request if you like.

Additionally, I am having trouble tracking down an example of a molecule configuration file. If anyone can point me in the right direction I would appreciate it.

**Comment by mwmahlberg** [comment]
@ssbarnea The documentation clearly states that after a `molecule init role myrole`, which has an implied `-d docker`, the files created beyond `myrole/molecule/default` should be 
<img width="706" alt="Bildschirmfoto 2020-03-21 um 13 24 34" src="https://user-images.githubusercontent.com/138420/77226309-9e56f280-6b77-11ea-9cfb-55b0326fc848.png">
whereas it looks like this:
<img width="689" alt="Bildschirmfoto 2020-03-21 um 13 29 10" src="https://user-images.githubusercontent.com/138420/77226356-00175c80-6b78-11ea-8dfd-7b54cf48b582.png">

The Dockerfile.j2 is missing, since `molecule init role` did not create it. Neither does `molecule init scenario`:
<img width="689" alt="Bildschirmfoto 2020-03-21 um 13 31 45" src="https://user-images.githubusercontent.com/138420/77226388-51275080-6b78-11ea-8eb9-daeefe05bddc.png">

However, the `Dockerfile.j2` is crucial, for example to add python to vanilla docker images.

Hence, a better title for the issue would be "Dockerfile.j2 is not rendered during init`.

**Comment by mwmahlberg** [comment]
@kevingentile I can confirm that copying the default `Dockerfile.j2` to the specified location works as expected. However, one might need to delete all images beneath the `molecule_local/` namespace, namely if they were built before the `Dockerfile.j2` was in place.

**Comment by ssbarnea** [comment]
Yep, happened to me few times, please file a bug about this and if you can also propose PR for fixing it would be super-great. Sadly, I am overloaded with bootrapping plugin drivers and setting CI for them that I hardly find any more time to fix real bugs.

Also adding a templating option that copies the Dockerfile when creating new role/scenario would be appreciated, as this is a valid use case. In fact there are at least 3 options possible: embedded dockerfile, bare-dockerfile and pre-loaded-dockerfile. Anyway this would deserve its own ticket and there is no need to implement it entierly in a single PR.

**Comment by mwmahlberg** [comment]
@ssbarnea If you could hint me where the init code is to find, I will try to find the time for a PR.

**Comment by mwmahlberg** [comment]
@ssbarnea Oh, and it would make sense to reopen this issue ;)

**Comment by kevingentile** [comment]
@mwmahlberg https://github.com/ansible-community/molecule/tree/master/molecule/command/init

**Comment by PhilippSelenium** [comment]
Current link to [Dockerfile.j2](https://github.com/ansible-community/molecule-docker/blob/6437272f6988086f2b9af626902aca2886300cda/src/molecule_docker/playbooks/Dockerfile.j2)

Since this is still an issue I would also opt to reopen it

**Comment by huyz** [comment]
It's 2023. I'm new to molecule. Imagine when all the docs talk about `Dockerfile.j2` and it's nowhere to be found.  Clearly, this issue needs to be reopened, regardless of whether anyone has the bandwidth to submit a PR.
