### ISSUE TITLE
prerelease version of ansible-lint is getting installed

### ISSUE THREAD

**Issue by mafalb** [ansible-community/molecule#2646]
# Issue Type

- Bug report

Prelelease version of ansible-lint breaks new molecule installs

A prerelease version o# ansible-lint -v
Usage: ansible-lint [options] [playbook.yml [playbook2 ...]]|roledirectoryf ansible-lint was released
https://pypi.org/project/ansible-lint/4.3.0a0/

```$ pip install molecule[lint]``` is installing that prerelease because of

```ansible-lint >= 4.1.1a2, < 5``` in setup.cfg

because of that pip is concluding that a prerelease version of ansible-lint is OK.
But: there is a bug in ansible-lint 4.3.0a0 which is breaking CI
https://github.com/ansible/ansible-lint/issues/731

Much of my CI is broken.

Please use stable dependencies in stable molecule versions.

# Molecule and Ansible details

```
$ ansible --version
ansible 2.9.6
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /molecule/lib/python3.6/site-packages/ansible
  executable location = /molecule/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

```
$ molecule --version
molecule 3.0.3
   ansible==2.9.6 python==3.6
```

```
$ ansible-lint --version
ansible-lint 4.3.0a0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

- ansible-lint

# Desired Behavior

```$ pip install molecule[lint]``` installs stable version of ansible-lint, running it without playbook or role as argument does not give usage message, e.g.

```
$ ansible-lint -v
Unknown file type: .github/workflows/CI.yml
Unknown file type: galaxy.yml
Unknown file type: roles/plugin/tasks/main.yml
Found roles: roles/plugin
Found playbooks: molecule/default/converge.yml molecule/default/verify.yml molecule/install_molecule.yml molecule/requirements.yml
Examining molecule/default/converge.yml of type playbook
Examining molecule/default/verify.yml of type playbook
Examining molecule/install_molecule.yml of type playbook
Examining molecule/requirements.yml of type playbook
Examining roles/plugin/tasks/main.yml of type tasks
```

# Actual Behaviour

```$ pip install molecule[lint]``` installs prerelease version of ansible-lint

```
$ ansible-lint -v
Usage: ansible-lint [options] [playbook.yml [playbook2 ...]]|roledirectory
```

**Comment by ssbarnea** [comment]
@mafalb That sounds like pip behavior change because last time I checked using pre-release version as minimal version request did not enforce installation of another pre-release. Still, it will be very easy for your to make a PR that chages condition to `>=4.0.0` and I will be happy to merge it.

**Comment by mafalb** [comment]
I did some search on that pre-release behavior, see the links below.

https://github.com/pypa/pip/issues/7579
especially
https://github.com/pypa/pip/issues/7579#issuecomment-573417740

or
https://github.com/pypa/pip/issues/4969#issuecomment-358506226

However, I do not get that behaviour on all installations but I am not sure under exactly what conditions, it could be that it's only with python 3 (on a molecule install with python 2 on CentOS for instance I got ansible-lint 4.2.0, not the pre-release).

**Comment by ssbarnea** [comment]
I am going to close this because there is nothing actionable about it. We will continue to use pre-release as long the linter does not move to a faster release cycle.

Also keep in mind that the stability of a pre-release varies a lot from one project to another. Mainly is better to use a working pre-release than a broken release.
