### ISSUE TITLE
[3.x] Documentation: how to use non-core driver?

### ISSUE THREAD

**Issue by juju4** [ansible-community/molecule#2647]
# Issue Type

- Bug report / Documentation

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
molecule 3.0.2
   ansible==2.9.6 python==2.7
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

try using lxd driver following https://molecule.readthedocs.io/en/2.22/configuration.html#lxd but not in https://molecule.readthedocs.io/en/latest/configuration.html#driver
from https://github.com/ansible-community/molecule/blob/35af47bcfe2a260bad8ed7f4c7c402a5c2cdaeae/CHANGELOG.rst#30, lxd driver and others were moved out of core and in separate repo https://github.com/ansible-community/molecule-lxd

currently
```
# pip install molecule-lxd
ERROR: Could not find a version that satisfies the requirement molecule-lxd (from versions: none)
ERROR: No matching distribution found for molecule-lxd
```

how should we use those?
Thanks

# Actual Behaviour

```
$ molecule --debug create
---
dependency:
  name: galaxy
driver:
  name: lxd
lint: 'set -e

  #yamllint .

  #ansible-lint

  flake8

  '
platforms:
  - image: ${MOLECULE_DISTRO:-ubuntu:16.04}
    name: instance
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: ansible

ERROR: Failed to pre-validate.

{'driver': [{'name': ['unallowed value lxd']}]}
```

**Comment by decentral1se** [comment]
The idea is `pip install molecule-myplugin` and then you're done. The issue at the moment is that nobody is maintaining those plugins so the integrations are not working. See https://github.com/ansible-community/molecule-hetznercloud for more info.
