### ISSUE TITLE
Missing Shell Environment Variables

### ISSUE THREAD

**Issue by kevingentile** [ansible-community/molecule#2651]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible-playbook/library']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]
molecule 3.0.3
   ansible==2.9.6 python==3.8
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

Defining `ANSIBLE_LIBRARY` in the current shell passes the change down to molecule

# Actual Behaviour
```
echo $ANSIBLE_LIBRARY
/etc/ansible-playbook/library
```

```
molecule --debug converge
...
ANSIBLE_LIBRARY: /usr/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/modules:/root/.cache/molecule/my_role/default/library
...
```

The above excerpt from converge is missing shell defined `ANSIBLE_LIBRARY` identified by the ansible command (`configured module search path`).

The workaround is to pass the shell variable in the provisioner section of `molecule.yaml`

```
provisioner:
  name: ansible
  env:
    ANSIBLE_LIBRARY: $ANSIBLE_LIBRARY
```

**Comment by ssbarnea** [comment]
@kevingentile Be sure that when you implement this you will make it in a way that allows us to `passenv` multiple variables, not only `ANSIBLE_LIBRARY`.

**Comment by kevingentile** [comment]
Any feedback on this? Do we want to inherit ansible environment variables from the shell or only through the provisioner section?
