### ISSUE TITLE
Provide globally default Dockerfile template

### ISSUE THREAD

**Issue by LucaBernstein** [ansible-community/molecule#2653]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.9.6
  config file = /molecule/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Apr  7 2020, 12:12:05) [GCC 9.3.0]
molecule 3.0.3
   ansible==2.9.6 python==3.8
```

Molecule+Ansible installation method:

- Using the Docker image `quay.io/ansible/molecule:3.0.3`

# Desired Behavior

Hey all,

While I was configuring Molecule for our monolithic repository I encountered a behavior not expected.

I tried to move as much configuration to a central place as possible. So I created a `molecule-defaults` directory, [created a default molecule configuration there](https://github.com/ansible-community/molecule/issues/648#issuecomment-266888242).
So far, so good.

Now I also wanted to create a common Dockefile, as for many roles in the repository this is the same and naturally I want to avoid redundancy.

So what I expected was, that in the provisoner section of the Molecule config I can provide the parameter dockerfile with an absolute path like so:

```
platforms:
  - name: molecule_instance_debian_10
    image: debian:10
    dockerfile: /molecule/molecule-defaults/Dockerfile.j2
    pre_build_image: false
```

Unfortunately this seems not to work, I looked in the code and found that snippet:
https://github.com/ansible-community/molecule/blob/5a18f5a3df182ae98c8f6ac716992e28d72437b3/molecule/provisioner/ansible/playbooks/docker/create.yml#L28-L32

And indeed, if I provide an extra ENV var `MOLECULE_SCENARIO_DIRECTORY: "/"` this works again, as my absolute path can be resolved again.
Though I do not want to break other behavior, as of now I do not know if the `molecule_scenario_directory` is used otherwise or whether I could still override the Dockerfile based on custom role configuration.

Hope you can help me out here.

If you want I can draft a PR.

Thanks a lot in advance!

Luca

**Comment by ssbarnea** [comment]
I think that you easily re-use the configuration loading to achieve this: ability to tell molecule to use the in-config dockerfile instead of the embedded on, and you would even have to touch the scenario definition to do it. Probably should be implementable in 2-3 lines of code. 

Mainly you need to make molecule look first of `.config/molecule/Dockerfile.j2` presence and use that when existing. The config can be hosted in your repo, it does take precedence over user home.  I would support a PR doing this.

**Comment by LucaBernstein** [comment]
Maybe we could also simply work with a case distinction for absolute and relative paths based on an initial `/`.

**Comment by ssbarnea** [comment]
Recent versions of molecule have embedded Dockerfile. I am going to close this as you either use the embedded file or you are in control of setting the path to the file.
