### ISSUE TITLE
Quay.io Dockerfile stale "latest" tag

### ISSUE THREAD

**Issue by kevingentile** [ansible-community/molecule#2656]
# Issue Type

- Bug report

# Desired Behavior

Pulling `quay.io/ansible/molecule:latest` provides a docker image with the latest version of molecule 

# Actual Behaviour

Latest tag is an older version of molecule.

```
docker run -it quay.io/ansible/molecule:latest molecule --version
molecule, version 2.20.0.0a3.dev12
```

**Comment by radek-sprta** [comment]
This still a thing. Wouldn't tagging new builds with latest in the CI solve this?

**Comment by kevingentile** [comment]
Looks like the Github workflow is missing the tox `build-containers` step. I've added a minimal PR, but will require a login step.

**Comment by ssbarnea** [comment]
Containers are not published by us and instead are build directly by quay when we create a new tag. Sadly they do not provide any feature to move the latest tag.

I am going to close this ticket as it is outside our power to solve it.
