### ISSUE TITLE
EL 8 docs specify wrong dependency for libselinux-python (should be python3-libselinux)

### ISSUE THREAD

**Issue by jeffcpullen** [ansible-community/molecule#2658]
# Issue Type

- Bug report

# Desired Behavior

Following installation docs for EL 8 distro it says to install libselinux-python, but thats not available. Instead it should point to python3-libselinux.

# Actual Behaviour

Following the installation guide on RHEL 8
```
$ sudo yum install -y gcc python3-pip python3-devel openssl-devel libselinux-python
Updating Subscription Management repositories.
Last metadata expiration check: 0:31:57 ago on Sat 18 Apr 2020 10:49:48 AM EDT.
No match for argument: libselinux-python
Error: Unable to find a match: libselinux-python
```

**Comment by ktdreyer** [comment]
We can close this now that https://github.com/ansible-community/molecule/pull/2661 is merged
