### ISSUE TITLE
"molecule.yml as only config required" support for plugins (molecule-hetznercloud)

### ISSUE THREAD

**Issue by decentral1se** [ansible-community/molecule#2671]
# Issue Type

- Feature request

# Molecule and Ansible details

- Latest

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

I'm migrating a lot of roles to Molecule 3.0 and it's quite a piece of work. That's fine and I'm glad to be able to do it. However, it got me thinking, it would be **excellent** if I only had to migrate my `molecule.yml` and not the prepare/create/destroy etc. (there were changes in the plugin implementation).

I have no custom changes to the create/destroy/prepare yaml files whatsoever. I feel like I don't need to see them in the `molecule/default/` folder. If they weren't there, then I really wouldn't notice and I would have a lot less work to do.

This would upstream maintenance work into the plugin (for create/prepare/destroy/etc.) and make migration much easier (allowing more flexibility in the molecule.yml definitions because you only have to change one file now).

So, my request is, can we make it such that if you have no `create.yml` in your `molecule/default` folder, then molecule looks at your driver plugin and then does a lookup into the plugin directory path to run the default create/prepare/destroy/etc. You can always override.

**Comment by ssbarnea** [comment]
@decentral1se This is already true for at least docker and podman plugins and if I remember well creation of a new scenario will no longer create these playbooks. When the files are not on disk, molecule will look inside the driver and use the embedded version.

This is a great feature to have which improves UX for most users. Still, it makes life bit harder for power-users which may want/need to tune the playbooks, mainly because now they need to dig into the source code to and copy the embedded files.

I think that ideally we should add a switch to `init` that would enable creation of these files.

Also, I should remind you that the repo shared config is another way to minimize alterning of molecule.yml files.

I put a lot of work in this direction with v3 as I hate having to port configuration, I think we will be less likely to do similar refactorings in the future.

**Comment by decentral1se** [comment]
Oh nice but it is broken for molecule-hetznercloud unfortunately.

```
WARNING: Couldn't open molecule/default/create.yml - No such file or directory
WARNING: Couldn't open molecule/default/destroy.yml - No such file or directory
WARNING: Couldn't open molecule/default/playbook.yml - No such file or directory
WARNING: Couldn't open molecule/default/prepare.yml - No such file or directory
WARNING: Couldn't open molecule/default/tests/test_default.yml - No such file or directory
WARNING: Couldn't open molecule/default/verify.yml - No such file or directory
--> Scenario: 'default'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'default'
--> Action: 'destroy'
Skipping, destroy action has no playbook.
--> Scenario: 'default'
--> Action: 'syntax'
--> Sanity checks: 'hetznercloud'
    
    playbook: /foobar/roles/autonomic.add-users/molecule/default/converge.yml
--> Scenario: 'default'
--> Action: 'create'
Skipping, create action has no playbook.
--> Scenario: 'default'
--> Action: 'prepare'
Skipping, prepare playbook not configured.
--> Scenario: 'default'
--> Action: 'converge'
    
    PLAY [Converge] ****************************************************************
    
    TASK [Gathering Facts] *********************************************************
fatal: [autonomic.add-users-774]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname foobar: Name or service not known", "unreachable": true}
    
    PLAY RECAP *********************************************************************
    autonomic.add-users-774    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```

This can be patched in molecule itself or what is the procedure to include the molecule-hetznercloud plugin in this functionality?

**Comment by ssbarnea** [comment]
I do not remember how I implemented it, you need to dig a bit. Still, I would fully support an implementation that makes this default for all plugins. Maybe they could override it in the future, but I see no harm to assume it default.

I think there are few plugins that do not use playbooks for create/destroy, probably these are more problematic as you still want to call their internal implementation.

**Comment by decentral1se** [comment]
I __think__ it has to do with something like the change implemented in https://github.com/ansible-community/molecule/pull/2572 which supports plugin "embedded" playbooks? Still digging...

**Comment by decentral1se** [comment]
OK, the core drivers have bundled playbooks in core. See https://github.com/ansible-community/molecule/tree/master/molecule/provisioner/ansible/playbooks. Then the PR marked above looks into that directory to grab plays if the end-user does not supply them.

**Comment by decentral1se** [comment]
Ok, I just had to add a "playbooks" dir to my plugin implementation and bundle there.
