### ISSUE TITLE
Add molecule-hetznercloud to the default Dockerfile

### ISSUE THREAD

**Issue by decentral1se** [ansible-community/molecule#2673]
# Issue Type

- Feature request

# Molecule and Ansible details

- Latest

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Instead of having to `pip install molecule-hetznercloud`, I get it baked into the upstream docker image that is provided from the molecule project and my builds run faster. I guess all plugins that are maintained should be included. Up for it?

**Comment by ssbarnea** [comment]
Addressed via https://github.com/ansible-community/molecule/pull/2680
