### ISSUE TITLE
Remove sh package as a molecule dependency

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2678]
As we previously had some problems with `sh` library and today [a new release also broke us](https://github.com/amoffat/sh/issues/520), it is time to remove it as a dependency.

If someone makes a PR to remove sh and replace it with either an internal implementation or another library that is better maintained (test coverage and multiple maintainers), I will be very happy to fast-track it.

Related: https://github.com/ansible-community/molecule/issues/2676

**Comment by decentral1se** [comment]
Regression was handled in a timely manner, however.

> https://github.com/amoffat/sh/issues/520#issuecomment-620637323

**Comment by Yajo** [comment]
https://plumbum.readthedocs.io/ rocks :guitar:

**Comment by ssbarnea** [comment]
Plumbum seems nice but I did not test it yet. Also seems to be another project backed by a single developer, which worries me. I am more inclined to add some DIY code than ending up in the same place one year later. Still, no action will be taken unless we have a strong reason.

**Comment by greg-hellings** [comment]
I have had good luck with plumbum in the past, and it has been pretty solidly stable. But for the amount of calling that Molecule does, we can do this ourselves with popen.

**Comment by ssbarnea** [comment]
I started working on this during the weekend, implemention would count as major change which will impact plugins, so it will only go in in `3.2.0`.
