### ISSUE TITLE
proposal: discourage use of localhost instance with delegated scenarios

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2700]
In order to avoid accidents where running a molecule scenario would mess your development machine or where is effectively impossible to run molecule safely without changing the scenario, I would like to add a big warning when `instance: localhost` is found in `molecule.yml`.

I would like to suggest use of `instance: tester` as a generic name to define a space host that can be used for testing.

If we do this, it would be easy for developers to point `tester` to resolve to whatever machine they want, even localhost.

The whole idea is that anything else than localhost would be fine, but having a recommended name would make much easier to switch from one to another.

As molecule manages the inventory itself, we should continue to promote use of `hosts: all` in its testing playbooks, as `all` is supposed to resolve as all tested hosts, and it does not include `localhost`.

**Comment by ssbarnea** [comment]
Alternatively we could reuse the `instance` name which is also very popular due to our examples, but I am afraid is a bit confusing term.

**Comment by geerlingguy** [comment]
Interesting, I’ve never used localhost as a target/name in Molecule, but I can see a few cases where it might be okay. “Tester” doesn’t quite seem right, but maybe “test_instance” or the overloaded “instance” as a recommendation instead.

**Comment by ericsysmin** [comment]
I can see where someone may use "localhost" such as testing their modules, I will side with `test_instance`, or something more descriptive.

**Comment by ssbarnea** [comment]
I really want a simple and short name, mainly because is a hostname, and I do not want to have to type a lot to `ssh foo`. The easiest way would to use `instance` but i really like naming a variable object or obj, is redundant and confusing.
