### ISSUE TITLE
Add a relative path to the file in the gilt dependency

### ISSUE THREAD

**Issue by WeslyG** [ansible-community/molecule#2702]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/weslyg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/c/Users/WeslyG/git/work/java/.venv/lib/python3.8/site-packages/ansible
  executable location = /mnt/c/Users/WeslyG/git/work/java/.venv/bin/ansible
  python version = 3.8.2 (default, Apr  1 2020, 15:52:55) [GCC 9.3.0]
molecule 3.0.4
   ansible==2.9.9 python==3.8
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Having a lot of scenarios in testing, I would be comfortable if they all used the same gilt file to install dependencies. The most convenient way to do this is to use the relative path to the file. I see the solution in the form of this configuration.

```
dependency:
  name: gilt
  options:
    config: ../common/gilt.yml
```

**Comment by 1efty** [comment]
Just FYI Gilt has been removed from the codebase https://github.com/ansible-community/molecule/pull/2814

Not sure on anyone's appetite for back-porting this into the 2.20 or 3.03 branches.
