### ISSUE TITLE
Problem test molecule in MacOS

### ISSUE THREAD

**Issue by Tomelin** [ansible-community/molecule#2717]
Hi,

I have a problem with tests the molecule in my MacOS.

Confs by pip
pip freeze | grep docker
docker==4.2.1
docker-compose==1.26.0
docker-py==1.10.6
docker-pycreds==0.4.0
dockerpty==0.4.1

pip freeze | grep ansible
ansible==2.9.9
ansible-lint==4.2.0

pip freeze | grep molecule
molecule==3.0.4
molecule-azure==0.3

**molecule test**
--> Test matrix

└── default
    ├── dependency
    ├── lint
    ├── cleanup
    ├── destroy
    ├── syntax
    ├── create
    ├── prepare
    ├── converge
    ├── idempotence
    ├── side_effect
    ├── verify
    ├── cleanup
    └── destroy

--> Scenario: 'default'
--> Action: 'dependency'
Skipping, missing the requirements file.
Skipping, missing the requirements file.
--> Scenario: 'default'
--> Action: 'lint'
--> Lint is disabled.
--> Scenario: 'default'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'default'
--> Action: 'destroy'
--> Sanity checks: 'docker'

    PLAY [Destroy] *****************************************************************

    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=instance)

    **TASK [Wait for instance(s) deletion to complete] *******************************
    failed: [localhost] (item={'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_item_label': u'instance', u'ansible_job_id': u'735711355767.11734', 'failed': False, u'started': 1, 'changed': True, 'item': {'image': u'centos:7', 'name': u'instance'}, u'finished': 0, u'results_file': u'/Users/rafaeltomelin/.ansible_async/735711355767.11734', '_ansible_ignore_errors': None, '_ansible_no_log': False}) => {"ansible_job_id": "735711355767.11734", "attempts": 1, "changed": false, "finished": 1, "item": {"ansible_job_id": "735711355767.11734", "changed": true, "failed": false, "finished": 0, "item": {"image": "centos:7", "name": "instance"}, "results_file": "/Users/rafaeltomelin/.ansible_async/735711355767.11734", "started": 1}, "msg": "Failed to import docker or docker-py - cannot import name __version__. Try `pip install docker` or `pip install docker-py` (Python 2.6)"}**

    PLAY RECAP *********************************************************************
    localhost                  : ok=1    changed=1    unreachable=0    failed=1

What's the problem?

I removed and reinstall docker by pip, but not working.

**molecule drivers**
name
---------
delegated
docker
podman
vagrant

**molecule --version**
molecule 3.0.4
   ansible==2.9.6 python==3.8

**Comment by ssbarnea** [comment]
That is not a bug in molecule, is an ansible miss-configuration. My main dev box is  a MacOS on. A hint: try using the docker ansible module with ansible itself, use `connection: local`, use -vvv, ansible will show you that is using another python version than the one you used locally to install molecule.
