### ISSUE TITLE
Allow molecule testing to run natively under zuul

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2738]
In order to improve the UX when running molecule under Zuul CI, it would be useful if zuul can detect which test sequences are enabled and run each of them as a separated zuul task.

This would allow to easily create zuul jobs that run specific molecule scenarios, ones that would produce an output similar with command line usage.

Current use usually involves using tox to install molecule and using pytest-html to encapsulate execution of molecule and produce an ANSI-enable HTML report. This setup can be seen bit complex for many users.

In order to be able to implement this, zuul needs to ask molecule about which steps are setup in current test sequence, likely by calling molecule `matrix -s scenario_name`.

**Comment by cognifloyd** [comment]
Could zuul be informed about which scenario is running similar to the Github/Travis/GitLab implementation in #2967 ?

**Comment by ssbarnea** [comment]
That is harder to implement if we want molecule to appear more natively integrated into zuul as we need to add some ansible module that returns the steps needed to run for particular scenario and make zuul loop over them using ansible. There are lots of issues around, especially as logic around what happens when a step fails, molecule itself knows to run destroy to perform cleanup but zuul would likely not.

For the moment I am focusing on producing HTML reports with molecule 3.2, a feature already present on master branch. If these are well visible under zuul it may be enough for a while.

This being said, if someone wants to start working on this, I will be more than happy to assist and facilitate any kind of molecule internal changes that could make it easier.

**Comment by decentral1se** [comment]
Is this still relevant re: https://github.com/ansible-community/molecule/pull/2789?

**Comment by cognifloyd** [comment]
It only matters if others are using ansible under Zuul. Molecule itself doesn't need it, so it is very unlikely to get much effort from molecule devs. (my opinion - I can't speak for any official molecule devs)
