### ISSUE TITLE
Patch-level breaking changes

### ISSUE THREAD

**Issue by greg-hellings** [ansible-community/molecule#2743]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.9.10
molecule 3.0.5
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

Patch version updates should not be incompatible with other releases in the minor release stream.

Error message:

```
  msg: 'Unexpected templating type error occurred on ({{ molecule_yml.platforms | molecule_get_docker_networks }}): get_docker_networks() missing 1 required positional argument: ''state'''
```

# Actual Behaviour

0ed6809e196e97b4906549209fb25ca5b3f1bab2 introduce a breaking change to Molecule with the 3.0.5 release. Previous playbooks which ran fine against 3.0.4 now failed while provisioning their Docker target. Since there does not appear to be any way that the Ansible default provision/destroy code is deployed with Molecule in a manner that allows it to be updated in the future, this represents a problem. New scenarios will, obviously, get the new version of the create.yml but existing changes will not.

Please, either do not introduce changes that break the code, or move to a model of distributing the default create/destroy code as a role or collection that can be updated when Molecule is updated.

For our project, we have moved the provisioning of resources with Molecule into a collection and then just rely on that collection and role so that when changes like this come along our code is successful. You can find our collection's role, here: https://github.com/oasis-roles/ansible_collection_system/tree/master/roles/molecule_docker_ci and see it in use in various scenarios throughout the collection.

This particular bug was fixed by https://github.com/oasis-roles/ansible_collection_system/commit/7bc3d63a023c7f7fee21e880b0245d865da5e7f9 derived from the molecule changeset that introduced the break.

**Comment by duck-rh** [comment]
I just fell into this problem because we use custom templates. I believe template functions should be considered as API. The distribution model would not improve this situation.

**Comment by ssbarnea** [comment]
I agree but there is nothing I know to be able to do to prevent it. Makes sense to close it but if you know a way to prevent making patch-version release that updates the API, I will be very happy to see it.

**Comment by duck-rh** [comment]
@ssbarnea yes, you can postpone it to a non-patch level release. You can also document it clearly as API changes, that would really help.

**Comment by greg-hellings** [comment]
It would require either creating a maintenance branch for the current work on 3.0.x and only merge non-breaking changes into it, which allows 3.1 to be developed on the main branch. Or you would have to just monitor the status of the main development branch and bump to 3.1 as soon as a break comes along. Even if it wasn't on your roadmap to release it now. (Another choice is just to hold all PRs that would break for when you're ready to bump minor version)

One requires extra maintenance, the other extra vigilance. Neither is super easy to manage, especially depending on how the API portion is defined.

**Comment by ssbarnea** [comment]
With the current level of help I get from others, I think the only option would to get used to the idea that a new release could break anything. Based on how risked adverted is each user, you can decide for a full ping or a major version pinning.
