### ISSUE TITLE
Can't install Molecule with latest Ansible devel releases (2.11)

### ISSUE THREAD

**Issue by geerlingguy** [ansible-community/molecule#2757]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version
ansible-base-2.11.0.dev0

$ molecule --version
3.0.6
```

Molecule installation method (one of):

```
pip install molecule
```

Ansible installation method (one of):

```
pip uninstall -y ansible
pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check
```

# Desired Behavior

Molecule should be able to run with Ansible installed from devel.

# Actual Behaviour

Molecule seems to be failing with:

```
pkg_resources.DistributionNotFound: The 'ansible' distribution was not found and is required by the application
```

The problem here is that if I install Ansible at devel first, then install Molecule via pip, Ansible 2.9.10 is installed on top of the ansible-base devel install, and that breaks Ansible too.

**Comment by geerlingguy** [comment]
Related issue: https://github.com/ansible-collections/community.kubernetes/issues/167

**Comment by geerlingguy** [comment]
It looks like even with ansible base 2.10 stable, I can't get Molecule to detect that ansible is installed:

Install with: `pip install https://github.com/ansible/ansible/archive/stable-2.10.tar.gz --disable-pip-version-check`

Get error when running `molecule`:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.8/x64/bin/molecule", line 5, in <module>
    from molecule.__main__ import main
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/molecule/__main__.py", line 22, in <module>
    from molecule.shell import main
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/molecule/shell.py", line 90, in <module>
    prog_name="molecule", version=molecule.__version__, message=_version_string()
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/molecule/shell.py", line 55, in _version_string
    pkg_resources.get_distribution("ansible").version,
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pkg_resources/__init__.py", line 482, in get_distribution
    dist = get_provider(dist)
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pkg_resources/__init__.py", line 358, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ansible' distribution was not found and is required by the application
##[error]Process completed with exit code 1.
```

**Comment by geerlingguy** [comment]
Even installing `ansible-base` from PyPi didn't seem to work (`pip install --pre ansible-base`).

**Comment by btravouillon** [comment]
molecule requires ansible, which might become an issue when the Ansible project will definitely stop to ship the ansible package in favor of ansible-base. As far as I know, there is no way to require one or the other package (ansible OR ansible-base) in setup.cfg (Requires-Dist).

While it does not work with devel, you should be able to install the latest ansible pre-release from PyPi, then molecule (w/ patch from #2777), without downgrading your environment to ansible 2.9.x.

```
(venv) $ pip install --pre ansible
[...]
Installing collected packages: ansible-base, ansible
Successfully installed ansible-2.10.0a8 ansible-base-2.10.0rc4
(venv) $ pip install git+https://github.com/btravouillon/molecule@fix/issues/2757
[...]
Installing collected packages: molecule
Successfully installed molecule-3.0.5.dev64
(venv) $ molecule --version
molecule 3.0.5.dev64
   ansible==2.10.0rc4 python==3.7
```

_Note: I can't explain why the molecule release is 3.0.5.dev64 while I branched from `master`._

**Comment by ssbarnea** [comment]
It is no longer possible to install "ansible" package from source using pip since it became "ansible-base" and AFAIK, the core team has no clear plans on making this possible.

While this is a real issue for testing molecule we cannot do anything about it. I would suggest poking  "Ansible Community Distribution" instead.
