### ISSUE TITLE
Molecule can't access group_vars/all/ and other global information

### ISSUE THREAD

**Issue by AquaL1te** [ansible-community/molecule#2761]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 29 2020, 00:00:00) [GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
molecule 3.0.4
   ansible==2.9.10 python==3.8
```

Molecule installation method (one of):

- OS package: python3-molecule-3.0.4-1.fc32.noarch

Ansible installation method (one of):

- OS package: ansible-2.9.10-1.fc32.noarch

# Desired Behavior

Below is a snippet of my Ansible directory structure:
```
.
├── ansible.cfg
├── group_vars
│   ├── all
│   │   ├── main.yml
│   │   ├── vault_crypto.yml
│   │   └── vault_password.yml
│   ├── researchproject.yml
│   └── workstation.yml
├── hosts.cfg
├── host_vars
│   ├── rp1.yml
│   ├── rp2.yml
│   ├── rp3.yml
│   ├── ws1.yml
│   ├── ws2.yml
│   └── ws3.yml
├── lookup_plugins
│   ├── neo.py
│   └── __pycache__
│       └── neo.cpython-38.pyc
├── molecule
│   └── default
│       ├── converge.yml
│       ├── molecule.yml
│       └── verify.yml
├── README.md
├── roles
│   ├── git
│   │   ├── tasks
│   │   └── vars
├── site.yml
├── todo.txt
└── vault-pass

77 directories, 22 files
```

Which won't allow me to initiate role tests with Molecule from a central location, i.e. from the Ansible playbook root directory. I need to configure Molecule in each role, e.g. `roles/git/`. And when I do, I cannot access my `lookup_plugins/neo.py` or `group_vars/all/` directory containing global variables. Which my roles depend on. Therefore, I need to copy variables and files into all my roles/ in order to make them work. I find it hard to believe that this is intended by design, because it's a best practice to not repeat yourself. Managing multiple identical var files, and keep them in sync, is not sufficient. It would also be strange if `group_vars/all/` is something that's unsupported by Molecule. I believe it's a convenient way to manage global vars.

Would it be possible to run a playbook in Molecule, the same as I would with `ansible-playbook`? And thus not limited to single roles which don't access e.g. `group_vars/all/`? **Or**, make a single role access the `group_vars/all/` and `lookup_plugins` directories, such that they don't run into missing information. That last one would of course already solve the whole situation. Because the core problem is that my roles depend on this globally available information, which i don't want to duplicate, unless there is a really good reason for that.

**Comment by ssbarnea** [comment]
Molecule manages inventory by itself, it does not make use of your inventory. It is test tool aimed to isolate test environment from your inventory. You are supposed to define the inventory in your molecule.yml, where you can also defined groups and other settings.
