### ISSUE TITLE
Idempotency on --debug doesn't help much

### ISSUE THREAD

**Issue by Yajo** [ansible-community/molecule#2763]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.9.9
  config file = /var/home/yajo/mydevel/mando/ansible.cfg
  configured module search path = ['/var/home/yajo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/home/yajo/mydevel/mando/.venv/lib64/python3.8/site-packages/ansible
  executable location = /var/home/yajo/mydevel/mando/.venv/bin/ansible
  python version = 3.8.3 (default, May 29 2020, 00:00:00) [GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
molecule 3.0.4
   ansible==2.9.9 python==3.8
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

When idempotency fails with `--debug`, it should display the full log of the failed tasks.

# Actual Behaviour

I have some idempotency failure, but this is what `molecule --debug test --all` prints:

```
ERROR: Idempotence test failed because of the following tasks:
* [basic] => base : start traefik container
* [basic] => nextcloud : start nextcloud container
```

Not much helpful to debug...

**Comment by ssbarnea** [comment]
Please use forum for support https://github.com/ansible-community/molecule/discussions

**Comment by Yajo** [comment]
Thank you but this is a bug... When passing `--debug`, molecule should print the failed idempotency tasks with `-vvv --diff`
