### ISSUE TITLE
💖 Molecule is looking for additional maintainers

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2764]
No, I am not leaving anywhere but I want to state that I am seriously looking into enlarging the pool of people that can perform maintenance on molecule itself.

If you are interested please let me know, the most important part is ability and willingness to review PRs and issues.

Ideally no change should be merged without a peer review and sadly during the last few months I was not able to fully respect this as I struggled to get reviews from others. An outcome is that I stopped working on any bugfixes and only reviewed code from others.

I am open to give review permissions quite soon but I also want to mention that I will start removing people with core rights that failed to performed any reviews for a longer period of time.

IMHO, a core developer has a moral duty of trying to review incoming changes. It is perfectly normal for them to remove themself from reviews where they do not know how to review but that does not mean they should be totally passive forever. By doing this we should also make it much easier to pick reviewers, as the dropdown list will have less "ghosts" ;)

Please state your interest here and do not forget that you can already perform reviews, even if you where not invited yet (remember to use the review button from file tab, just a PR comment does not appear as review).

**Comment by ldarmbuster** [comment]
I'd like to volunteer to help with reviewing PRs and issues. I don't have a pure developer background, but I know Python and Ansible and use Molecule almost daily.

**Comment by greg-hellings** [comment]
I would be happy to help with reviews and maintenance work. I'm in and out of Molecule on a daily basis as day.job is Molecule scenarios for Ansible collections

**Comment by alainchiasson** [comment]
I have been using Molecule on and off since the 2.x switch, and push it anywhere I can. I would love to help out.

**Comment by eighty20results** [comment]
I'd be very interested in helping out. Been developing with/for Python, Ansible and Molecule for a little while, for the computer manufacturer I work for and am doing daily code review in that context.

**Comment by SteveFroehlich** [comment]
Making an on ramp to being a maintainer might be helpful. For example just creating a new label, like Mozilla does with [good first bug](https://wiki.mozilla.org/Good_first_bug), could make it a lot easier for people to know where to start.

**Comment by ssbarnea** [comment]
I did not seen much success in using a good-first-bug label on other projects, most users lost interest before making a PR and the only result was cluttering the project with extra labels, not to mention that this prevented more senior people from fixing these issues.

If someone wants to help they have two options: randomly pick something and raise a PR or engaging on #ansible-molecule freenode channel. On irc it is much likely to give an instant answer on what can be done to help. Also the channel received notifications regarding any new open issue or pull-request.

**Comment by hluaces** [comment]
I could help if needed. 

I don't have a full developer background, but I work with Ansible + Molecule daily and I've done a few custom modules for Ansible as well.

**Comment by ssbarnea** [comment]
@hluaces Thanks. Even watching what happens and reviewing changes can very extremely valuable. Some PRs may need local checkout and manual testing. It is a misconception that only python developers can help.

**Comment by hluaces** [comment]
@ssbarnea great, count me in.

**Comment by IlyesSemlali** [comment]
Hi @ssbarnea, I'm also volunteer, I can spend at least half an hour a day, taking issues and reviewing code. I've been working on a fix for the 2.20 version, but it was the time the 3.0 version got released.

**Comment by decentral1se** [comment]
Pop by on `#ansible-molecule` IRC channel @ freenode folks if you want to discuss / organise / whatever to get things done :fireworks:

**Comment by sobedrinker42** [comment]
I'll be happy to contribute.  limited with python knowledge but work with molecule/ansible daily.
