### ISSUE TITLE
Support tasks tagged molecule-idempotence-nofail, similar to molecule-idempotence-notest

### ISSUE THREAD

**Issue by nre-ableton** [ansible-community/molecule#2765]
# Proposal: <proposal name>

*Author*: Nik Reiman <@nre-ableton> IRC: N/A

*Date*: 2020/07/28

- Status: New
- Proposal type: Enhancement
- Estimated time to implement: Unknown

## Motivation

I would like to use Molecule to test roles which have tasks that are not idempotent, but also not have the idempotency task fail or be required to mark such tasks with the `changed_when: false` attribute.

A bit more background -- I have some Ansible roles which install and configure rather complex services (in this case, Jenkins and Jenkins build nodes via Swarm Client). Before these roles can be safely run, these services must be stopped. Then, several tasks are run to configure the host, and then the service is restarted. It is impossible (or rather, extremely difficult and/or very impractical) to determine idempotency before shutting down the service, and therefore the most practical way to proceed is to stop the service, run the tasks, and then start it up again at the end of the role.

Ideally, I want molecule to alert me when the _intermediate_ tasks are non-idempotent. Therefore, disabling the idempotency check entirely is not a desirable solution. Also, I need molecule to actually run the service tasks, so `molecule-idempotence-notest` will not work since this skips them altogether. Ideally, I wish I could tag such tasks with a tag named something like `molecule-idempotence-nofail`. Such tasks should be run by molecule, but the idempotency check will not fail if molecule sees that they have changed the system state.

I'm not sure how difficult or practical this will be to implement, since I've not looked into the molecule codebase at all. If this feature is not desired by the community or would be very hard to implement , I'll close this issue. If it is easy to moderately hard to implement, then I'll take a look at the code and see if I can come up with a PR.

### Problems

What problems exist that this proposal will solve?

- Allowing tasks which are known to change system state to be run, and not fail idempotency tests

## Solution proposal

Unknown

## Dependencies (optional)

N/A

## Testing (optional)

I'm assuming that test cases would be fairly trivial to implement for such a feature.

## Documentation (optional)

Ideally this should be documented alongside `molecule-idempotence-notest` [here](https://molecule.readthedocs.io/en/latest/configuration.html#molecule.provisioner.ansible.Ansible).

## Anything else?

I'm relatively new to molecule and haven't contributed before. Apologies for my n00b-ness. 😅

**Comment by ssbarnea** [comment]
I am closing this ticket as this is an unlikely use-case and no is expected. Still, keep in mind that a closed ticket does not mean a PR would not not be welcomed, it only means to not expect anyone else to implement it for you.

**Comment by greg-hellings** [comment]
Oh this is a feature I would love to have. I've toyed with the idea of adding a flag to the molecule.yml to just completely skip idempotence checking altogether. I've settled on just adding "changed_when: false" to tasks that trigger problems, but sometimes that's just not appropriate. Most common times I have this issue is with calls to tempfile. Sometimes command/shell as well, depending on what they're doing.

**Comment by ssbarnea** [comment]
@greg-hellings I did the same. I think is perfectly fine to make use of `changed_when`. Even gathering facts about a host does change things on the host (temporary files), the old observer conundrum. You cannot do anything without affecting the state of the observed, it was already proved.

This means that it is up to the playbook writer to decide when a change counts towards altering the state of the targer machine or not. IMHO, creating (small) temp files does not. Getting idempotence right is one of the harder to achieve goals with ansible and authors should think about overall result. Obviously that if your code restarts a service each time it runs, without good reasons, it means it should fail idempotence. Still, if you write a role that accepts a `force_restart` argument, this is not expected to pass an indempotence test and that is easy to bypass by rewriting the test sequence.

**Comment by greg-hellings** [comment]
@ssbarnea Indeed. I have a role whose sole purpose is to reboot a machine and wait for it to come up. Obviously this fails idempotence check every time! It would be nice to have a way to nuke checking for idempotence specifically for the "reboot" call. Or to just skip the idempotence check every time that role is run.

**Comment by nre-ableton** [comment]
> @greg-hellings I did the same. I think is perfectly fine to make use of `changed_when`. Even gathering facts about a host does change things on the host (temporary files), the old observer conundrum. You cannot do anything without affecting the state of the observed, it was already proved.

I disagree with this statement a bit.. basically it is saying that an action which _does_ change state on the host should be ignored when the nature of that change is inconvenient in this specific case. :smile: Anyways, it's more of a philosophical distinction I suppose.

@greg-hellings If you would like to team up to solve this issue, I'd be more than happy to do that! My only shortcoming is that I'm wholly unfamiliar with the molecule codebase, so I'm not even sure where to start looking to make such a change.

**Comment by sjpb** [comment]
Interesting. Found this issue, thought "oh `molecule-idempotence-notest` will solve it", then found it skips the tasks entirely! My usecase - which can't be that uncommon? - is that I'm creating a tempfile and doing stuff with it. So that isn't idempotent as the tempfile is different everytime (and it needs to be unique, in this case, so I don't want to hard-code it) but I want molecule to not fail! Use of `changed_when` is maybe philosophical but it doesn't seem right to have ansible mark this as no-change **in the real environment** just because of a testing limitation.
