### ISSUE TITLE
Provide mechanism to exclude execution steps

### ISSUE THREAD

**Issue by greg-hellings** [ansible-community/molecule#2766]
# Issue Type

- Feature request

# Desired Behavior

Currently, if you want to run a custom sequence for a command, you must specify the FULL sequence. But if, for instance, you just want to exclude one step, that should be possible.

Some steps are easy - if you don't want to prepare or cleanup, just don't write a playbook for that. Don't provide unit tests, etc. But occasionally there is a role that has other conditions and should skip one of the other stages. There ought to be a way to say, "Run everything as normal EXCEPT for <stage>"

My particular use case, I have one or two roles that simply cannot pass idempotence because the action they take is inherently not idempotent. E.g. a reboot-wait role. Or a role specifically designed to update packages which could, theoretically, have different results on two consecutive runs.

For roles like those I would like to say, "Just don't run idempotence" rather than have to specify a fully custom sequence for test.

I'm willing to work on a PR if this is desirable and we have a reasonable mechanism proposed for how to specify exclusions.

**Comment by decentral1se** [comment]
> I'm willing to work on a PR if this is desirable and we have a reasonable mechanism proposed for how to specify exclusions.

Yes, please go for it. I guess some sort of exclude list or inverting how the current "list all first and comment one out in the molecule.yml" approach would be good. Ideally, we wouldn't break existing configs. Would be great to have something more convenient for this.

**Comment by ssbarnea** [comment]
Closing as wontfix due to lack of traction. I should mention that we will not refuse a PR that adds this feature but we do not plan to implement it ourselves, especially because it is possible to customize the list of steps to run, which is sorting this issue, at least partially.
