### ISSUE TITLE
Idempotence test fails on... gathering facts?

### ISSUE THREAD

**Issue by MetallDoktor** [ansible-community/molecule#2774]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version

ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxxxxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxxxxxxx/molecule/molecule-venv/lib/python3.8/site-packages/ansible
  executable location = /home/xxxxxxxx/molecule/molecule-venv/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
molecule 3.0.6
   ansible==2.9.11 python==3.8
```

Molecule installation method:

- pip

Ansible installation method:

- pip

Linters or test runners used:
```
yamllint
ansible-lint
flake8
```

# Desired Behaviour

I am developing an Ansible role with Molecule through the Docker driver. I managed to get all my tasks idempotent so the idempotence step should be passed without any problems or errors.

# Actual Behaviour

However, here is what I get:

![image](https://user-images.githubusercontent.com/33860184/89299872-006c4c00-d670-11ea-97f7-0eb8ec116b28.png)

But the problem is not about one of my tasks because I can see this with --debug option...:

![OpenedWithImage](https://user-images.githubusercontent.com/33860184/89300497-fdbe2680-d670-11ea-9837-35e10000a6c0.png)

... and this without it:

![image](https://user-images.githubusercontent.com/33860184/89303253-9c985200-d674-11ea-9cb9-92365ee62567.png)

All other tasks are "ok", neither "failed" nor "changed". Couldn't find anything useful about it. I could disable idempotence check in test_sequence, of course - I mean, as far as I can see, the role is idempotent after all - but it would be great to know why is this happening and could it be resolved.

**Comment by btravouillon** [comment]
Can you share a reproducer?

**Comment by MetallDoktor** [comment]
Greetings! I'm sorry, but what do you mean by "reproducer"? Never came across this and Google/Molecule docs didn't help much. I mean, I know what this means in general (at least, I believe I know), but fail to see what this means in terms of Molecule.

**Comment by btravouillon** [comment]
Can you share a role with molecule tests we could run to reproduce your issue?

**Comment by MetallDoktor** [comment]
Sorry for the delay. Here it is. I had to redact some sensible information, but it should not bring any troubles: the role is fine and the bug still can be reproduced.

[cuckoo-sandbox.zip](https://github.com/ansible-community/molecule/files/5084255/cuckoo-sandbox.zip)

**Comment by changsijay** [comment]
met same issue here, even tried ansible with options `vvv` it only shows

```
--> Scenario: 'default'
--> Action: 'idempotence'
ERROR: ansible-playbook 2.10.1
```

**Comment by ssbarnea** [comment]
This seems more like a support thing that should go to https://github.com/ansible-community/molecule/discussions

**Comment by changsijay** [comment]
Dont know why closeed it, It failed without any clear message and also nothing failed.

**Comment by Hendrik44** [comment]
I have this issue too and in one role i was able to fix it by having no tags inside a block and add the molecule-no-test tag to the block and not to every task inside the block. 

But now i have another role where it fails too but in this role i dont have such a skip tag.This issue should be reopen until there is a workaround or fix for this issue.

My setup: Ansible versions up to 2.9.15 and with molecule 3.1.5.
