### ISSUE TITLE
Delegated driver inventory refresh in a play

### ISSUE THREAD

**Issue by dmlb2000** [ansible-community/molecule#2780]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible 2.9.12
  config file = None
  configured module search path = ['/home/dmlb2000/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dmlb2000/.virtualenvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/dmlb2000/.virtualenvs/ansible/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
molecule 3.0.6
   ansible==2.9.12 python==3.6
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

I'm using a delegated scenario driver with a cloud like environment. I'm creating the systems I want to test, then logging into them to do some initial configurations before I run a converge on the role. I was hoping to perform both of these actions in the `create.yml` playbook. Though the inventory doesn't seem to refresh properly, I'm setting the `inventory_conf` and creating the `molecule_instance_config` file. The ansible meta inventory refresh task doesn't see to help.

However, the inventory generated this way only gets recreated when molecule is run and I don't know of a way to execute a molecule inventory refresh from a play.

# Actual Behaviour

I end up running `molecule create` twice, it fails the first time unable to connect to the inventory host in the second play.

**Comment by dmlb2000** [comment]
I did create a `prepare.yml` and moved some of the steps there to get the pipeline working. Though the inventory refresh task after creating the `instance_config.yml` would be a good feature.

**Comment by ssbarnea** [comment]
By design inventory is altered by create and destroy playbooks and I did no see any real use case for other than this.

I would recommend using discussions for things that are not a clear bug.
