### ISSUE TITLE
tox tests fail on clean checkout

### ISSUE THREAD

**Issue by greg-hellings** [ansible-community/molecule#2782]
# Issue Type

- Bug report

# Molecule and Ansible details

```
git master branch
```

Molecule installation method (one of):

- source

Ansible installation method (one of):

- source

Detail any linters or test runners used:

tox -e py38-ansible29-functional

# Desired Behavior

Tests should all pass

# Actual Behaviour

Some of the tests fail because they are incorrectly creating OpenStack based scenarios instead of docker/podman based scenarios.

```
========================= 4 failed, 33 passed, 2 skipped, 33 deselected in 938.37s (0:15:38) =========================
ERROR: InvocationError for command /home/ghelling/src/molecule/.tox/py38-ansible29-functional/bin/python -m pytest (exited with code 1)
```

Specifically these tests are failing:
test_command_init_role[docker]
test_command_init_role[podman]
test_command_init_scenario[docker]
test_command_init_scenario[podman]

They are all failing with output similar to this:

```
------------------------------------------------ Captured stdout call ------------------------------------------------
    --> Initializing new role test-init...
    Initialized role in /tmp/pytest-of-ghelling/pytest-0/test_command_init_scenario_pod0/XOCKT/test-init successfully.
    
    --> Initializing new scenario test-scenario...
    Initialized scenario in /tmp/pytest-of-ghelling/pytest-0/test_command_init_scenario_pod0/XOCKT/test-init/molecule/test-scenario successfully.
    
    ---
    driver:
      name: openstack
    platforms:
      - name: test-test-init
    
    
------------------------------------------------ Captured stderr call ------------------------------------------------
ERROR: Failed to pre-validate.

{'driver': [{'name': ['unallowed value openstack']}]}
```

**Comment by greg-hellings** [comment]
Going out on a limb here - I have a custom Ansible role skeleton directory defined in my ~/.ansible.cfg file. This includes both docker and openstack scenarios.

The test should be explicit about what skeleton to use.

**Comment by geerlingguy** [comment]
I haven't used tox at all, so I might not be that well-versed in what's going on with the scaffolding, but it seems that's where the error lies.
