### ISSUE TITLE
Odd behavior with Ansible 2.10 in a tox-created virtualenv

### ISSUE THREAD

**Issue by greg-hellings** [ansible-community/molecule#2853]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version

ansible 2.10.1
  config file = /home/greg/.ansible.cfg
  configured module search path = ['/home/greg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/greg/src/ansible_collections/devroles/min_reproducer/.tox/py38/lib/python3.8/site-packages/ansible
  executable location = /home/greg/src/ansible_collections/devroles/min_reproducer/.tox/py38/bin/ansible
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
molecule 3.0.8
   ansible==2.10.1 python==3.8
```

Molecule installation method (one of):

- tox

Ansible installation method (one of):

- tox

Detail any linters or test runners used:

# Desired Behavior

Running molecule with Ansible 2.10 from a tox-crafted virtualenv works as expected

# Actual Behaviour

When executing `molecule test` from inside of a tox run, with Ansible >= 2.10, odd behavior with molecule's interaction with pkg\_resources leads to weird behavior. Details can be found at https://github.com/greg-hellings/min_reproducer, but the crux of the result is that I get this warning message from Ansible, resulting in failed Molecule execution:

```
[WARNING]: Skipping plugin (/home/greg/src/ansible_collections/devroles/min_rep
roducer/.tox/py38/lib/python3.8/site-
packages/molecule/provisioner/ansible/plugins/filter/molecule_core.py) as it
seems to be invalid: The 'ansible_base' distribution was not found and is
required by the application
```

Activating the tox-created virtualenv and running molecule manually results in the same warning/error.

Running from a manually created virtualenv does not result in the error, and molecule behaves properly. But, for the life of me, I cannot figure out if there is something in my tox.ini, if there's something in Molecule, if it's something related to Ansible (runs fine if I restrict ansible<2.10 in tox.ini), or if it is something odd with how tox creates a virtualenv. I'm happy to shift the reporting further upstream if I can figure out a minimum reproducer case for another project.

**Comment by ssbarnea** [comment]
That is one of the reasons why I went towards removing all molecule plugins/filters, something already done in master branch.

Please check if you can reproduce with `molecule>=3.1.0a1` and delegated driver. If you can reopen it. If it does happen only with another driver, we need to open a ticket with that driver.

**Comment by greg-hellings** [comment]
3.1.0a2 does resolve the problem. I'll look for the 3.1.0 release. Thanks!
