### ISSUE TITLE
ansible_user is undefined

### ISSUE THREAD

**Issue by nre-ableton** [ansible-community/molecule#2862]
I have a basic task which has a condition that examines `ansible_user`. When running this task from molecule, I get an error:

```
fatal: [instance]: FAILED! => {"msg": "The conditional check 'jenkins_user != ansible_user' failed. The error was: error while evaluating conditional (jenkins_user != ansible_user): 'ansible_user' is undefined\n\nThe error appears to be in '/home/nre/Code/project/tasks/configure-user.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create Jenkins user\n  ^ here\n"}
```

When I run the playbook from Ansible itself, it works fine. Am I missing something super obvious here?

# Molecule and Ansible details

```
ansible 2.9.11
  config file = None
  configured module search path = ['/home/nre/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nre/Code/caches/venv/lib/python3.8/site-packages/ansible
  executable location = /home/nre/Code/caches/venv/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
molecule 3.0.6```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

**Comment by larmbuster** [comment]
Have you tried different quoting with the conditional like this?
'ansible_user != "jenkins_user"'

**Comment by nre-ableton** [comment]
So it turns out that `ansible_user` is a connection variable, and is only supplied when Ansible is executing a specific target. If molecule isn't supplied a target, then it won't have this variable.

FWIW, I solved this by changing the condition to `when: not (ansible_user is defined and jenkins_user == ansible_user)`.
