### ISSUE TITLE
Molecule won't start Docker container - fatal: [centos8]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure ...

### ISSUE THREAD

**Issue by shanxijie** [ansible-community/molecule#2870]
When run molecule test, I got the following error:
fatal: [centos8]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1602159340.7644343-138649041382011 `\" && echo ansible-tmp-1602159340.7644343-138649041382011=\"` echo ~/.ansible/tmp/ansible-tmp-1602159340 exited with result 1", "unreachable": true}

After this failure, "docker ps -a" return nothing, which means no docker containers were started. 

My platform is wsl 2 on Window 10
coomand "docker run hello-world" indicates the docker is working properly

the versions of pip and python are:  Python 3.8.5 and pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
the molecule.yml:
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
provisioner:
  name: ansible
verifier:
  name: ansible

...

**Comment by larmbuster** [comment]
Can you try doing `molecule create` to create a docker instance and then `molecule list` to display the instance? You could also try going through the step by step test sequence commands listed in the "Run test sequence commands" section of the [Getting Started Guide](https://molecule.readthedocs.io/en/latest/getting-started.html).

**Comment by shanxijie** [comment]
@larmbuster, the issue was resolved. skipping step create was caused by the states in molecule cache. after reset, everything is working now. Thanks for your helps!

**Comment by larmbuster** [comment]
@shanxijie Glad to hear you were able to figure it out!

**Comment by rcooper85** [comment]
Hi, i'm getting the exact same error message using molecule version 2.20.2. 

If I run, molecule converge, molecule verify, molecule destroy separately, it works fine. I only seem to get the UNREACHABLE error when I use the molecule test command. I have nothing within my ~/.cache/molecule directory either.
