### ISSUE TITLE
Removal of molecule filters

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2872]
[Molecule ansible filters](https://github.com/ansible-community/molecule/blob/master/molecule/provisioner/ansible/plugins/filter/molecule_core.py) are moved are **now moved to a standalone collection** https://galaxy.ansible.com/community/molecule and we encourage plugin authors and test writers to either one of:

* Replace `molecule_to_yaml` and `molecule_from_yaml` with their native ansible counterparts.
* Use modules from community.molecule collection by using FQCN,  like `community.molecule.from_yaml`. Remember to add `community.molecule` collection to your `requirements.yaml` and to install it.

As these filters were also present in user managed playbooks like `create.yml` and `destroy.yml`, we aim to make transition easier.

Because this is breaking change, it will only be included in `3.1.0`.

## Reasoning

The main reason behind this move is to finalize decoupling of molecule tool from ansible internals and removing the need to install Ansible python packages in the same python environment as molecule.

If done right, at the end molecule should only be a command line that calls ansible and that the testing playbooks could be run even without molecule itself.

**Comment by ssbarnea** [comment]
@decentral1se @sshnaidm @cloudnull @geerlingguy @greg-hellings Please comment on this move as I want to minimize disruptions for current users and to assure that they have an easy migration path. 

My concerns is that this will initially break most drivers, but I will assure a release is not made before I update most of them.

**Comment by decentral1se** [comment]
Hey, missed this one but aware of it now, when the 3.1 release comes out, I'll let you know how it goes. Thanks.

**Comment by ssbarnea** [comment]
I am still fixing bugs caused by move of docker and podman out of core. It could prove very useful o have someone brave enough to run molecule and main plugins from master branches.
