### ISSUE TITLE
Support for include_tasks in roles.

### ISSUE THREAD

**Issue by matthew-williams** [ansible-community/molecule#2885]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.9.10
  config file = /home/adminlocal/mailrelay.playbook/ansible.cfg
  configured module search path = ['/home/adminlocal/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
molecule 3.0.4
   ansible==2.9.10 python==3.8
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):
- pip

# Desired Behavior

Molecule will honor the include_tasks module relative to the role its ran in.

Questions related to this:
[How do I get molecule to follow include_tasks correctly](https://stackoverflow.com/questions/64362077/how-do-i-get-molecule-to-follow-include-tasks-correctly)
[Pretty frustrated with no support for include_task module from ansible.](https://github.com/ansible-community/molecule/discussions/2884)

Hitting up as many resources as possible after finding no other documentation or issues related to this.

**Comment by fourstepper** [comment]
Do I understand correctly that you are calling molecule on the playbook level?

**Comment by fourstepper** [comment]
I have created a little directory structure like the one you have and include_tasks works fine for me.

The structure:

```
├── molecule
├── playbook.yml
└── role-test
    ├── tasks
    │   ├── main.yml
    │   └── test.yml
```

```
cat role-test/tasks/main.yml
---
# tasks file for role-test
- include_tasks: test.yml
```

```
cat role-test/tasks/test.yml
---
- debug:
    msg: hello world!
```

This also works when the role (`role-test`) is in the `roles/` directory

Is there something I am missing?

**Comment by greg-hellings** [comment]
I do this extensively in my roles and have no issues. Can you point to where your code lives? Or create a minimum reproducer?
