### ISSUE TITLE
Contributing documentation - a slight problem with two URLs

### ISSUE THREAD

**Issue by fourstepper** [ansible-community/molecule#2887]
# Issue Type

- Bug report for the Documentation

Docs URL: https://molecule.readthedocs.io/en/latest/contributing.html#guidelines

3rd bullet point, URLs link to a different page than the one on which we are, and those are broken, f.e. https://molecule.readthedocs.io/en/latest/testing.html#linting

Everything else on there seems fine

**Comment by ssbarnea** [comment]
I see an opportunity for make a first contribution by removing that entire sentence, the one with two broken links.

**Comment by fourstepper** [comment]
Alright, I will get it fixed
