### ISSUE TITLE
login blocking other operations

### ISSUE THREAD

**Issue by heichblatt** [ansible-community/molecule#2905]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.10.2
molecule 3.1.1
   ansible==2.10.2 python==3.8
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

After `molecule create`ing an instance, I would like to be able to `molecule login` and `tail` a log file in one shell session while running `molecule converge` in another.

# Actual Behaviour

$ molecule converge
Retrying to acquire lock on /Users/foo/.cache/molecule/bar/bar, waiting for 30 seconds

I recognize that blocking makes sense for i.e. `molecule create` and `molecule converge`, but I fail to see the reasoning behind making `login` blocking.

**Comment by fourstepper** [comment]
I have noticed this as well and am on the same boat - molecule login shouldn't be blocked

**Comment by fourstepper** [comment]
This looks relevant, but I am not sure

https://github.com/ansible-community/molecule/commit/65ccd6beab63ed3c4901c9ef6296461fe8f375e5

**Comment by ssbarnea** [comment]
The lock was added to prevent parallel conflicts but when I do it I forgot that it may not be uncommon for someone to want to have a sneak preview while a test/converge/verify operation is in progress.

I am not aware of any use-case of `login` option in automation so it should be save to make it bypass the lock.

Any PR that addressed this would be welcomed. What is bit tricky is that ephemeral_directory is a property, so it cannot receive arguments. I am not sure which would be the best approach.

**Comment by fourstepper** [comment]
This seems to a bigger issue than it might've seemed, too bad that the folks are not discussing it here:

https://github.com/ansible-community/molecule/issues/2895

**Comment by zolvaring** [comment]
Crossposting from https://github.com/ansible-community/molecule/issues/2895 to +1 that I'm seeing this issue as well. I don't have any other Molecule tasks running AFAIK, but simply trying to converge the vagrant scenario now fails due to a timeout establishing lock.

Reverting to 3.0.8 restored functionality to the driver for me.

**Comment by dennycrane0** [comment]
@ssbarnea It's not only about having a sneak preview. It's also not working for when opening multiple shells.
Any current plans on how to fix this or are you still looking for a PR?

**Comment by ssbarnea** [comment]
The only thing I can promise is to look at PRs. Other than this, only implementing the features that I need myself.

Happy to receive PRs!!!

**Comment by apatard** [comment]
I don't plan to use such feature but I've made a quick fix for that: https://github.com/apatard/molecule/commit/31780a9ae1ea6e242ab11a4be6474a640c31fb58. Now, if needed, just use ``MOLECULE_NO_LOCK=true molecule login ....`` and the problem describe here should be solved. Given the possible breakages related to disabling the lock, it's set to false by default and not set to true for the ``login`` command.

I'm not sure it's the best way to do that but seems to work. If wanted, I can turn that into a PR.

**Comment by ssbarnea** [comment]
I think it would be better to patch molecule to avoid the lock by default unless `MOLECULE_PARALLEL` is defined. That locked caused more problem than it solved.

**Comment by apatard** [comment]
that's actually a different part of the issue. I mean, this would solve the blocking login issue for a lot of people, but this issue will still be here for people setting ``MOLECULE_PARALLEL``.
