### ISSUE TITLE
Molecule3 -Mutiple scenario testing failed

### ISSUE THREAD

**Issue by chanderthakur** [ansible-community/molecule#2912]
Version Details:
molecule 3.0.8
ansible==2.10.2 python==3.8

Structure:
.
├── defaults
│   └── main.yml
├── files
│   └── logging.conf
├── handlers
│   └── main.yml
├── meta
│   └── main.yml
├── molecule
│   ├── default
│   │   ├── converge.yml
│   │   ├── INSTALL.rst
│   │   ├── molecule.yml
│   │   ├── prepare.yml
│   │   ├── tests
│   │   │   ├── __pycache__
│   │   │   │   └── test_default.cpython-38-pytest-6.1.1.pyc
│   │   │   └── test_default.py
│   │   └── verify.yml
│   └── metricbeat-enabled
│       ├── converge.yml
│       ├── INSTALL.rst
│       ├── molecule.yml
│       ├── prepare.yml
│       ├── tests
│       │   ├── __pycache__
│       │   │   └── test_metricbeat_enabled.cpython-38-pytest-6.1.1.pyc
│       │   └── test_metricbeat_enabled.py
│       └── verify.yml
├── README.md
├── tasks
│   ├── configure.yml
│   ├── install.yml
│   ├── main.yml
│   └── service.yml
├── templates
│   ├── metricbeat-pin.j2
│   └── metricbeat.yml.j2
├── tests
│   ├── inventory
│   └── test.yml
└── vars
    └── main.yml

==================================================================
molecule.ym (indentical in both scenario)
---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint
platforms:
  - name: ubuntu2004
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
verifier:
  name: testinfra

==============================================================

Goal :
I want to test my two different scenario (in default one I am installing metricbeat and putting the same on disabled n stopped mode and in metricbeat-enable I am doing vice versa). I want two containers/instances for the same (I have with separate names of instances too in molecule.yml). so that can test separately.

When I create and converge this without executing the default scenarios ..it gives me belwo mentioned error while login using molecule login command 

ERROR: Instances not created.  Please create instances first.
However that time I have checked docker conatiner/instance is running. And create and converged done successfully then why it is giving me error.

Instance Name    Driver Name    Provisioner Name    Scenario Name       Created    Converged
---------------  -------------  ------------------  ------------------  ---------  -----------
ubuntu2004       docker         ansible             default             false      false
ubuntu2004       docker         ansible             metricbeat-enabled  true       true

===============================================================================

How can I achieve this.. I want two instances for two different scenarios. and want to work in any scenario first means without following any order . Is this possible ? Don't know Is this a bug or not ?

Can anybody help me out ?

Thanks

**Comment by ssbarnea** [comment]
Please do not abuse the issue tracker for support issues.
