### ISSUE TITLE
driver configurable by environment variable

### ISSUE THREAD

**Issue by johrstrom** [ansible-community/molecule#2919]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version && molecule --version
```

ansible 2.10.2
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
molecule 3.1.5
    ansible:2.10.2 python:3.8
    delegated:3.1.5 from molecule
    docker:0.2.4 from molecule_docker
    podman:0.2.3 from molecule_podman

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Hi, I'm not sure if this is a bug or a feature.  I can't currently do it, but I'm not sure if that's expected or not.

What I'd like to do is use a variable to determine what driver to use so that I can run locally with `podman` but whomever (and whatever CI) can still use docker. This way I don't have to force folks to use one container runtime or another, it can be a variable. 
```yaml
driver:
  name: ${CONTAINER_RT:="docker"}
```

This currently fails with this error

```text
ERROR: Failed to pre-validate.

{'driver': [{'name': ['unallowed value ${CONTAINER_RT:="docker"}', 'field \'name\' cannot be coerced: (\'${CONTAINER_RT:="docker"}\', ValueError(\'Invalid placeholder in string: line 1, col 1\'))']}]}
```

**Comment by johrstrom** [comment]
Sorry! this works, apparently there's a big difference between `${CONTAINER_RT:="docker"}` and `${CONTAINER_RT:-"docker"}` in initializing the variables.

**Comment by ssbarnea** [comment]
This ticket looks more like a support ticket. Please use [discussions](https://github.com/ansible-community/molecule/discussions) if you have any usage questions, even for issues that look like bugs.

**Comment by erinn** [comment]
I know this is not a support ticket location, but because I just struggled through this here is some more complete information:
This DOES work (note the lack of quotes):
```
driver:
  name: ${CONTAINER_RT:-podman}
```
This DOES NOT work (note the quotes):
```
driver:
  name: ${CONTAINER_RT:-"podman"}
```
and will result in this:
```
CRITICAL Failed to pre-validate.

{'driver': [{'name': ['unallowed value "podman"']}]}
```
