### ISSUE TITLE
Add support for pdb mode for testinfra

### ISSUE THREAD

**Issue by amarao** [ansible-community/molecule#2968]
- Feature request

# Molecule and Ansible details

```
ansible 2.9.11
  config file = /home/amarao/git/nwaas/ansible.cfg
  configured module search path = ['/home/amarao/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/amarao/venvs/ansible29/lib/python3.8/site-packages/ansible
  executable location = /home/amarao/venvs/ansible29/bin/ansible
  python version = 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]
molecule 3.2.0a0
    ansible:2.9.11 python:3.8
    delegated:3.2.0a0 from molecule
    libvirt:0.0.3 from molecule_libvirt
    openstack:0.1 from molecule_openstack
```
installation method: pip

# Desired Behavior
Right now molecule does not provide a tty to testinfra, so `pytest --pdb` can not interact with user. This mode can be enabled by this sinppet of molecule config:
```
verifier:
  name: testinfra
  options:
    pdb: true
```
It would be nice to have some kind of 'interactive' command line option for molecule to allow operators to have pdb shell in the test. This option should:
1. Add `--pdb` option to testinfra
2. Allow interactive shell for testinfra invocation.

**Comment by ssbarnea** [comment]
You are welcomed to add it, in fact I would even find useful to add a `--pdb` to molecule itself once we address the main issue. Being able to step-in in case of failure is useful.

**Comment by amarao** [comment]
Before I jump into the code, what should it do if verifier is ansible? I suspect, to print warning and ignore.

**Comment by ssbarnea** [comment]
I would start first to investigate what prevents use of interactive tty, I would first test if suprocess-tee library that we are using works with that. Once this is sorted, we can look at details and I can help making it configurable. IMHO, focus on point 2, as adding the argument is easily sorted.

**Comment by aryn-lacy** [comment]
This is already a thing and works exactly as described above. Should this issue be closed?

**Comment by amarao** [comment]
@aryn-lacy, had I missed something? How to invoke pdb for testinfra in molecule?

**Comment by danielhoherd** [comment]
From some quick testing, it looks like this does drop into pdb:

```yaml
verifier:
  name: testinfra
  options:
    pdb: true
```

What is puzzling is that this will not give you the regular prompt, even when typing `interact`. It will be just a blank line. Here is an example of what it looks like:

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

get_vars = {}, host = <testinfra.host.Host ansible://instance>

    def test_correct_exiftool_version(get_vars, host):
        ver = host.run("exiftool -Ver")
>       assert ver.stdout.strip() == get_vars["exiftool_version"]
E       KeyError: 'exiftool_version'

molecule/bionic/tests/test_default.py:29: KeyError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/dho/code/ansible-role-exiftool/molecule/bionic/tests/test_default.py(29)test_correct_exiftool_version()
-> assert ver.stdout.strip() == get_vars["exiftool_version"]
ll
(Pdb)  27       def test_correct_exiftool_version(get_vars, host):
 28         ver = host.run("exiftool -Ver")
 29  ->     assert ver.stdout.strip() == get_vars["exiftool_version"]
interact
*interactive*
dir(ver.stdout)
(Pdb) >>> ['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
```

In the above snip, I typed `ll`, `interact` and `dir(ver.stdout)`

**Comment by amarao** [comment]
It looks like someone had messed with tty settings. May be calling `subprocess.check_output('stty sane')` would return in back to normal?

**Comment by ssbarnea** [comment]
I am almost sure this is related to use use of rich terminal recording feature, something we need in order to be able to capture console output and produce HTML reports.  When trying to fix this, be careful not not break the html report recording feature.
