### ISSUE TITLE
notest tag should not be skip on create/destroy step

### ISSUE THREAD

**Issue by fletort** [ansible-community/molecule#2992]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
```
molecule 3.0.6

ansible 2.9.9

Molecule installation method (one of):
Ansible installation method (one of):

Docker official Image.

Detail any linters or test runners used:

# Desired Behavior

# Actual Behaviour

In my case, it is problematic that the default `molecule-notest` or `notest` tags are passed to the create step.

In my create playbook, i am using a role to create some specific staff.... But this role was tested with molecule... and have some tasks with the given `notest` tag.... so the creation did not work, as theses tasks are not executed.....

For me theses generic tags should be passed only to converge step, no ?

**Comment by decentral1se** [comment]
I would guess limiting skip tags for some steps would inconvenience other users who rely on it. It's quite an edge case you've run into here I would say. That in one instance, you want molecule not to test a role when it is being tested but when being used to support another role under test, you need it to run.

I wonder if there is some way to stop passing this skip logic into roles that are not directly invoked by molecule but then I think that is a slippery slope into what I know is hard to track entrypoints for roles. Given your workaround, I am not sure what else can be done here.

**Comment by jimbo8098** [comment]
Couldn't you just use `molecule converge` for this? There's no final test following that. Perhaps it would help to know why you are looking to skip those tags. I think it would help us understand why this is important in your case and might allow us to get a different viewpoint on other potential issues.

**Comment by ssbarnea** [comment]
I do not think we should add extra complexity for create/destroy as user can easily remove the notest tag from them, they are not present in any embedded playbooks, so not a bug.
