### ISSUE TITLE
Molecule should auto install tested collection during dependency step

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#2997]
# Issue Type

- Feature request

# Desired Behavior

When the user creates scenarios inside a collection they also need to install the collection itself before running molecule or the tests would likely fail to access roles and modules from within the collection.

Until now users either manually added ansible-galaxy install the local collection with something like:
```
    sh -c "rm -rf dist/* .cache/collections/*"
    # build collection
    ansible-galaxy collection build -v -f --output-path dist/
    # install collection in custom location
    sh -c "ansible-galaxy collection install -f dist/*.tar.gz -p .cache/collections"
```

Clearly this is not something convenient and we want to have a seamless experience where molecule scenarios can be run right away without extra user interventions. The tool can easily detect the presence of a collection repository by cheking presence of the `galaxy.yml` file.

It should be noted that Molecule itself already knowns to isolated ansible collections and roles paths to scenario specific folders, so installing these should not pollute user folders.

At this moment dependency already knows to install dependencies but does nothing about local collections, the one being subject to the test.

Sadly Ansible does not provide any way to perform editable installs for collections, so we will need to install it each time forced.

**Comment by ssbarnea** [comment]
Molecule already does this, closing.

**Comment by provenvelocity** [comment]
FYI the solution of using ansible-lint does not work with the latest release of ansible. I converted my requirements to version pinning to force working on the latest and not get behind... famous last words.  

The run with the requirements fails.
ansible
docker
molecule
molecule-docker
molecule-podman
molecule-vagrant
python-vagrant
pytest
pytest-testinfra
yamllint
flake8

But running with this does work:
ansible==3.4.0
docker==5.0.0
molecule==3.3.0
molecule-docker==0.2.4
molecule-podman==0.3.0
molecule-vagrant==0.6.3
pytest==6.2.4
pytest-testinfra==6.3.0
python-vagrant==0.5.15
yamllint==1.26.1
flake8==3.9.2

**Comment by provenvelocity** [comment]
@ssbarnea
