### ISSUE TITLE
Molecule custom Dockerfile

### ISSUE THREAD

**Issue by bcochofel** [ansible-community/molecule#3020]
# Issue Type

Trying to use Dockerfile.j2 to install some packages but doesn't do anything.

- Bug report

# Molecule and Ansible details

```
molecule 3.2.1 using python 3.7 
    ansible:2.10.4
    delegated:3.2.1 from molecule
    docker:0.3.3 from molecule_docker
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

Install the packages from Dockerfile.j2

# Actual Behaviour

Packages not installed

**Comment by decentral1se** [comment]
Uhmm I'm not sure what is going on with plugins but it seems like you need to open this over here:

> https://github.com/ansible-community/molecule-docker

**Comment by decentral1se** [comment]
Also, can you give more details @bcochofel? Where did you put your `Dockerfile.j2` and what was in it? What was the output of the run and perhaps using `--debug`. We can't do much for you with the issue as it is.

**Comment by decentral1se** [comment]
So yes, as I know understand it hopefully correctly, you'll want to re-open this on https://github.com/ansible-community/molecule-docker. This functionality is now based in a plugin. Hope that is clear.

**Comment by bcochofel** [comment]
Yes, thank you
