### ISSUE TITLE
Sign PyPI releases

### ISSUE THREAD

**Issue by maltfield** [ansible-community/molecule#3022]
**Describe the bug**

When a user downloads this python module using `pip`, there is no cryptographic authenticity or integrity validation to protect the user from a MITM attack.

Therefore, this project is making any other projects that obtain the `molecule` module via `pip` in their build process vulnerable to a [watering hole attack](https://en.wikipedia.org/wiki/Watering_hole_attack).

**Expected behavior**

A developer should have a mechanism to cryptographically verify the integrity and authenticity of molecule when obtaining it through `pip`.

**To Reproduce**

`pip install molecule`

**Additional context**

Possible solutions include:

1. Using the [`--sign` argument](https://twine.readthedocs.io/en/latest/#why-should-i-use-this) of `twine` when uploading packages to PyPI

1. Publishing a cryptographically signed document (ideally using `gpg`) listing the hashes for all packages uploaded to PyPI, which users can then pass into `pip` using the [`--hash` argument](https://pip.pypa.io/en/stable/reference/pip_install/#hash-checking-mode)

**Comment by ssbarnea** [comment]
Signing makes sense when missing HTTPS. Because pypi never allows a package to be replaced and because it does support hashing, it also means that signing adds no additional security.

I will close this ticket but if you have proof that other major packages are starting to add signing (especially if they are dependencies), I will reconsider it. I am not against signing, but I am realistic that there are far more important things to be addressed before that.

Note: if you make a PR that enables use of signing on the github action used, I will consider it.

**Comment by maltfield** [comment]
> signing adds no additional security.

Sorry, but that's absolutely incorrect. Https is still at risk of MITM from thousands (million?) of organizations that may have their keys stolen.

> PR that enables use of signing on the github action used,

I do not recommend storing your private keys on github. I've set this up with my github actions for signing *prereleases*, but imho releases should be signed by a key that's not shared.

I don't have a comprehensive list of other packages on PyPi that sign their releases, but here's a few examples of projects that sign their releases on pypi off the top of my head:

# python-gnupg https://pypi.org/project/python-gnupg/
# borg-backup https://pypi.org/project/borgbackup/
# pprofile https://pypi.org/project/pprofile/
# libusb1 https://pypi.org/project/libusb1/

**Comment by ssbarnea** [comment]
I will reconsider it once we have all (or most) dependencies signed. Without this one it makes no sense. AFAIK none is signed, so it makes no sense to start with us.

**Comment by maltfield** [comment]
@ssbarnea what PyPi dependencies do you have in mind? I'll open a ticket with those projects as a start.

**Comment by ssbarnea** [comment]
https://github.com/ansible-community/molecule/blob/master/setup.cfg#L69-L90
