### ISSUE TITLE
Quay docker image publishing missing latest release from pypi

### ISSUE THREAD

**Issue by decentral1se** [ansible-community/molecule#3023]
# Issue Type

- Bug report

# Molecule and Ansible details

N/A

# Desired Behavior

https://quay.io/repository/ansible/molecule?tab=tags has a 3.2.1 release like in https://github.com/ansible-community/molecule/releases.

# Actual Behaviour

https://quay.io/repository/ansible/molecule?tab=tags is missing the latest release. See https://github.com/ansible-community/molecule/releases for latest.

**Comment by decentral1se** [comment]
Aha, I just saw:

> Use of this repository is deprecated as it will no longer receive new builds. From now please switch to use ansible/toolset which also includes a bundle of tools including molecule.

Seems like https://quay.io/repository/ansible/toolset?tab=tags is where it is at now officially?

**Comment by decentral1se** [comment]
ba6496563bbe360693a409657c9c1515df6482eb

**Comment by ssbarnea** [comment]
Yes, https://github.com/ansible-community/toolset project takes care of building and publishing a container.
