### ISSUE TITLE
Molecule environment variables do not work for the verifier directory

### ISSUE THREAD

**Issue by bencardinal** [ansible-community/molecule#3038]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ben/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ben/molecule-env/lib64/python3.6/site-packages/ansible
  executable location = /home/ben/molecule-env/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
molecule 3.2.0 using python 3.6 
    ansible:2.10.3
    delegated:3.2.0 from molecule
    docker:0.3.3 from molecule_docker
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

Detail any linters or test runners used:

# Desired Behavior

Given the following directory tree:

```
my_role
└── molecule
   ├── default
   │  ├── converge.yml
   │  ├── create.yml
   │  ├── Dockerfile.j2
   │  ├── molecule.yml
   │  └── verify.yml
   └── resources
     └── tests
        ├── conftest.py
        └── test_hello_world.py
```
The tests in the resources will work as expected if the `verifier` section of the `molecule.yml` looks like this:

```yaml
  verifier:
    name: testinfra
    directory: ../resources/tests
```
However, I would like to use  the `MOLECULE_PROJECT_DIRECTORY` variable instead of the relative path.

```yaml
  verifier:
    name: testinfra
    directory: ${MOLECULE_PROJECT_DIRECTORY}/molecule/resources/tests
```

# Actual Behaviour
When using the variable I get the following error:
```
INFO     default scenario test matrix: verify
INFO     Running default > verify
WARNING  Skipping, no tests found.
```
I have verified that the `${MOLECULE_PROJECT_DIRECTORY}` does expand to the fully rooted path for `my_role` by inspecting `~/.cache/molecule/my_role/default/molecule.yml` and if I cut and past the fully expanded path from the `.cache` file and assign that to `directory:` explicitly it _does_ work as expected.  There is something about the variable processing in the verify step that isn't working as expected.

**Comment by zhan9san** [comment]
Hi @bencardinal 

This issue is addressed in [_get_tests in #3467](https://github.com/ansible-community/molecule/pull/3467/files#diff-484e298af273a464276755e85baba0628e876f99d4fa6b3488cf269d344a1b30R172-R176)

You can verify it in latest version

```shell
pip install git+https://github.com/ansible-community/molecule.git
```
