### ISSUE TITLE
molecule lint doesn't set ANSIBLE_ROLES_PATH for linting stage

### ISSUE THREAD

**Issue by ultral** [ansible-community/molecule#3055]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.9.13
  config file = None
  configured module search path = ['/home/ms/lgonchar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

molecule 3.2.3 using python 3.6 
    ansible:2.9.13
    delegated:3.2.3 from molecule
    docker:0.2.4 from molecule_docker

ansible-lint --version
ansible-lint 5.0.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

`molecule lint` works

$ molecule --debug lint
DEBUG    Validating schema /home/ms/lgonchar/cde/ansible/roles/cde_common/molecule/default/molecule.yml.
INFO     default scenario test matrix: dependency, lint
INFO     Running default > dependency
WARNING  Skipping, missing the requirements file.
WARNING  Skipping, missing the requirements file.
INFO     Running default > lint
COMMAND: set -e
export ANSIBLE_ROLES_PATH=/home/ms/lgonchar/cde/ansible/roles/cde_common/..
yamllint .
ansible-lint

Loading custom .yamllint config file, this extends our internal yamllint config.
WARNING  Replaced deprecated tag '403' with 'package-latest' but it will become an error in the future.

# Actual Behaviour

```
$ molecule --debug lint
DEBUG    Validating schema /home/ms/lgonchar/cde/ansible/roles/cde_common/molecule/default/molecule.yml.
INFO     default scenario test matrix: dependency, lint
INFO     Running default > dependency
WARNING  Skipping, missing the requirements file.
WARNING  Skipping, missing the requirements file.
INFO     Running default > lint
COMMAND: set -e
yamllint .
ansible-lint

Loading custom .yamllint config file, this extends our internal yamllint config.
WARNING  Listing 2 violation(s) that are fatal
internal-error: the role 'cde_common' was not found in /home/ms/lgonchar/cde/ansible/roles/cde_common/molecule/centos8/roles:/home/ms/lgonchar/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ms/lgonchar/cde/ansible/roles/cde_common/molecule/centos8
molecule/centos8/converge.yml:9:7 [WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
ERROR! the role 'cde_common' was not found in /home/ms/lgonchar/cde/ansible/roles/cde_common/molecule/centos8/roles:/home/ms/lgonchar/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ms/lgonchar/cde/ansible/roles/cde_common/molecule/centos8

The error appears to be in '/home/ms/lgonchar/cde/ansible/roles/cde_common/molecule/centos8/converge.yml': line 9, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - role: cde_common
      ^ here


internal-error: the role 'cde_common' was not found in /home/ms/lgonchar/cde/ansible/roles/cde_common/molecule/default/roles:/home/ms/lgonchar/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ms/lgonchar/cde/ansible/roles/cde_common/molecule/default
molecule/default/converge.yml:10:7 [WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
ERROR! the role 'cde_common' was not found in /home/ms/lgonchar/cde/ansible/roles/cde_common/molecule/default/roles:/home/ms/lgonchar/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ms/lgonchar/cde/ansible/roles/cde_common/molecule/default

The error appears to be in '/home/ms/lgonchar/cde/ansible/roles/cde_common/molecule/default/converge.yml': line 10, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - role: cde_common
      ^ here


You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - internal-error  # Unexpected internal error
Finished with 2 failure(s), 0 warning(s) on 14 files.
CRITICAL Lint failed with error code 2
```

# workaround

There is workaround. we can set ANSIBLE_ROLES_PATH in the lint section
```
lint: |
  set -e
  export ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/..
  yamllint .
  ansible-lint
```

**Comment by gabrielbahniuk** [comment]
The same problem here.

**Comment by goetzc** [comment]
Thanks for the workaround @ultral, this works good!

**Comment by apatard** [comment]
the error comes from newer checks done by ``ansible-lint`` and molecule is not really responsible for it. I bet that if you run manually ``ansible-lint``, you'll get the same error.

From the bug report, the version of ansible-lint is older than 5.0.7 and 5.0.7 have changes that should make things work without the workaround. Please upgrade to 5.0.7, test and if it's not working, I think it would be better to report to ansible-lint.

**Comment by goetzc** [comment]
In my case, `ansible-lint` 5.0.7 is already installed.

![image](https://user-images.githubusercontent.com/2220440/114734605-fc69f100-9d09-11eb-840e-d16d0d7d8ab6.png)

I think the user expects Molecule to set everything specific and necessary for the linters and other steps to work and it's also a more elegant solution. Also there is nothing on the documentation to suggest this other behavior.

**Comment by apatard** [comment]
> In my case, `ansible-lint` 5.0.7 is already installed.
> 
> ![image](https://user-images.githubusercontent.com/2220440/114734605-fc69f100-9d09-11eb-840e-d16d0d7d8ab6.png)

ok. So, no warning about fully qualified role name (fqrn) from prerun, so I guess  ansible-lint managed to find a valid proper fqrn. And ansible-lint is expecting people to use this fqrn inside the playbooks it's linting. So, if the ``converge.yml`` is something like:
```
  roles:
    - role: base
```
won't work. In order to get things working, either:
- fix the playbook to use the fqrn. Check also .cache directory content to check if the fqrn has been properly found by ansible-lint. If not, the ``meta/main.yml`` file may need some fixes.
- tell ansible-lint to ignore 'role-name' rule.

ansible-lint may possibly need to be improved on that point.

> 
> I think the user expects Molecule to set everything specific and necessary for the linters and other steps to work and it's also a more elegant solution. Also there is nothing on the documentation to suggest this other behavior.

From what I understand, with molecule 3, in order to be more flexible, the linting handling is reduced to running the shell script specified in the ``lint`` section of the ``molecule.yml`` file and does nothing more. See https://molecule.readthedocs.io/en/latest/configuration.html#lint. "We decided to maximize flexibility by just calling an external shell command."

@ssbarnea Feel free to correct me if I've said something wrong.

**Comment by ssbarnea** [comment]
There were some recent changes in ansible-lint==5.0.9 related to which Ansible variables are defined or not and I think this bug is no longer valid. You may be surprised but ideally that variable should not be defined.
