### ISSUE TITLE
Molecule converge can't create a temp directory for group_vars on MacOs

### ISSUE THREAD

**Issue by andreas-gold** [ansible-community/molecule#3057]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.10.6
molecule 3.2.3
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

Driver:
- Docker

# Desired Behavior

I would expect, that molecule successfully creates a temp directory for the group_vars as it does for the host_vars directory when executing molecule converge.
My setup is actually working on a windows10 machine (using WSL2 with Ubuntu), but does not on a Mac with MacOs Catalina v10.15.7. 

# Actual Behaviour

Executing molecule converge fails, due to the following Error:

```
TASK [Gathering Facts] *********************************************************
fatal: [myHost]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo unable to find user admin: no matching entries in passwd file/.ansible/tmp `\"&& mkdir \"` echo unable to find user admin: no matching entries in passwd file/.ansible/tmp/ansible-tmp-1614277926.464561-18178-124657968422918 `\" && echo ansible-tmp-1614277926.464561-18178-124657968422918=\"` echo unable to find user admin: no matching entries in passwd file/.ansible/tmp/ansible-tmp-1614277926.464561-18178-124657968422918 `\" ), exited with result 126, stdout output: unable to find user admin: no matching entries in passwd file\r\n", "unreachable": true}
```

This occurs if I set the group_vars either as a link in the ansible provisioner or as a directory inside my molecule scenario and trigger to converge.
However the playbook is running if I remove group_vars and eventually fails later due to the missing group variables.
It seems that internally another kind of mechanism is used to load the host_vars link (or directory) since only using host_vars is not causing a similiar error, so I guess the temp dir for host vars is generated properly.

Changing the tmp path in ansible.cfg as the error message suggests did not solve the problem. Neither did sudo execution.

Additionally the issue creating a temp directory for group_vars seems to be MacOS specific as the same setup runs on my windows machine using WSL2/Ubuntu.

**Comment by fourstepper** [comment]
`stdout output: unable to find user admin: no matching entries in passwd file`

have you tried looking into this?

**Comment by andreas-gold** [comment]
Yes, I know that this issue is somehow connected to missing permissions.
I just don't get why there isn't any trouble with the host_vars too.

But I'm considering that there also could be a difference between the docker versions of my devices. So it could also be unrelated to the OS. I'll check that.

**Comment by andreas-gold** [comment]
Well it's a bit embarrassing, but finally I found the cause. :D
The difference between the working and the failing setup wasn't inside my identical molecule scenario, BUT inside the all.yml (inside the group_vars directory) the ansible ssh user was set to admin - as the error message indicates.

`ansible_ssh_user: admin `

Nevertheless, thank you very much for your efforts!

**Comment by fourstepper** [comment]
I didn't do much :) Glad it's solved.
