### ISSUE TITLE
Add support for checking exit codes on shell dependencies

### ISSUE THREAD

**Issue by jhg03a** [ansible-community/molecule#3070]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.10.5
  config file = /Users/jhg03a/<redacted>/ansible.cfg
  configured module search path = ['/Users/jhg03a/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 24 2021, 13:26:09) [Clang 12.0.0 (clang-1200.0.32.29)]
molecule 3.2.3 using python 3.9
    ansible:2.10.5
    delegated:3.2.3 from molecule
    docker:0.2.4 from molecule_docker
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Currently it appears that the dependency shell module doesn't take into account the exit code from the command.  If something goes wrong in the dependency phase, it's highly likely the rest of the run is going to fail or have inconsistent results.

### Example:
```yaml
dependency:
  name: shell
  command: 'false'
```

**Comment by tadeboro** [comment]
Hi @jhg03a! I prepared a fix for this issue in https://github.com/ansible-community/molecule/pull/3105. Right now, the dependency command will be retried three times before failing (this behavior is hardcoded into molecule). But I hope I can prepare a follow-up PR that will make the number of retries and backoff interval configurable.
