### ISSUE TITLE
driver-template configuration flag missing

### ISSUE THREAD

**Issue by alexnovak** [ansible-community/molecule#3073]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
```
ansible: 2.9.6
molecule: 3.2.2

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

`molecule init secnario` should accept a `--driver-template` configuration flag, which lets you input a directory of cookiecutter templates that can correspond to the `--driver-name` configuration flag.

# Actual Behaviour

When running the following example: `molecule init scenario --driver-name ec2 --driver-template /path/to/template scenario-name`, the following output is returned:
```
Usage: molecule init scenario [OPTIONS] [SCENARIO_NAME]
Try "molecule init scenario --help" for help.

Error: no such option: --driver-template
```

I noticed this when upgrading from version `3.0.2`. I could definitely just have missed the memo and this behavior was deprecated, but based on remaining code it looks like the removal was accidental. A bunch of the logic for the `driver_template` variable still exists in the [scenario.py file](https://github.com/ansible-community/molecule/blob/master/src/molecule/command/init/scenario.py#L92).

The most substantial difference between `3.0.2` ([here](https://github.com/ansible-community/molecule/blob/3.0.2/molecule/command/init/scenario.py)) and the main branch ([here](https://github.com/ansible-community/molecule/blob/master/src/molecule/command/init/scenario.py#L92)) is the removal of 
```
@click.option(
    "--driver-template",
    type=click.Path(exists=True, dir_okay=True, readable=True, resolve_path=True),
    help="Path to a cookiecutter custom driver template to initialize the "
    "scenario. If the driver template is not found locally, default "
    "template will be used instead.",
)
```
From the configuration options, as well as 
```
    driver_template = driver_template or os.environ.get(
        "MOLECULE_SCENARIO_DRIVER_TEMPLATE", None
    )
    if driver_template:
        command_args["driver_template"] = driver_template

```
being pulled from the `scenario` function.
Reintroducing these lines of code makes the command work the way I was expecting.

The docstring is also now a little strange, suggesting that the appropriate command for initializing a scenario with a cookiecutter template is `cd foo; molecule init scenario bar --role-name foo` instead of the previous `cd foo; molecule init scenario bar --role-name foo --driver-template path`. I might be missing something, but I haven't been able to get the former to work as expected.

Super sorry if I missed something and this is deprecated behavior! But enough things looked odd that it seemed worthy to flag. On the chance this _is_ an issue, I'd be happy to make a PR for the changes that appeared to work for me. 
Thanks for your time and effort!

**Comment by tadeboro** [comment]
It seems that this was a deliberate move: https://github.com/ansible-community/molecule/commit/848e9f6b6d23cbdf0996dc08effc589acc8683bf.

It looks like the commit missed some places where the template is used, though, so we should probably clean things a bit more. But before we do that, would you mind explaining how do you use this feature and if replacing it with a plain cookie-cutter command is feasible for you? Thanks.

**Comment by ssbarnea** [comment]
Driver template is used internally in order to retrieve location of templates from within the drivers, but is no longer possible to give custom templates to init. I will be closing this as I do not see it as a bug but let me know if it needs to be reopen.
