### ISSUE TITLE
3.2.4 is broken for docker (at least on Travis)

### ISSUE THREAD

**Issue by jorhett** [ansible-community/molecule#3075]
# Issue Type

- Bug report

# Molecule and Ansible details

Ansible 3.0 with Molecule 3.2.4

Ansible and Molecule installation method:

```
pip3 install molecule[lint,docker]
```

Detail any linters or test runners used:

# Desired Behavior

Travis CI job that worked yesterday with 3.2.3 should work.

# Actual Behaviour

As of this morning all CI jobs with molecule are failing on Travis. The breakage happened when 3.2.4 appeared. Reverting to 3.2.3 fixes it. I'm still debugging but it's hard to iterate usefully on Travis :(

```
INFO     Sanity checks: 'docker'
ERROR! couldn't resolve module/action 'docker_container'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/home/travis/virtualenv/python3.8.3/lib/python3.8/site-packages/molecule_docker/playbooks/destroy.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  tasks:
    - name: Destroy molecule instance(s)
      ^ here
```

**Comment by jorhett** [comment]
Results after change to `pip3 install molecule[lint,docker]==3.2.3`

```
default > destroy
INFO     Sanity checks: 'docker'
PLAY [Destroy] *****************************************************************
TASK [Destroy molecule instance(s)] ********************************************
changed: [localhost] => (item=ubuntu_2004_js_env)
```

**Comment by jorhett** [comment]
[ch197666]

**Comment by jorhett** [comment]
Also, changing to ansible-lint 5.x is going to break a number of people. Why was this a patch release?

**Comment by aminvakil** [comment]
Can you share your travis logs?
FWIW I ran a molecule test just recently and didn't have a problem with molecule 3.2.4.
https://github.com/aminvakil/ansible-role-docker-installation/runs/2124376202?check_suite_focus=true#step:4:10

**Comment by jorhett** [comment]
> Can you share your travis logs?

Private repo so not the entire log. What are you looking for? It doesn't get very far so...

```
$ pip3 install molecule[lint,docker]
Collecting molecule[docker,lint]
  Downloading molecule-3.2.4-py3-none-any.whl (238 kB)
Collecting enrich>=1.2.5
  Downloading enrich-1.2.6-py3-none-any.whl (8.6 kB)
Collecting paramiko<3,>=2.5.0
  Downloading paramiko-2.7.2-py2.py3-none-any.whl (206 kB)
```

.... etc, pretty base 20.04 ubuntu builtin python 3.8

```
$ cd roles/js_env && molecule test
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Running default > dependency
default > dependency
WARNING  Skipping, missing the requirements file.
WARNING  Skipping, missing the requirements file.
INFO     Running default > lint
default > lint
COMMAND: set -e
yamllint .
ansible-lint
flake8
./handlers/main.yml
  2:27      error    no new line character at the end of file  (new-line-at-end-of-file)
./tasks/ubuntu.yml
  10:18     error    too few spaces after comma  (commas)
./tasks/install_nvm.yml
  22:1      warning  comment not indented like content  (comments-indentation)
CRITICAL Lint failed with error code 1
WARNING  An error occurred during the test sequence action: 'lint'. Cleaning up.
INFO     Running default > cleanup
default > cleanup
WARNING  Skipping, cleanup playbook not configured.
INFO     Running default > destroy
default > destroy
INFO     Sanity checks: 'docker'
ERROR! couldn't resolve module/action 'docker_container'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/home/travis/virtualenv/python3.8.3/lib/python3.8/site-packages/molecule_docker/playbooks/destroy.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
  tasks:
    - name: Destroy molecule instance(s)
      ^ here
CRITICAL Ansible return code was 4, command was: ansible-playbook --inventory /home/travis/.cache/molecule/js_env/default/inventory --skip-tags molecule-notest,notest /home/travis/virtualenv/python3.8.3/lib/python3.8/site-packages/molecule_docker/playbooks/destroy.yml
```

Locking the version to 3.2.3 solves the problem fully.

The other PR isn't relevant since it was using Ansible 3.1.0 which includes the necessary community modules.

```shell
$ ansible-galaxy collection list |grep -e docker -e general
community.docker              1.3.0
community.general             2.2.0
```

Using 3.0 also covers that.

```shell
$ ansible-galaxy collection list |grep -e docker -e general
community.docker              1.2.2
community.general             2.0.1
```

**Comment by ssbarnea** [comment]
This is not a bug, please use discussions in the future instead of the issue tracker. Installing ansible itself is outside the scope of molecule cli.

**Comment by jorhett** [comment]
> This is not a bug, please use discussions in the future instead of the issue tracker. Installing ansible itself is outside the scope of molecule cli.

I'm sorry, but on what basis do you make this claim that it's not a bug. It runs in previous version, it fails in the new version. The one and only response to this issue referred to issues with older modules, which I showed to be unrelated as we're using the newer modules.

If you have some justification for calling this not a bug, then please present that.  Closing a repeatable issue with a clear replication state as "not a bug" without any justification isn't very helpful.

ALSO - you didn't reference the semver failure in introducing a major new version with different requirements in a patchfix version.

**Comment by jorhett** [comment]
So I've discovered the problem. Ansible was installed in the system python, molecule was being installed in user space.

```
sudo pip3 install ansible
pip3 install molecule[lint,docker]
```

This used to work in 3.2.3, and stopped working in 3.2.4. Workaround is:

```
sudo pip3 install ansible
sudo pip3 install molecule[lint,docker]
```

I fail to understand why molecule will not run from a user-space installation, and why this behavior change was pushed out in a patchfix release?
