### ISSUE TITLE
The command to enable shell auto completion differs depending on the version of python-click installed

### ISSUE THREAD

**Issue by DanHam** [ansible-community/molecule#3119]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version
ansible [core 2.11.0]
  config file = /home/dan/.ansible.cfg
  configured module search path = ['/home/dan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/dan/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.5 (default, May 12 2021, 17:14:51) [GCC 10.2.0]
  jinja version = 3.0.0
  libyaml = True

$ molecule --version
molecule 3.3.1 using python 3.9
    ansible:2.11.0
    delegated:3.3.1 from molecule
    podman:0.3.0 from molecule_podman
    vagrant:0.2 from molecule_vagrant

# This is relevant too!
$ pacman -Q python-click
python-click 8.0.0-1
```

Molecule installation method (one of):

- source
- pip

Neither. I'm using Arch and installed via `pacman` - the default package manager on Arch. 

Ansible installation method (one of):

- source
- pip
- OS package

OS package

Detail any linters or test runners used:

Linters:
- yamllint
- ansible-lint

Drivers:
- podman
- vagrant

... everything else is pretty standard at the moment.

# Desired Behavior

Working auto completion for the shell.

# Actual Behaviour

Following discussions on irc it was discovered that auto completion has been 'broken' by differences between python-click 7 and 8. Reporting here as requested.

Currently (with python-click 8) the command given to enable autocompletion does not work

```bash
# Does not work with python-click 8
eval "$(_MOLECULE_COMPLETE=source molecule)"
```

When click 8 is installed the command to get auto completion working is:

```bash
# Works with python-click 8
eval "$(_MOLECULE_COMPLETE=bash_source molecule)"
```

Additional info from IRC:

7 expects:

`_MOLECULE_COMPLETE=source_bash molecule` 

See: https://click.palletsprojects.com/en/7.x/bashcomplete/#activation

8 expects:

`_MOLECULE_COMPLETE=bash_source molecule`

See: https://click.palletsprojects.com/en/8.0.x/shell-completion/#enabling-completion

Many thanks

**Comment by ssbarnea** [comment]
This was fixed on master branch. I will make a release today.
