### ISSUE TITLE
using ansible-lint to resolve collection dependencies fails  in latest  ansible

### ISSUE THREAD

**Issue by provenvelocity** [ansible-community/molecule#3135]
# Issue Type

- Bug report

# Molecule and Ansible details
Semie working config
```
ansible 2.10.9
  config file = /Users/H217689/kp/ansible/kp_devops/test/ansible.cfg
  configured module search path = ['/Users/H217689/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/H217689/kp/ansible/kp_devops/test/local_venv/lib/python3.9/site-packages/ansible
  executable location = /Users/H217689/kp/ansible/kp_devops/test/local_venv/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:36:27) [Clang 12.0.0 (clang-1200.0.32.29)]
molecule 3.3.0 using python 3.9 
    ansible:2.10.9
    delegated:3.3.0 from molecule
    docker:0.2.4 from molecule_docker
    podman:0.3.0 from molecule_podman
    vagrant:0.6.3 from molecule_vagrant
```
Not Working Config:
```
ansible [core 2.11.1] 
  config file = /Users/H217689/kp/ansible/kp_devops/test/ansible.cfg
  configured module search path = ['/Users/H217689/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/H217689/.kp_devops/kp_devops_venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/H217689/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/H217689/.kp_devops/kp_devops_venv/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:36:27) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True
molecule 3.3.2 using python 3.9 
    ansible:2.11.1
    delegated:3.3.2 from molecule
    docker:0.2.4 from molecule_docker
    podman:0.3.0 from molecule_podman
    vagrant:0.6.3 from molecule_vagrant
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

Ansible lint

# Desired Behavior

FYI the solution of using ansible-lint does not work with the latest release of ansible. I converted my requirements to remove version pinning to force working on the latest and not get behind... famous last words.

The desired result should be a cache folder somewhere on the machine that contains the current collection and a converge.yml that loads it.

the requirements.txt fails to produce a .chace folder with the current collection. 
ansible
docker
molecule
molecule-docker
molecule-podman
molecule-vagrant
python-vagrant
pytest
pytest-testinfra
yamllint
flake8

the requirements.txt that produces a .chace folder with the current collection. 
ansible==3.4.0
docker==5.0.0
molecule==3.3.0
molecule-docker==0.2.4
molecule-podman==0.3.0
molecule-vagrant==0.6.3
pytest==6.2.4
pytest-testinfra==6.3.0
python-vagrant==0.5.15
yamllint==1.26.1
flake8==3.9.2

# Actual Behaviour

The current version (N) produces no cache folder that I can find that holds the current collection.

The N-1 version of ansible produces a cache folder but I cant not get converge.yml to load the collection and use it.

Side Issue is that I can not get the converge.yml to recognize the current collection even with the old version of ansible-lint... 
I have set the collections path in every way possible and the code is in the path, but the converge playbook does not see it.

molecule.yml

 provisioner:
  name: ansible
  config_options:
    defaults:
      timeout: 30
      system_warinings: false
      collections_paths: .cache/collections
  env:
    ANSIBLE_COLLECTIONS_PATH: .cache/collections. 

per this link
https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
converge trials...

converge.yml1
---
- import_playbook: devops.test.site

converge.yml2
---
- name: Converge
  hosts: all
  collections:
    - devops.test

- import_playbook: devops.test.site

converge.yml3
---
- name: Converge
  hosts: all
  collections:
    - devops.test

- import_playbook: devops.test.site.yml

I also tried the run with several collection cache path locations.... 

 DEBUG: SHELL REPLAY:
ANSIBLE_COLLECTIONS_PATH=.cache/collections ANSIBLE_CONFIG=/Users/H217689/.cache/molecule/test/default/ansible.cfg ANSIBLE_FILTER_PLUGINS=/Users/H217689/kp/ansible/kp_devops/test/local_venv/lib/python3.9/site-packages/molecule/provisioner/ansible/plugins/filter:/Users/H217689/.cache/molecule/test/default/plugins/filter:/Users/H217689/kp/ansible/kp_devops/test/plugins/filter:/Users/H217689/.ansible/plugins/filter:/usr/share/ansible/plugins/filter ANSIBLE_FORCE_COLOR=1 ANSIBLE_LIBRARY=/Users/H217689/kp/ansible/kp_devops/test/local_venv/lib/python3.9/site-packages/molecule/provisioner/ansible/plugins/modules:/Users/H217689/kp/ansible/kp_devops/test/local_venv/lib/python3.9/site-packages/molecule_vagrant/modules:/Users/H217689/.cache/molecule/test/default/library:/Users/H217689/kp/ansible/kp_devops/test/library:/Users/H217689/.ansible/plugins/modules:/usr/share/ansible/plugins/modules ANSIBLE_ROLES_PATH=/Users/H217689/.cache/molecule/test/default/roles:/Users/H217689/kp/ansible/kp_devops:/Users/H217689/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:roles MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=vagrant MOLECULE_ENV_FILE=/Users/H217689/kp/ansible/kp_devops/test/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/Users/H217689/.cache/molecule/test/default MOLECULE_FILE=/Users/H217689/.cache/molecule/test/default/molecule.yml MOLECULE_INSTANCE_CONFIG=/Users/H217689/.cache/molecule/test/default/instance_config.yml MOLECULE_INVENTORY_FILE=/Users/H217689/.cache/molecule/test/default/inventory/ansible_inventory.yml MOLECULE_PROJECT_DIRECTORY=/Users/H217689/kp/ansible/kp_devops/test MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/Users/H217689/kp/ansible/kp_devops/test/molecule/default MOLECULE_SCENARIO_NAME=default MOLECULE_STATE_FILE=/Users/H217689/.cache/molecule/test/default/state.yml MOLECULE_VERIFIER_NAME=ansible MOLECULE_VERIFIER_TEST_DIRECTORY=/Users/H217689/kp/ansible/kp_devops/test/molecule/default/tests

COMMAND: ansible-playbook --diff --inventory /Users/H217689/.cache/molecule/test/default/inventory --skip-tags molecule-notest,notest /Users/H217689/kp/ansible/kp_devops/test/molecule/default/converge.yml
ERROR! Unable to retrieve file contents
Could not find or access '/Users/H217689/kp/ansible/kp_devops/test/molecule/default/kp_devops.test.site' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
CRITICAL Ansible return code was 1, command was: ansible-playbook --diff --inventory /Users/H217689/.cache/molecule/test/default/inventory --skip-tags molecule-notest,notest /Users/H217689/kp/ansible/kp_devops/test/molecule/default/converge.yml

**Comment by ssbarnea** [comment]
Remove `ANSIBLE_COLLECTIONS_PATH` from your molecule file and it should work fine with latest ansible-lint. We now use `~/.cache/...` with hashed directory names for caching collections. I suspect that this variable disables our custom cache use. 

If you run the linter in verbose mode you should see exactly where it does build the cache. Same logic is used by molecule itself (it reused the same code from the linter).

**Comment by ssbarnea** [comment]
Now I seen you reported the bug against 3.3.0 when latest version is 3.3.3. Please report bugs only on latest versions.

**Comment by provenvelocity** [comment]
I upgraded and tested and the new ansible lint directory is not in the collections paths for the converge phase of the code but is in the roles I added the detail to the bug you closed if you would like to re open if I'm still not missing something ha!

@ssbarnea

**Comment by provenvelocity** [comment]
Sorry had to many tickets open I had added this response to the wrong ticket....

**Comment by provenvelocity** [comment]
@tadeboro  I think this is still an issue can you let @ssbarnea  know I think I got to chatty messing up tickets... he might not have seen the new update :)

**Comment by provenvelocity** [comment]
If you notice each of the env configurations are different and result in different running environments for each step. I am working to see if this is the issue or if there is a bigger issue with ansible also. 

Either way the code should all use the same env configuration code so that it is consistent....
