### ISSUE TITLE
Can't create new scenario

### ISSUE THREAD

**Issue by staticdev** [ansible-community/molecule#3158]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible [core 2.11.1] 
  config file = None
  configured module search path = ['/home/static/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/static/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/static/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/static/.local/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
  jinja version = 2.11.2
  libyaml = True
molecule 3.3.4 using python 3.8 
    ansible:2.11.1
    delegated:3.3.4 from molecule
    docker:0.2.4 from molecule_docker
```

Molecule installation method (one of):

- pip 

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

`molecule --debug create --scenario-name scenarioname` get scenario created.

# Actual Behaviour

`CRITICAL 'molecule/scenarioname/molecule.yml' glob failed.  Exiting.`

**Comment by tadeboro** [comment]
The `molecule create ...` will not create a new scenario, it will create instances for a selected scenario. What you are looking for is the `molecule init scenario` subcommand.
