### ISSUE TITLE
fix "Edit on Github" link in docs

### ISSUE THREAD

**Issue by ltalirz** [ansible-community/molecule#3220]
The "Edit on Github" link in the [molecule docs](https://molecule.readthedocs.io/en/latest/) is currently broken (due to the switch from `master` to `main`).

This comment https://github.com/readthedocs/readthedocs.org/issues/7907#issuecomment-828827927 explains how to fix it in the RTD dashboard

**Comment by gundalow** [comment]
@ltalirz Thank you for reporting this, and for finding how to fix the issue.

The "Edit on GitHub" link has now been fixed, though it seems like there is a CSS problem, potentially due to the release of `sphinx-rtd-theme-1.0.0`
