### ISSUE TITLE
Ansible output is not displayed

### ISSUE THREAD

**Issue by ashemsay** [ansible-community/molecule#3232]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible [core 2.11.4]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.virtualenvs/mol/lib/python3.7/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.virtualenvs/mol/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
  jinja version = 3.0.1
  libyaml = True
molecule 3.4.0 using python 3.7
    ansible:2.11.4
    delegated:3.4.0 from molecule
```

Molecule installation method:

- pip

Ansible installation method:

- pip

Detail any linters or test runners used:

# Desired Behavior

When runing a molecule command, the ansible output gets displayed

# Actual Behaviour

When running a molecule command, all the molecule output is displayed but not the ansible-playbook output (i.e "PLAY ... TASK...").

To reproduce the issue, I used this simple script named `test.sh` in my test directory:

```
#!/bin/bash
VERSION=${1:-HEAD}
if [ "$VERSION" == "HEAD" ];then
  pip install molecule ansible
else
  pip install molecule==3.1.5 ansible==2.9.25
fi
ansible --version && molecule --version
rm -rf myrole
molecule init role myrole
cd myrole || return
molecule --debug destroy
```
- I created a virtualenv and ran `./test.sh` to install last version of molecule and ansible and execute a `molecule destroy` and got no ansible output
- I created another virtualenv and ran `./test.sh 1` to install version 3.1.5 of molecule and version 2.9.25 of ansible and this time got the expected ansible

I posted the complete output [here](https://bin.idrix.fr/?7ea238e01d3a6dbc#4mNDxMoTRVJ7xpJ3eqBaSD2dKVZ8TeMSdzP1xTRQRim1)

I used the `molecule destroy` command as it is the easiest reproducible example but I experience the same issue with `molecule converge` or `molecule test`.

I tried on debian buster (python 3.7) and ubuntu focal (python 3.8)

**Comment by ssbarnea** [comment]
I think that may be a regression specific to `3.4.0`, have you tried to use the latest 3.3.x version, or the `3.5.0a0` pre-release? Known if bug reproduces on these or not could help us address it faster.

It should be noted that I am actively working towards 3.5.0 release which will have a lot of internal changes that can affect how output from ansible is processed.

**Comment by ashemsay** [comment]
This does not seem to be the case, I updated my script

```
#!/bin/bash
VERSION=${1:-HEAD}
if [ "$VERSION" == "HEAD" ];then
          pip install molecule ansible
elif [ "$VERSION" == "3.5" ];then
          pip install molecule==3.5.0a0 ansible==2.9.25
elif [ "$VERSION" == "3.4" ];then
          pip install molecule==3.4.* ansible==2.9.25
elif [ "$VERSION" == "3.3" ];then
          pip install molecule==3.3.* ansible==2.9.25
elif [ "$VERSION" == "3.2" ];then
          pip install molecule==3.2.* ansible==2.9.25
elif [ "$VERSION" == "3.1" ];then
          pip install molecule==3.1.5 ansible==2.9.25
fi
ansible --version && molecule --version
rm -rf myrole
molecule init role myrole
cd myrole || return
molecule --debug destroy
```

And ran some tests, I have the issue with these:

- 
	```
	molecule 3.2.4 using python 3.7
			ansible:2.9.25
			delegated:3.2.4 from molecule
	ansible 2.9.25
		config file = None
		configured module search path = ['/home/testuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
		ansible python module location = /home/testuser/.virtualenvs/molecule-3.2/lib/python3.7/site-packages/ansible
		executable location = /home/testuser/.virtualenvs/molecule-3.2/bin/ansible
		python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
	```
- 
	```
	molecule 3.3.4 using python 3.7
			ansible:2.9.25
			delegated:3.3.4 from molecule
	ansible 2.9.25
		config file = None
		configured module search path = ['/home/testuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
		ansible python module location = /home/testuser/.virtualenvs/molecule-3.3/lib/python3.7/site-packages/ansible
		executable location = /home/testuser/.virtualenvs/molecule-3.3/bin/ansible
		python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
	```
- 
	```
	ansible 2.9.25
		config file = None
		configured module search path = ['/home/testuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
		ansible python module location = /home/testuser/.virtualenvs/molecule-3.4/lib/python3.7/site-packages/ansible
		executable location = /home/testuser/.virtualenvs/molecule-3.4/bin/ansible
		python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
	molecule 3.4.0 using python 3.7
			ansible:2.9.25
			delegated:3.4.0 from molecule
	```
- 
	```
	molecule 3.5.0a0 using python 3.7
			ansible:2.9.25
			delegated:3.5.0a0 from molecule
	ansible 2.9.25
		config file = None
		configured module search path = ['/home/testuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
		ansible python module location = /home/testuser/.virtualenvs/molecule-3.5/lib/python3.7/site-packages/ansible
		executable location = /home/testuser/.virtualenvs/molecule-3.5/bin/ansible
		python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
	```
- 
	```
	molecule 3.4.0 using python 3.7
			ansible:2.11.4
			delegated:3.4.0 from molecule
	[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.7.3
	(default, Jan 22 2021, 20:04:44) [GCC 8.3.0]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can
	be disabled by setting deprecation_warnings=False in ansible.cfg.
	ansible [core 2.11.4]
		config file = None
		configured module search path = ['/home/testuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
		ansible python module location = /home/testuser/.virtualenvs/molecule-head/lib/python3.7/site-packages/ansible
		ansible collection location = /home/testuser/.ansible/collections:/usr/share/ansible/collections
		executable location = /home/testuser/.virtualenvs/molecule-head/bin/ansible
		python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
		jinja version = 3.0.1
		libyaml = True
	```
The only one producing the expected behaviour is molecule 3.1.5
Can you at least reproduce it?

**Comment by ssbarnea** [comment]
I can confirm the bug, it also happens to me with molecule from trunk.

**Comment by ssbarnea** [comment]
I think i found the bug, try to add `subprocess-tee!=0.3.3` and tell me if it is fixing your problem, if confirmed I will yank that release made yesterday and look for a fix for it.

**Comment by tdmdema** [comment]
> I think i found the bug, try to add `subprocess-tee!=0.3.3` and tell me if it is fixing your problem, if confirmed I will yank that release made yesterday and look for a fix for it.

I had the same problem, but this woraround fixed it.

**Comment by bshewale** [comment]
> I think i found the bug, try to add `subprocess-tee!=0.3.3` and tell me if it is fixing your problem, if confirmed I will yank that release made yesterday and look for a fix for it.

it's working for me :) Thanks!

**Comment by ssbarnea** [comment]
I just yanked the 0.3.3 release and created https://github.com/pycontribs/subprocess-tee/issues/46 for tracking. Rerunning CI jobs should be enough. For local, you may want to recreate the virtualenvs to remove the rotten apple.

**Comment by ashemsay** [comment]
Perfect, thanks for the very quick fix.
