### ISSUE TITLE
Toolset image is discontinued

### ISSUE THREAD

**Issue by mprasil** [ansible-community/molecule#3420]
The [documentation](https://github.com/ansible-community/molecule/blob/4f8fd055ab183a1928b3460ccb39e94ac6162ebf/docs/installation.rst#docker) links to toolset project for running molecule in docker container. This [project](https://github.com/ansible-community/toolset) has now been deprecated, so that part of docs should be either removed or updated with some other appropriate option.

**Comment by mprasil** [comment]
The toolset project links to [creator-ee project](https://github.com/ansible/creator-ee) as replacement, however that one does not seem to be suitable for production use:

> We should also mention that this container must not be used in production by Ansible users.

**Comment by mprasil** [comment]
Thanks for update @ziegenberg, is there any info on the current recommendation to not use creator-ee image in production?

**Comment by nodje** [comment]
It's really hard to understand what happened to the ansible/toolset project.

If I hadn't stumble upon this issue I'd have opened another issue.

Why not simply put up a notice in the ansible/toolset repo?

**Comment by ziegenberg** [comment]
Hi

@nodje the actual repo for the now deprecated `ansible/toolset` image lives here https://github.com/ansible-community/toolset and has a link to creator-ee.

@mprasil Can you be a bit more specific? The toolset image wasn't meant for production use either, as far as I know.

**Comment by ziegenberg** [comment]
@mprasil the Readme.md of toolset says"
> Toolset bundles Ansible developing and testing tools in a single container.
In my opinion that's a rather clear indicator that this is not meant to be used in production.

**Comment by mprasil** [comment]
@ziegenberg well certainly not clear enough for me. 😅 But fair enough. If I understand it right, there is no plan to provide production-grade Ansible image?

**Comment by ziegenberg** [comment]
@mprasil that's an answer I cannot give. Maybe @ssbarnea can jump in with more information?

**Comment by mprasil** [comment]
I still feel like this should be mentioned [here](https://molecule.readthedocs.io/en/latest/installation.html#docker) as well. The Docker installation method is mentioned there with pip which I assume is meant to be used in production. Had I just read the Molecule docs, I'd be under impression, that production-grade Molecule image is provided. (which is likely why I considered the toolset image to be suitable for such purpose)

**Comment by zhan9san** [comment]
Hi @mprasil 

IMHO, for simplicity, you can build customized image, referring to https://github.com/ansible-community/molecule-docker/issues/139#issuecomment-1093796496. And tou can decide which tools would be packaged into image in your control.

Besides, [creater-ee](https://github.com/ansible/creator-ee#ansible-creator-execution-environment) is another project, as it says, it's not for production use.
 > This is a container (execution environment) aimed towards being used for development and testing of the Ansible content. We should also mention that this container must not be used in production by Ansible users.

**Comment by mprasil** [comment]
@zhan9san that's indeed what I've been doing. I just think having an development image in the docs as one of the installation methods for the tool is a bit misleading.

**Comment by ziegenberg** [comment]
Molecule aids in the development and testing of Ansible roles. You are talking about production-grade Ansible images. I'm not entirely sure why you need a production-grade Ansible image for a development tool!? In my eyes creator-ee seems a pretty good fit for molecule. One could argue that creator-ee is a bit too big for your standard CI/CD pipeline (see ansible/creator-ee/issues/41) but for production, I personally would create my own EE, tailormade for my use-case with just the tools I need. I'm sure you know about Ansible Builder: https://github.com/ansible/ansible-builder
