### ISSUE TITLE
Drop cookiecutter from molecule

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#3486]
As the future of cookiecutter project seems to be not sure I would like to propose dropping it before it becomes a real issue, even a security one (yep current release 1.7.3 from pypi being affected by one command injection security issue).

I personally reached a point where I am ok with any of the following approaches:

* use either ansible playbooks for templating
* removal of init functionality (templating)

I am fully aware that some people might like this but I do not think that the maintenance burden justifies keeping that feature, especially as its interaction with molecule provisioner plugins makes it even more problematic to use and debug.

As this is likely to count as a major change, it should be planned for v4 which is already on main branch. If anyone is interesting in helping with this task, please let me know.

## References

* https://github.com/cookiecutter/cookiecutter/issues/1555
* https://github.com/cookiecutter/cookiecutter/issues/1636
* https://github.com/cookiecutter/cookiecutter/issues/1642

**Comment by zhan9san** [comment]
i'd like to have a try

**Comment by ssbarnea** [comment]
Super! Basically I would look into using ansible itself to do the templating, or jinja2. Keep in mind that we do also have plugins that add their own templates.

As it would be a breaking change it, we could expect to need to update the plugins and/or templates, but the goal is to minimize the amount of change if possible.

**Comment by jensens** [comment]
Cookiecutter is live again - we released 2.1.0 https://pypi.org/project/cookiecutter/2.1.0/
