### ISSUE TITLE
Release schedule for  v3.6.2?

### ISSUE THREAD

**Issue by amarao** [ansible-community/molecule#3547]
Sorry for bringing up this topic as a bug, but I've tried all other ways of communication without success.

What are release plans for 3.6.2? There are few bugs in 3.6.1, which was patched and accepted in master, but those changes wasn't released yet.

**Comment by amarao** [comment]
Oh, there are discussions!

**Comment by scjones-attunely** [comment]
Actually, looks like downgrading to 3.5.2 might work - but 3.6.1 seems sort of broken

**Comment by yodatak** [comment]
Same for me here
