### ISSUE TITLE
molecule is not able to load the module utilities

### ISSUE THREAD

**Issue by gyuvaraj10** [ansible-community/molecule#3562]
### Discussed in https://github.com/ansible-community/molecule/discussions/3561

<div type='discussions-op-text'>

<sup>Originally posted by **gyuvaraj10** May 31, 2022</sup>
I have module utilities in my root project folder under "library" and the module_utils property is configured in ansible.cfg under root directory. Now when I run <molecule test> command, the molecule is not able to understand the module utilities directory and throwing the following error.

Root Project folder:
![image](https://user-images.githubusercontent.com/8053219/171254699-f5e2770c-f25c-41e9-ad1b-e97a38489ad1.png)

ansible.cfg:
![image](https://user-images.githubusercontent.com/8053219/171254842-36290dd5-d5c2-43e8-b010-609b23c94aad.png)

molecule.yml:
---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
     managed: False
     ansible_connection_option:
        ansible_connection: local
platforms:
  - name: instance
provisioner:
  name: ansible
  log: True
  config_options:
    defaults:
      module_utils: ../../../library
  env:
    ANSIBLE_CONFIG: ../../../ansible.cfg
    ANSIBLE_ROLES_PATH: $ANSIBLE_ROLES_PATH:../../../../roles
    ANSIBLE_LIBRARY: $ANSIBLE_LIBRARY:../../../../library
  options:
    vvv: True
  inventory:
     links:
       group_vars: ../../../../group_vars/
       hosts: ../../../../inventories/single-machine/hosts
       host_vars: ../../../../inventories/single-machine/host_vars/
verifier:
  name: ansible
  lint:
    name: ansible-lint

molecule test: **output:**
fatal: [localhost]: FAILED! => {"msg": "Could not find imported module support code for ansible.modules.start_on_demand_backup.  Looked for (['ansible.module_utils.aws_deployment_util.AWSDeploymentUtility', 'ansible.module_utils.aws_deployment_util'])"}

Note: none of the configuration added to ansible.cfg is available to molecule.</div>

**Comment by zhan9san** [comment]
Hi @gyuvaraj10 

I am glad to help you on this issue.

Could you please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?
