### ISSUE TITLE
Providing tags for task to run only in molecule test - Opposite of "notest"

### ISSUE THREAD

**Issue by nodje** [ansible-community/molecule#3585]
It seems an obvious need to me, maybe it's not.
In any case I couldn't find any reference to this either on the web or here in the issues.

There should be a tag available that does the opposite of the `notest` tag: something like `onlytest` that would allow task to be run only when the playbook is ran by molecule.

Or am I missing something?

**Comment by zhan9san** [comment]
IMHO, if you add tags in your role, and a tag is added it in `converge.yml`, only tasks matched the tag would be run.

Does it make sense?

**Comment by nodje** [comment]
That sure works, thank you.
I'd have to add `--tags "untagged, onlytest"` to each molecule execution though.

Would still feel easy and confortable to know a "onlytest" tag makes sure the task is only executed by Molecule, regardless of anything else.

**Comment by nodje** [comment]
That sure works, thank you.
I'd only have to add --tags "untagged, onlytest" to each converge.yml include_role task. which is fine contrary to what I said in my earlier post.
