### ISSUE TITLE
Remove cerberus dependency from molecule

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule#3637]
As https://github.com/pyeve/cerberus is no longer actively maintained we should aim to remove it from molecule ASAP, preferably replacing it with python-jsonschema validator, which is already used by many of our projects.

If anyone wants to work in this, please let me know. I will do my best to provide support.

**Comment by zhan9san** [comment]
@ssbarnea 

It's new to me, but I'd like to have a try.

**Comment by greg-hellings** [comment]
How close is a 4.{next} release? Was trying to get Molecule put into my system but I can't get around Cerberus 1.3.4 being packaged up. Seeing this is fixed has me itching for a new Molecule release (might be overdue since 4.0.1 was in July).

**Comment by ssbarnea** [comment]
@greg-hellings I am releasing it now a 4.0.2, forgot.
