### ISSUE TITLE
Unable to dial down Ansible log output

### ISSUE THREAD

**Issue by davestephens** [ansible-community/molecule#3654]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible [core 2.12.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/david/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
  jinja version = 3.0.3
  libyaml = True
molecule 4.0.1 using python 3.10 
    ansible:2.12.7
    delegated:4.0.1 from molecule
    docker:2.0.0 from molecule_docker requiring collections: community.docker>=3.0.0-a2
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

Detail any linters or test runners used:

# Desired Behavior

I'd like to be able to dial down the log verbosity during runs. I understand from the docs that it should be possible.

So my log output should be:

```
INFO     Running default > prepare
INFO     Running default > converge
INFO     Running default > idempotence
```
...and so on

# Actual Behaviour

The log output is like this:
```
INFO     Running default > prepare
<very long ansible-playbook output>
INFO     Running default > converge
<very long ansible-playbook output>
INFO     Running default > idempotence
<very long ansible-playbook output>
```
...and so on

I've tried the `--no-debug` switch, as well as adding the following:

```
provisioner:
  name: ansible
  log: false
```
None of the above seems to work.

**Comment by jseguillon** [comment]
Hi @davestephens thanks for reporting, I think best way to reach your goal is to tune your ansible config to use an alternative callback plugin. 

Try with an ansible.cfg containing:
```
[defaults]
stdout_callback = dense
```

There are more ansible callbacks available, inlcuding `null`: https://docs.ansible.com/ansible/latest/collections/index_callback.html

**Comment by jseguillon** [comment]
hi @davestephens 
can we close this issue or do you need more help ?

**Comment by davestephens** [comment]
Forgot to come back to this, apologies - your suggestion worked perfectly, thank you 👍
