### ISSUE TITLE
Documentation for verifier is missing and 404 page rendering wrong

### ISSUE THREAD

**Issue by marcidy** [ansible-community/molecule#3835]
I'm using firefox 102.7.0 esr 64bit.  The doc at https://molecule.readthedocs.io/configuration/#verifier is 404, and the 404 page renders really poorly.  Everything is fullscreen width.  Here's the burger menu:
![image](https://user-images.githubusercontent.com/5845312/221644727-562e7ab7-e22e-40fe-bddf-8f8246fcb9ce.png)

That's my full screen browser window!

**Comment by ssbarnea** [comment]
Already fixed, we had a mistake in RTD config.
