### ISSUE TITLE
Broken links in documentation on the "getting started" page

### ISSUE THREAD

**Issue by dtufood-kihen** [ansible-community/molecule#3844]
I'm not sure if this is the correct please to report issues with the documentation website.

But these links on the [Getting Started Guide](https://molecule.readthedocs.io/en/latest/getting-started/) webpage in the docs is broken in the [Inspecting the molecule.yml](https://molecule.readthedocs.io/en/latest/getting-started/#inspecting-the-moleculeyml) section

- [dependency](https://molecule.readthedocs.io/configuration/#dependency)
- [driver](https://molecule.readthedocs.io/configuration/#driver)
- [platforms](https://molecule.readthedocs.io/configuration/#platforms)
- [provisioner](https://molecule.readthedocs.io/configuration/#provisioner)
- [verifier](https://molecule.readthedocs.io/configuration/#verifier)

**Comment by jpodivin** [comment]
Still a problem. At least the stable version is fine.
